### ISSUE TITLE
What does "END_REVERSE" mean, and how to continue from here?

### ISSUE THREAD

**Issue by vanbeveren** [ndierckx/NOVOPlasty#100]
For one of my plastid assemblies, I get what looks like an unfinished assembly, as it doesn't show me the assembly options at the end of the run. In the "Merged_contigs" file it does list how the contigs are connected, like so:

```
LINKS BETWEEN CONTIGS
---------------------

04----> 02 OR 03
02----> 05 OR 06
11654----> END_REVERSE
05----> 07 OR 08
03----> 05 OR 06
21654----> END_REVERSE
07----> 21654 OR 11654
06----> 07 OR 08
08----> 21654 OR 11654
START----> 04 OR 01
01----> 02 OR 03
```

All options would end with one of the two contigs with irregular IDs (11654 and 21654), which aren't in the Contigs file, but I can find them in the extended log. I assume it means that the final contig doesn't link back to the actual start, but instead to the reverse complement of the starting contig, but I'm not sure. I'm also not sure how to progress further to try to fix this assembly. 

Any help would be appreciated!
[log_extended_pt-5b.txt](https://github.com/ndierckx/NOVOPlasty/files/3405639/log_extended_pt-5b.txt)

**Comment by ndierckx** [comment]
Yes that's what it means. But what do you use as a seed, because it starts in a repetitive region, which is not ideal? Best not to use a complete genome as seed file, because it will just use the beginning of the sequence to seed and those are often problematic regions. Best to use some gene, doesn't have to be from the same species

**Comment by vanbeveren** [comment]
Thanks, I used a prediction of the rbcL gene to assemble the plastid genome. I have quite a few sequenced and most of them are circular now. It's really nice because some of these plastid genomes, are very dissimilar and some times much bigger than typical plastid genomes.

Currently, there are still two plastid genomes that are not completely. From what I can tell it is for different reasons. In one case (Rbre) there is repetitive region that is likely to long for Illumina to cover. From what I can see NOVOPlasty tries to keep extending it on one end untill it reaches the maximum size I have given in the configuration file. The output only gives me one contig just over the maximum size. You can also see that the spades assembly reaches the same issue.

![Rbre_spades_graph](https://user-images.githubusercontent.com/39235945/62613527-e8050c80-b909-11e9-811f-36c436c1c2bb.png)

I actually have another plastid with a similar issue where it did resolve, it recognized that both ends of the contig are seperated by a repetitive region, and give a sinlgle "Option" for the circular assembly. In this case however it doesn't seem to work, I have tried different kmers as well.

The other plastid genome (Ssub) has a small sequence between two contigs that both NOVOPlasty and spades can't resolve. I assume this bit is repeated to some extend as well, but I'm not entirely sure. You can find the spades image below, I also included two log files with different amount of RAM given. Both extended log files (also for Rbre) are attached.

![Ssub_spades_graph](https://user-images.githubusercontent.com/39235945/62614489-c7d64d00-b90b-11e9-89bd-56bc7b5193a3.png)

If you have time it would be great if you could have a look on how I could get circular plastid genomes for these two. Thanks!
[log_extended_Ssub_12GB.txt](https://github.com/ndierckx/NOVOPlasty/files/3476797/log_extended_Ssub_12GB.txt)
[log_extended_Ssub_32GB.txt](https://github.com/ndierckx/NOVOPlasty/files/3476798/log_extended_Ssub_32GB.txt)
[log_extended_Rbre.txt](https://github.com/ndierckx/NOVOPlasty/files/3476799/log_extended_Rbre.txt)

**Comment by ndierckx** [comment]
Hi, Sorry I don't have the time to look at these individual cases at the moment. Some complex genomes take a bit of manual work and even then it is not always possible to circularize, but I am currently switching jobs so won't have the time the next months

**Comment by vanbeveren** [comment]
Alright, I'll see what I can do. Probably "Ssub" can be fixed manually (as there is only one small contig in between). For Rbre, since the repeated region between the contig is of very high coverage, I'm looking into whether we can use long-read sequencing instead.
