### ISSUE TITLE
Question: Assembly excluding seed

### ISSUE THREAD

**Issue by OnlyHigh** [ndierckx/NOVOPlasty#101]
Hi, 
Regarding issue #13, 
I'm assembly two contigs, one contig containing the 80% of the mitochondria and another contig containing exclusively the seed, 

I'm using COI amplicon as seed and assembling from RNA-seq 

Is normal to break the assembly around the seed?
Cheers, 
Luis Alfonso

**Comment by ndierckx** [comment]
Hi,

Normally not, maybe try another seed
But it works for RNA-seq, because I designed it for WGS, I thought RNA-seq doesn't always contain the complete mito genome?

**Comment by OnlyHigh** [comment]
Hi, 
I used the largest contig of the first assembly as seed of a second assembly and then the two contigs of the first where merged.
Regarding the RNA-seq, you can recover some part of the mitocondria, in some cases, the complete genome... some parts are better than none haha. 

Thanks for the answer, 
Cheers, 
Luis Alfonso.
