### ISSUE TITLE
Does seed choice create gaps?

### ISSUE THREAD

**Issue by Astahlke** [ndierckx/NOVOPlasty#103]
Hello, 

The NOVOPlasty assembly of our chloroplast genome yielded several contigs with gaps relative to our seed reference. When we used PCR to resolve these gaps and merge contigs, we found that they were actually not gaps in our assembly, rather indel differences between the genomes. Is this due to the seed we chose and NOVOPlasty's algorithm? 

Thanks for this software! 

Amanda

**Comment by ndierckx** [comment]
Hi,
It's a de novo assembly, so will never really base on the reference file, it can just be used to resolve the inverted repeats and get a complete unique circular assembly (in best case)

**Comment by Astahlke** [comment]
I understand! Thanks for the reply @ndierckx!
