### ISSUE TITLE
Interpreting VCF file results

### ISSUE THREAD

**Issue by elsemikk** [ndierckx/NOVOPlasty#104]
Hi,

Thank you so much for developing this useful tool!

I have a question about interpreting the VCF file results, in particular the allele frequencies. Are the allele frequencies reported for the reference or alternate allele? For example in my Homoplasmy_project.vcf there are several SNPs with very high allele frequency reported, for example: AF=0.998;DP=1990;FR=R. Would this be the allele frequency of the alternate allele, meaning the reference sequence is probably an error?  In the Possible_NUMTs_project.vcf there are some some SNPs with very low allele frequency reported, would that also be the allele frequency of the alternate allele that is the NUMT? In the Heteroplasmy_project.vcf file instead there are two allele frequencies reported, for example AF=0.984,0.0153;DP=2086;FR=R;LCR=SNR. Is the first allele frequency the frequency of the reference, followed by the alternate allele?

Thank you for clarification. 
Else

**Comment by ndierckx** [comment]
Hi,

Which version did you use? Because I changed quite a bit in the latest versions.

**Comment by elsemikk** [comment]
Thanks for the quick reply!
I used version 3.0 to assemble the mitogenome but later I used 3.7 for the heteroplasmy detection, with the assembly from 3.0 as the input seed and reference sequence.

**Comment by ndierckx** [comment]
Would it be possible to share your output files? You can mail them to me, my email is on github. And the assembled mitogenome was from the same dataset?
