### ISSUE TITLE
run two dataset at the same time with paired-end reads

### ISSUE THREAD

**Issue by biocoreexpert** [ndierckx/NOVOPlasty#107]
I have two datasets containing two paired-end files each.

dataset1_R1.fastq
dataset1_R2.fastq

dataset2_R1.fastq
dataset2_R2.fastq

How do I combine these if I want to use both datasets at the same time?
I guess merging both forward-read files is not possible since they are from different datasets?

**Comment by ndierckx** [comment]
Are the datasets from the same sample? and do they have the same read length and insert size?

**Comment by biocoreexpert** [comment]
Not exactly the same samples, but same sample type, you can view them as biological replicates. Same read length and insert.

**Comment by ndierckx** [comment]
If it is the same individual, same read length and insert, you can just merge the forward reads and merge the reverse reads. Unless the read ids have a different structure, but that is probably not the case

**Comment by biocoreexpert** [comment]
Thanks, I will try that
