### ISSUE TITLE
set platform in configure file

### ISSUE THREAD

**Issue by uzma-researcher** [ndierckx/NOVOPlasty#111]
Hi Nicolas,
I got this problem that 'Platform has to be 'illumina or 'ion', please check the configration file'', when running configure file although I set platform as illumina.  I  have emailed you my configure file. Would you please see and help me out?
Best,
Uz

**Comment by ndierckx** [comment]
Hi,
I am currently on holiday so can't be of much help. I assume you also have the same problem when using windows to alter the configuration file? I will fix it when I am back but can't you use the fix proposed in topic #42 ?

**Comment by uzma-researcher** [comment]
Thank you for your reply. Yes I have tried that also downloaded Sublime text and then opned my file and again saved as txt, but it didn't work, got same issue when I ran the command. I think I have to wait until you join back.
Thank you!Best,Uzma
UzmaPhD ScholarPlant Systematics and Evolution LaboratoryDepartment of PlantBiotechnology
Atta-ur-Rahman School of Applied Biosciences (ASAB)
National University of Sciences and Technology (NUST)
H-12, Islamabad, Pakistanhttps://uzma-researcher.weebly.com/
 

    On Monday, October 14, 2019, 10:36:28 PM GMT+5, Nicolas Dierckxsens <notifications@github.com> wrote:  
 
 
Hi,
I am currently on holiday so can't be of much help. I assume you also have the same problem when using windows to alter the configuration file? I will fix it when I am back but can't you use the fix proposed in topic #42 ?

**Comment by ndierckx** [comment]
Maybe try to redownload the config file again and use sublime

**Comment by uzma-researcher** [comment]
Okay, I'll try and let you know how it works.Thank you!Best,
UzmaPhD ScholarPlant Systematics and Evolution LaboratoryDepartment of PlantBiotechnology
Atta-ur-Rahman School of Applied Biosciences (ASAB)
National University of Sciences and Technology (NUST)
H-12, Islamabad, Pakistanhttps://uzma-researcher.weebly.com/
 

    On Monday, October 14, 2019, 10:42:51 PM GMT+5, Nicolas Dierckxsens <notifications@github.com> wrote:  
 
 
Maybe try to redownload the config file again and use sublime

**Comment by uzma-researcher** [comment]
Hi Nicolas,Yes it works now!Thank you!Best,
UzmaPhD ScholarPlant Systematics and Evolution LaboratoryDepartment of PlantBiotechnology
Atta-ur-Rahman School of Applied Biosciences (ASAB)
National University of Sciences and Technology (NUST)
H-12, Islamabad, Pakistanhttps://uzma-researcher.weebly.com/
 

    On Monday, October 14, 2019, 10:42:51 PM GMT+5, Nicolas Dierckxsens <notifications@github.com> wrote:  
 
 
Maybe try to redownload the config file again and use sublime
