### ISSUE TITLE
How to deal with multiple libraries?

### ISSUE THREAD

**Issue by LIZW2019** [ndierckx/NOVOPlasty#113]
Hi,

Great appreciation for your wonderful job! I am now working on a soybean genome, its raw sequencing data are made up of two libraries, both contain all the information in soybean genome, just with different insert lengths(270bp VS 500bp). Which one should I choose? Or should I do them both and choose the better result? Or try to merge them together first?
Looking forward to your answer!

God bless you,
Li

**Comment by ndierckx** [comment]
Hi,

Currently it is not possible to combine multiple libraries. I would try both, because assemblies don't take long. If you don't have enough coverage, you could just merge both and give an insert size in the middle.
