### ISSUE TITLE
The suitable length of seed?

### ISSUE THREAD

**Issue by LIZW2019** [ndierckx/NOVOPlasty#114]
Hi,

Thank you for your reply yesterday and I am now have a question again.
What's the suitable length of seed? I am assembling soybean genome and the total length of the reference genome is 964M, and my sequencing data is 146G for each direction (I am going to use sub sample of 25% of it and i wonder am wondering if it is suitable too).

Looking forward to your reply!
Jesus love you,
Li

**Comment by ndierckx** [comment]
I assume you want to assemble the chloropalst?
Any length above 100bp is fine. For chloroplast genomes I would recommend to use the RuBP seed sequence from the github page. If your plant is too distant you can get another seed, but doesn't have to be the same species
