### ISSUE TITLE
Plastomes - loss of one IR

### ISSUE THREAD

**Issue by matiaskohler** [ndierckx/NOVOPlasty#115]
Dear all,

I'm wondering how NOVOPlasty deals with reads from samples that presumably doesn't have one of the IR region. As far as I'm able to check, it's seems that the assembler understand that regions of the contig with higher coverage of reads than the rest of the contig are the putative IR region. Am I right?

**Comment by ndierckx** [comment]
Hi,
That's no problem. NOVOPlasty never looks to the coverage depth or the IR regions. If there are IR regions, they are usually not resolved, you get 2 possible assembly outputs (each with a different orientation of the region between the IR's. If you have a close enough reference, NOVOPlasty can resolve this automatically by checking the orientation in the reference. So no IR just makes it easier.
