### ISSUE TITLE
Cannot open perl script

### ISSUE THREAD

**Issue by Chloisf** [ndierckx/NOVOPlasty#116]
Hello,
I am sorry to ask a question that might be trivial. 
I am a begginer in bioinformatics and trying to learn how to use NOVOPlasty using the test files.
I downloaded the mitochondrial test files and put them in the same directory as the NOVOPlasty3.7.2.pl file. 
When I type `perl NOVOPlasty3.7.2.pl -c config_mito_test.txt` in the terminal
I get this error `Can't open perl script "NOVOPlasty3.7.2.pl": No such file or directory`.
I don't understand why since I put everything in the same directory, in which I am in the terminal.

I would be very grateful if someone has an idea to fix this problem!
Thank you!

**Comment by ndierckx** [comment]
Hi, are you on a Windows? If could be Perl is not installed yet?
https://www.perl.org/get.html

**Comment by Chloisf** [comment]
Hello!
Thank you for answering. 
Yes I am on Windows. I also wondered if it was about Perl. I checked with `perl -v`
and it appears I do have pearl installed as this is what it shows 
`This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi`

**Comment by ndierckx** [comment]
can you show a screenshot of your terminal?
Because I don't know what's wrong, if it doesn't find the perl file, it means you are doing something wrong

**Comment by Chloisf** [comment]
Hello,
Thank you!
Please find the screenshot below.

![screenshotterminalnovoplasty](https://user-images.githubusercontent.com/57893316/69040165-addef700-0a30-11ea-9d00-0480529b183e.JPG)

**Comment by ndierckx** [comment]
Hi,
It's because you have .txt behind all your files...
You did use the download button on github the download the zipped file or not? Because I had a user before who got the html scripts of each of the files in stead of downloading it

**Comment by Chloisf** [comment]
Hi!
Oooh that is right. Indeed I individually downloaded each file by clicking download and then download it by right clicking on the newly opened page displaying the file. Thank you for spotting the error, next time I will know! 
I downloaded the whole NOVOPlasty-master file, unzip it and put it in my directory (chloisf on the screenshot) then tried again. This time the pl file is indeed displayed as pl and not pl.text. However e as I try to run it I have a new error `Can't open perl script "NOVOPlasty3.7.2.pl": Permission denied`.
I'm sorry I think it's still a bit blurry for me how to download and where to put the files...

**Comment by ndierckx** [comment]
If you don't have permission on your cluster to run anything, I can't help you there. You should contact the administrator
