### ISSUE TITLE
Linear genomes

### ISSUE THREAD

**Issue by AllanSSX** [ndierckx/NOVOPlasty#12]
Hi,

I'm currently working on the assembly of endosymbiotic genomes and I would like to know if it is not problematic to working with linear genomes for NOVOPlasty. Do I've have to be careful with some parameters?

Thanks

**Comment by ndierckx** [comment]
Hi,

No it's not a problem, just keep in mind that it will try to circularize once it is in given genome range, so put it high enough to make sure it doesn't circularizes duplicated regions. The contig merging function won't work though, so you will need to do that manually, but you can still look at the links between the contigs in the merged file.
How large are those genomes?

**Comment by AllanSSX** [comment]
Ok, thanks!

The genomes size from close species vary between 8Mbp and 20Mbp. I've already done a de novo assembly using SOAPdenovo2 and I've isolated scaffolds from the endosymbiont, ~5Mbp but it's highly fragmented.

**Comment by ndierckx** [comment]
Ok, that are large genomes, haven't tested it yet on similar genomes so can't say what the results will be.
Is the coverage higher than the nuclear genome and are their duplicated regions between endosymbiont and the nuclear or mitochondrial genome?

**Comment by AllanSSX** [comment]
Yes, the coverage is quite a bit higher than for the host genome. For the structure, I don't think the endosymbiont genome share some regions with the host genome or with the organelles. Most of the closed species from my endosymbionte do not contain repeat elements or duplicated regions and the genes are very compacted for an eucaryote genome.

**Comment by ndierckx** [comment]
Might work, I am sure you get larger contigs than SOAP (creates lots of small contigs in my experience)
You could do some runs with different seeds derived from your current assembly. Maybe it is best to use the mito stand, good luck!

**Comment by AllanSSX** [comment]
Yes, I hope! With SOAP, I've 3488 scaffolds and most of them are quite short. I've a question for the input seed: should I gave all the scaffolds or only the longest?
Thanks for the advices!

**Comment by ndierckx** [comment]
Just give one contig, size doesn't matter, it just uses the seed to retrieve a read and then it will assemble in both directions starting from that read, so best not too close to either end of your genome. What kind of endosymbionts are you studying, i am just curious?

**Comment by AllanSSX** [comment]
Ok thanks!
I'm studying a subclass of fungi, Microsporidia. That are strict unicellular parasites with the most compacted genomes in Eukaryotes, the most smaller is about 3Mbp! And I'm focus on the studying of a genus that able to change the host genetic sex (male -> female) to ensure his transmission in the population.

**Comment by ndierckx** [comment]
Ok, you can let me know how the results are and if you send me the extended log I can estimate if there is room for improvement. I working on a assembler for larger genomes, so maybe it work better, but will see how it goes first..
