### ISSUE TITLE
NOVOPlast3.8.pl

### ISSUE THREAD

**Issue by scrameri** [ndierckx/NOVOPlasty#120]
Dear Nicolas,

You made some cool developments on NOVOPlasty v. 3.8, which I wanted to try out. However, the main NOVOPlast3.8.pl script on GitHub has been deleted 4 days ago. Do you plant to upload it again soon?

Best regards,
Simon

**Comment by ndierckx** [comment]
Hi,

There was a bug in that version, but will upload it again today
