### ISSUE TITLE
Not resolving the inverted repeats in mito_plant mode

### ISSUE THREAD

**Issue by SaiReddy-A** [ndierckx/NOVOPlasty#127]
Hello, 
Thank you for the NOVOPlasty, it's a great tool. I've used for my plant chloroplast assemblies and it worked perfectly. 
However, when I tried to use NOVOPlasty for mitochondrial assembly (using mito_plant option), the assembly is not able to get past the repeat sequence (~1500 bp) and giving me a circularized assembly  of length ~50 kb, where the original assembly is around ~300 kb. 
The chloroplasts also had inverted repeats, yet the NOVOPlasty was able to resolve both the repeats, It's not the same case with the mito_plant though. I would really appreciate it if you could help with this problem. 

Thank you!!

**Comment by ndierckx** [comment]
Hi,

Plant mitochondria are very hard to assemble, often impossible with short reads, sometimes even with long reads, they can differ even a lot between individuals.
Could you send me the log file, will check if you adjust something

**Comment by SaiReddy-A** [comment]
Thank you for your response. I have tried different genome range and able to get two autonomous rings. However, it looks impossible to get all of the mitochondrial sequences.
