### ISSUE TITLE
Any chance to proceed very short reads?

### ISSUE THREAD

**Issue by OmonkeyGOD** [ndierckx/NOVOPlasty#128]
Hi,
I am trying to use NOVOPlasty to assemble a fungal mitogenome. However, I got this error: Unable to read any data from the read files. Check your files and maybe try to move the files to the same directory as the Perl file Inappropriate ioctl for device. 
I set k-mer as 23 and provided a reference genome sequence. The reads in fastq file are very short, around 36. Is this the reason for the error?
@ERR062316.1 HWI-EAS422_30GRKAAXX_2_1_409_1525 
GGAGTAGATATTATATTCTGTAGGGTGTTTTGCTCT
+ERR062316.1 HWI-EAS422_30GRKAAXX_2_1_409_1525 
>>>>>>>>><>><><>>>>8>>3<<73;<<<%0<+<
@ERR062316.2 HWI-EAS422_30GRKAAXX_2_1_785_608 
GGAACAACCTGCTGCACCTGACCAACATGCCCGTGA
+ERR062316.2 HWI-EAS422_30GRKAAXX_2_1_785_608 
88<<<<<<<<<<<<<<<<83<<<<<+<<8<3<<<8:
@ERR062316.3 HWI-EAS422_30GRKAAXX_2_1_247_1437 
GTAGAGGATGGGGACTGGGAAGAATGTGGCTGACAT

**Comment by ndierckx** [comment]
Hi,

Yeah I think 36 p is too short, I think lower limit is around 50 bp

**Comment by OmonkeyGOD** [comment]
Thank you for your reply.
