### ISSUE TITLE
Having trouble understanding VCF file

### ISSUE THREAD

**Issue by OmonkeyGOD** [ndierckx/NOVOPlasty#129]
Hi~
I assembled a mitogenome with a reference. 
But the .vcf is so confusing. E.g. some records got "AF=;" and what does this mean?
For some pos without DP info, does that robust? 
At the pos 355 where ref and alt are both G, does this mean in my data there is 0.702 chance 355 will be G and otherwise, G is missing? 
I also attached the log files. Hope it will help.
Thank you very much!
![Screen Shot 2020-04-02 at 3 12 55 AM](https://user-images.githubusercontent.com/56337391/78220756-1aaed700-7490-11ea-9388-4647002078ed.png)
[log_CM11_S1.txt](https://github.com/ndierckx/NOVOPlasty/files/4419432/log_CM11_S1.txt)
[log_extended_CM11_S1.txt](https://github.com/ndierckx/NOVOPlasty/files/4419433/log_extended_CM11_S1.txt)

**Comment by ndierckx** [comment]
By developing the heteroplasmy function, I messed up the code of the variance detection. I still have to have to fix it, but I thought nobody was using that function, so i didn't had the motivation yet to do it :) I hope I will find some time to fix it..
