### ISSUE TITLE
no seed in final assembly

### ISSUE THREAD

**Issue by j131j131** [ndierckx/NOVOPlasty#13]
First of all thank you for the amazing piece of software!
I am trying to use version 2.5.6.
Sometimes the "final assembly" - either from Contigs.. or Circularized... files do not have anything in common with the seed file given in config.txt file. How is that possible??

**Comment by ndierckx** [comment]
I will have something in common, at least a sequence as long as the kmer you selected.
What kind of seed you are using and what you trying to assemble?
Sometimes a chloroplast seed can initiate a mitochondrial assembly, so you have to select a good seed for chloroplast assembly (it's explained in the paper)

**Comment by j131j131** [comment]
I am trying to assembly some tough animal mitochondria. They do contain large amounts of repetitive sequences and may even be fragmented. I already had some pieces assembled so I used those as seeds. The seed sequence length was at least 2 kbp and may have already contained some (not many) msat-like repeats. NOVOPlasty produced "Circularized assembly" slightly bigger than the seed (3.5 kbp long) but dotplot show no significant overlap between the seed and the final assembly. After a closer inspection the result was composed of tandem repeats only... 
I do realize the case may be too difficult to actually solve with short reads only, just exploring the new opportunity your assembler clearly gives.
Oh, the reads are input from >300M genomic PE reads from HiX, 2x150bp; I used a machine with 256GB RAM and the coverage for the regions I have already assembled seems to be OK, somewhere around 200-300x.
So do you think it would be better to use rather short seed but derived from the most reliable source? With high specificity, expected good coverage, simple structure (no repeats) to start with?

**Comment by ndierckx** [comment]
Hi,

Short reads will always have their limitations on repetitive regions. NOVOPlasty can work quite well if the repeats are not identical or not too long, otherwise it will get stuck. Since the whole assembly is a tandem repeat I would indeed use a seed with no repeats, so that the assembly can at least start outside the repetitive region. If the region is not too long it should be able to jump passed the repetitive region
