### ISSUE TITLE
Selecting a seed

### ISSUE THREAD

**Issue by dcraheem** [ndierckx/NOVOPlasty#133]
The mt genomes I am assembling using novoplasty represent several species in a single land-snail genus. I have previously assembled and annotated complete mt genomes for other species in this same genus. 

1) Would the sequence of a highly-conserved gene (e.g. cox1, cox2 or cox3) from one of these previously assembled genomes make a suitable seed for my novoplasty assembly? 

2) If I use a gene like cox1, should the sequence of the whole gene be used? For my genus, the total length of the cox 1 gene is c. 1600 bp  (700-800 bp for the cox 2 and cox 3 genes).

**Comment by ndierckx** [comment]
seed doesn't matter, can use a mouse sequence for human, still works
length doesn't matter as long not shorter than the read length, probably will only use the first 100 to 200 bp anyway

**Comment by dcraheem** [comment]
Do you mean that  novoplasty probably uses only the first 100-200bp of the seed sequence?

**Comment by ndierckx** [comment]
Yes, unless it doesn't finds a match there, it will continue further

**Comment by dcraheem** [comment]
Thanks very much for the advice and the software.
