### ISSUE TITLE
Two merge options with identical assemblies.

### ISSUE THREAD

**Issue by OmonkeyGOD** [ndierckx/NOVOPlasty#137]
Hi~
When I assemble some samples, it gives me several contigs. It seems some contig combinations can also be circularized.  But with this sample, I got two identical merged results. Could you please help check my results? Thank you very much! The log files are attached. 
Also, sometimes I got more than one contigs, does this because the assembler could not elongate from one side of the contig and restart from the other side? Or there are some ambiguous loci or missing parts in the dataset. Could it result from heteroplasmy? Thanks~
[Merged_contigs_SRR6669917.txt](https://github.com/ndierckx/NOVOPlasty/files/4497534/Merged_contigs_SRR6669917.txt)
[log_extended_SRR6669917.txt](https://github.com/ndierckx/NOVOPlasty/files/4497535/log_extended_SRR6669917.txt)

**Comment by ndierckx** [comment]
Multiple contigs can because of several reasons, duplications, inverted repeats...
Those two identical contigs, you can ignore, just see it as one.

**Comment by OmonkeyGOD** [comment]
I see. Thanks~
