### ISSUE TITLE
Bug in repetitive region is resolved (assembly didn't stop and made huge extende log files). 25/01/17

### ISSUE THREAD

**Issue by j131j131** [ndierckx/NOVOPlasty#14]
Are you sure this bug is fixed in 2.5.6?
I am still observing such behaviour...
j131

**Comment by ndierckx** [comment]
I haven't observed it anymore but could maybe still happen in some cases.
Could you send me the extended log so I can check what the problem is?
I the log gets to big just abort it once it gets in the repetitive region

**Comment by j131j131** [comment]
When I increase just the genome size parameter the assembly will grow up to this size, using the same repeats, with the coverage falling indefinitely (down to 1).

[config.zip](https://github.com/ndierckx/NOVOPlasty/files/878558/config.zip)
[log_extended_test.zip](https://github.com/ndierckx/NOVOPlasty/files/878550/log_extended_test.zip)

**Comment by ndierckx** [comment]
I am on holiday in Myanmar so can't fix the problem now, but I think you are assembling the mitochondrial genome, so try a different seed and then the repeats shouldn't occur. Try the RUBP unit as seed, always works for me, don't have to be from a close related species

**Comment by j131j131** [comment]
Enjoy your holidays, there is no rush.  I think I can manually close the assembly with reasonable confidence anyway.
It is animal mtDNA (no RUBP?) and I have tried various seeds already, same result. The problem may be that the repeat region is flanked from the other side by a long homopolymeric run located few hundred bp upstream. So the circular map seems to be: "several kb of regular sequence - homopolymer - few hundred bp regular sequence - repeat region - regular sequence". I guess this may make the "jump over the repeats" difficult. Still, the assembler should not get stuck at the repeat and should not produce endless array of repeats so I still consider this behavior a bug.

**Comment by ndierckx** [comment]
Ok thanks for telling me, it seems the bug isn't completely fixed then.
I will try to fix it and upload a new version when I am back!
That homopolymer could make jumping difficult indeed

**Comment by ndierckx** [comment]
Hi it looks it repeats a 1000 bp region, never saw this in organelle regions, so in the next version, the assembler will not get stuck anymore but will also not be able to continue the assembly(for now, looking in to it)
