### ISSUE TITLE
regex issue

### ISSUE THREAD

**Issue by brunonevado** [ndierckx/NOVOPlasty#144]
Hi,

Running the latest NOVOplasty (4.1) I got a regex error:

21786 bp assembledQuantifier follows nothing in regex; marked by <-- HERE in m/* <-- HERE T*C*T*TATA/ at NOVOPlasty/NOVOPlasty4.1.pl line 15460.

Previous run with the same dataset but using a different K-mer terminated correctly, so doesn't seem to be an input issue.

Let me know if you need more info to deal with this,
Thanks,
Bruno

**Comment by ndierckx** [comment]
Hi,

Thanks for the reporting the bug, it were some redundant lines. I removed them so it should be fixed with version 4.2 I uploaded

Greets,

Nicolas
