### ISSUE TITLE
Invalid seed issue

### ISSUE THREAD

**Issue by brenna-levine** [ndierckx/NOVOPlasty#147]
Hi,
I'm keep getting the invalid seed message when I use the "mito" program, regardless of the seed that I use (I have tried many). I know my files have mitochondrial reads in them, as I have previously aligned these to a reference genome, and that I have high coverage. Here is my log file (the extended doesn't seem to have much information in it):

Project:

Project name = test
Type = mito
Genome range = 12000-22000
K-mer = 33
Max memory =
Extended log = 1
Save assembled reads = no
Seed Input = sequence.fasta
Extend seed directly = no
Reference sequence =
Variance detection =
Chloroplast sequence =

Dataset 1:

Read Length = 250
Insert size = 500
Platform = illumina
Single/Paired = PE
Combined reads =
Forward reads = reads_1.fastq
Reverse reads = reads_2.fastq

Heteroplasmy:

Heteroplasmy =
HP exclude list =
PCR-free =

Optional:

Insert size auto = yes
Use Quality Scores =

Subsampled fraction: 90.97 %
Forward reads without pair: 26
Reverse reads without pair: 0

Retrieve Seed...

INVALID SEED, PLEASE TRY AGAIN WITH A NEW ONE

The seed is:

>MT882033.1
CAAAGGTAGCATAATAATTTGTTTTTTAATTGGAAACTAGTATGAATGGTCATACGAGGGATTGACTTTC
TTTATCTTACTTAAATTAATTTTATTTTTCTGTGAAAAAGCAGAGATTTCATTAGTAGACGATAAGACCC
TTTAAAACTTTATTCATTATAGAAGTATAATTTTGTTAGGTTTTAATAGTGTACTTTTTTAATGAGTTTT
GTTGGGGCGACAGGTAAATTTATTTAACTTTATTTTTGTTTTTCACTAATTAGTGTTTATTTGATCCAGA
TTTAGTTTTGATTATAAGTTTAAGTTACTT
Can you advise?

Thanks,

Brenna

**Comment by ndierckx** [comment]
I saw you just closed it when I was looking :) 
But sorry, I can't tell what the problem is from this log file..
