### ISSUE TITLE
Empty files but "The genome has been circularized"

### ISSUE THREAD

**Issue by mjnetherland19** [ndierckx/NOVOPlasty#148]
Hello,

After removing adapters with Trimmomatic and using a read as a seed, I was given the exact same output as you see in the log.

However, the log I have provided shows the seed as the RuBP file provided by NOVOPlasty. I did this to see if I would obtain the same output by using a seed that I knew was correct to use.

Since the problem is not with the seed, is there something that Trimmomatic is doing while removing the adapters, or could it be a problem with my reference sequence?

Also, on the topic of valid seeds, is it necessary for the seed not to be trimmed or error corrected? I would like to try and use one of my own reads again.

Here is the log file:

[log_NOVOPlasty.txt](https://github.com/ndierckx/NOVOPlasty/files/5335622/log_NOVOPlasty.txt)

Thank you for your time.

**Comment by ndierckx** [comment]
Hi,

Could you run it again with extended log to 1, and send me that file?

**Comment by mjnetherland19** [comment]
Unfortunately, it looks to be the same:

[log_NOVOPlasty2.txt](https://github.com/ndierckx/NOVOPlasty/files/5336305/log_NOVOPlasty2.txt)

**Comment by ndierckx** [comment]
yeah but that is the log file again, there should be an extended log file?

**Comment by mjnetherland19** [comment]
Here it is:

[log_extended_AAffAnton.txt](https://github.com/ndierckx/NOVOPlasty/files/5336341/log_extended_AAffAnton.txt)

**Comment by ndierckx** [comment]
This is weird, it's the same as the normal log..
Which version you used, will test it on my laptop

**Comment by mjnetherland19** [comment]
Version 4.2

**Comment by ndierckx** [comment]
I don't see how it is possible that you don't get anything in your extended log, could you redownload the NOVOPlasty and config file? You never changed anything in the code?

**Comment by mjnetherland19** [comment]
I downloaded the newest version 4.2.1 and reran it
Here's the extended log:
[log_extended_AAffAnton.txt](https://github.com/ndierckx/NOVOPlasty/files/5336903/log_extended_AAffAnton.txt)

No, I didn't change anything in the code

**Comment by ndierckx** [comment]
Hi,

Sorry forgot to answer, it's because you didn't put any genome range, so it finishes the assembly immediately

**Comment by mjnetherland19** [comment]
Interesting. I thought it was odd I didn't see it in the output. But it's been in my config file for every run. There's

**Comment by ndierckx** [comment]
Can you redownload the config file and fill it in again? 
That usually works...

**Comment by mjnetherland19** [comment]
Worked like a charm. Thanks!
