### ISSUE TITLE
Request for tagged releases

### ISSUE THREAD

**Issue by Wildish-LBL** [ndierckx/NOVOPlasty#15]
Hi,

thanks for developing and maintaining NOVOPlasty! Can I make a request that you please tag new releases with the version number. That way we can just download the archive, rather than having to pull the HEAD of the git repository. It's a safer way of making sure we get the right version, in case something changes in the HEAD.

 I see you do have tagged versions, but only as far as 2.4, not up to the latest version. It would be great if you could do this in future :-)

 Thanks in advance,
 Tony.

**Comment by ndierckx** [comment]
Hi,

Added the latest version, will try to do it after each release

Greets

**Comment by Wildish-LBL** [comment]
wow, that was fast! Thank you :-)
