### ISSUE TITLE
Out of Memory / 'Max memory' can only be an integer, the amount is always in GB of RAM, don't add a unit!

### ISSUE THREAD

**Issue by bioramg** [ndierckx/NOVOPlasty#150]
Hi,
I am trying to assemble the plant mitochondrial genome using Novoplasty. I am having issues with memory. My server is having 320 GB RAM, 12 core, and 12 TB hard drive space. 
1. If I do not mention anything on Max memory option in the configuration file, I am getting a message "Retrieve Seed...Out of Memory!" and could not run any other programs for at least 24 h.
2. If I mention 290 on Max memory option in the configuration file, then I am getting a message " 'Max memory' can only be an integer, the amount is always in GB of RAM, don't add a unit ! "

Configuration file:
Project:
-----------------------
Project name          = plant_mt
Type                  = mito_plant
Genome Range          = 700000-850000
K-mer                 = 33
Max memory            = 290
Extended log          = 0
Save assembled reads  = no
Seed Input            = /home/Novoplasty/295K_contig.fasta
Extend seed directly  = no
Variance detection    =
Chloroplast sequence  = /home/Novoplasty/plant_cp.fasta

Dataset 1:
-----------------------
Read Length           = 151
Insert size           = 550
Platform              = illumina
Single/Paired         = PE
Combined reads        =
Forward reads         = /home/1_paired.fq
Reverse reads         = /home/2_paired.fq

Heteroplasmy:
-----------------------
MAF                   =
HP exclude list       =
PCR-free              =

Optional:
-----------------------
Insert size auto      = yes
Use Quality Scores    = no
 
I tried with even 0.1% of raw reads, getting the same error. What could be the problem and how to solve it?
Thank you.

**Comment by ndierckx** [comment]
Hi,

Can you send me the log file?
I think the problem is with your config file, some other people had also some similar problems.
The config file can get corrupted, but I don't know how (maybe caused by the text editor
Are you using Windows, Mac or Linux?

And that problem is always resolved by redownloading the config file...

**Comment by bioramg** [comment]
Thank you for your response.
I restarted my server computer and it's working fine with the above-mentioned commands.
I would like to know how to set the output path and which one is the output file. I obtained so many output files and could not see which one is the final result?

**Comment by ndierckx** [comment]
The output files will always get the tag from the project name in the config fiel, soyou need to change this project name for every run!
I will make an output directory option for the next update

**Comment by bioramg** [comment]
Thank you
