### ISSUE TITLE
qsub issue: file not found

### ISSUE THREAD

**Issue by rspfau** [ndierckx/NOVOPlasty#153]
I'm attempting to run NOVOplasty on a remote computer cluster using a qsub script, but it returns "file not found". 

When I have the read files in the same directory as NOVOplasty script, it runs fine. But I need to have the read files in a shared directory. In the config file, I reference the absolute path of the file in the shared directory. I know this path works and the file is there because I can execute "zcat /DAS/sharedData/tarleton/lepus_europaeus_1.gz | head -n 8" from any directory and view the first 8 lines of the read file. 

Is this a problem with the computer cluster, NOVOplasty, or my own ignorant error?

The screenshot showing shared directory path, qsub script, config file, the cluster output file are attached.

[lepus_novoplasty.qsub.txt](https://github.com/ndierckx/NOVOPlasty/files/5397969/lepus_novoplasty.qsub.txt)
[test1.o73326.txt](https://github.com/ndierckx/NOVOPlasty/files/5397964/test1.o73326.txt)
[config_lepus.txt](https://github.com/ndierckx/NOVOPlasty/files/5397875/config_lepus.txt)
![shared-directory](https://user-images.githubusercontent.com/20186858/96385379-1363c800-1159-11eb-8f0b-848d636b0c7a.JPG)

**Comment by ndierckx** [comment]
It should not be a problem, I also run it like that so..

If you go to /home/pfau/lepus in the command line, does it work when you enter "cd /DAS/sharedData/tarleton/" ?

**Comment by ndierckx** [comment]
And your files are not fasta.gz or fastq.gz, it are illumina reads inside the zipped file?

**Comment by rspfau** [comment]
We identified the problem as being on the computer cluster. Thanks for confirming that NOVOplasty works in this environment. If you're interested in knowing, I am teaching a Genetic Techniques class were students are using NOVOplasty to assemble mitogenomes and then annotate them. We thank your for providing our students an easy entry into genomics and bioinformatics.

**Comment by ndierckx** [comment]
Ah that's great! :)
