### ISSUE TITLE
many short contigs in mito_plant mode

### ISSUE THREAD

**Issue by SaiReddy-A** [ndierckx/NOVOPlasty#156]
Hello, 
I have been trying to assemble the mitogenome of Solanum, using 10X data. I removed the barcode sequences using longranger basic and then ran NOVOplastyv4.2.1. But i'm getting so many contigs that are very small  which makes it difficult to assemble. Could you please have a look. 

I tried to assemble the plastome with the same data but i had no issues. I'm attaching both the log files, and extended log files. 

Thank you!! 

[log_mito.txt](https://github.com/ndierckx/NOVOPlasty/files/5460803/log_mito.txt)
[log_extended_mito.txt](https://github.com/ndierckx/NOVOPlasty/files/5460804/log_extended_mito.txt)
[log_extended_cp.txt](https://github.com/ndierckx/NOVOPlasty/files/5460813/log_extended_cp.txt)
[log_cp.txt](https://github.com/ndierckx/NOVOPlasty/files/5460815/log_cp.txt)

**Comment by ndierckx** [comment]
Hi,

Plant mitochondrial genomes are just too complex to assemble with short reads, havent' see many successes, even with long reads. You put 40000-50000 as genome range, they aren't they usually larger? 

The only thing you could do than can improve the assembly is add the chloroplast genome sequence you assembled to the config file (is option for)

**Comment by SaiReddy-A** [comment]
I've tried by adding chloroplast as well but it didn't improve anything. I've also tried changing the genome range but no success.

**Comment by ndierckx** [comment]
Short reads have their limits, good chance long reads won't work either...

**Comment by SaiReddy-A** [comment]
Thank you!!
