### ISSUE TITLE
seed input

### ISSUE THREAD

**Issue by wbglizhizhong** [ndierckx/NOVOPlasty#16]
hi,
I was confused that I select a gene from A's cp genome as seed,but alway said 

NVALID SEED, PLEASE TRY AGAIN WITH A NEW ONE

why? In fact, I have the complete cp genome of A, I just want to try,so please tell me,thank so much

**Comment by ndierckx** [comment]
Hi,

What kind of data do you have? (WGS, capture, pared end?) And do you have sufficient coverage?

**Comment by wbglizhizhong** [comment]
WGS, 10G,I think the coverage was enough. and today I try other species and use universal primers check the complete co genome, so many error
![image](https://cloud.githubusercontent.com/assets/26796424/24575168/1c271c20-16d1-11e7-974d-9dd191160387.png)
![image](https://cloud.githubusercontent.com/assets/26796424/24575170/28d91cca-16d1-11e7-9329-01a578e826bc.png)
So,I think you could check more species and confirm it is useful

**Comment by ndierckx** [comment]
You mean that NOVOPlasty assembled with that many errors? I doubt that because I assembled over 60 species and accuracy was always 100% (except a few bp around SNR's, but that's not the case here)
I am on holiday in Myanmar, so can't check every day, but send me the config file , because I think you are doing something wrong, or you assembled something else (mitochondrial genome has lots of duplicate regions of the chloroplast)

**Comment by wbglizhizhong** [comment]
thank you for your reply and have  a good time, today I used new one, that was okay. however, I suggest that some aquatic plants you should be checked,  because their genome always be complicated. 
enjoy your holiday, if you have the chance, welcome to China.
best,
Zhizhong

**Comment by ndierckx** [comment]
I haven't tried many aquatic plants (only grasses). So it could be unusual structures are difficult to assemble and won't circularize, but those errors could only be caused very long repetitive regions (only time I observed a reduced accuracy was in a long repetitive region of a mitochondrial genome with too low coverage) But if you want you can send me your data and I can try one example myself, or if there is some public data available of one of those species... 
I have been a few times to China and will return next year I think!

**Comment by finchnSNPs** [comment]
Hello,

I'm getting the same error. INVALID SEED, PLEASE TRY AGAIN WITH A NEW ONE

My input data are fastq.gz. They HAVE been trimmed (not recommended I know...but why?). Do you think that would result in this error? I tried this with four different seed fastas. Two are from an older assembly made with the same reads and two are rbcl sequences from genbank. They all look like standard fastas to me >first line and 70 character line wrapping. 

I can provide more information if needed. 

Thanks,

**Comment by ndierckx** [comment]
Hi,
I don't think the seed file is the problem, probably some incompatibility problems with your data files.
What is the size of your dataset and can you send me a log file?
And are you using the latest version, with latest config file?

**Comment by ndierckx** [comment]
Oww and trimming is no good because they just trim away low quality regions, while it is still possible to use that data because NP can recognize them. So it will create gaps in data which is problematic for a continuous assembler like NP

**Comment by finchnSNPs** [comment]
Okay I will try it without trimmed seqs and see if that works.

**Comment by ndierckx** [comment]
No, that has nothing to do with that problem, it just for a better performance, but won't influence the results that drastically

**Comment by sivajean** [comment]
Hi.. 

What is that mean by seed.fasta , in my case i just gave some reference cp genome in seed input. is that any other database that available for this?

**Comment by ndierckx** [comment]
Hi, 
it's the sequence to start the assembly, best not to take a complete cp genome, it can initiate mito assembly. Check the manual or the manuscript..
I added an example seed on github, you can try that one, it's a zea mays one, but should work for most species
