### ISSUE TITLE
Question about specific name for config files

### ISSUE THREAD

**Issue by occasional-it-guy** [ndierckx/NOVOPlasty#161]
Does the config filename have to be config.txt? I have my config files written up as config (name of sample).txt and I tried running the following command

`perl NOVOPlasty/NOVOPlasty4.1.pl -c Sequenced_Aphyllon_Data/NOVOPlastyData/config A_validum_validum_Mistreeta.txt`

and received

`-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 4.1
Author: Nicolas Dierckxsens, (c) 2015-2020
-----------------------------------------------

Error:Can't open the configuration file, please check the manual!

Usage: perl NOVOPlasty4.1.pl -c config.txt`

Any help would be much appreciated!

**Comment by ndierckx** [comment]
No it doesn't have to be config.txt, it can be any file name.
But I think it is not a good idea to have a space in your filename, it won't be recognised, best to never use that for any command intthe terminal. Can replace it with _
