### ISSUE TITLE
Config file mismatch?

### ISSUE THREAD

**Issue by ulaszewski** [ndierckx/NOVOPlasty#164]
@ndierckx  config.txt in version 4.3 does not match the config example in README. Is it ok?

EDIT:
After running the NOVOPlasty4.3.pl does not recognize arguments used in the config file template shown in README.

**Comment by ndierckx** [comment]
Hi,

Thanks for reporting, seems I forgot a previous update, changed it now.

The correct one was the the separate config file.

Greets
