### ISSUE TITLE
Enquiry for data path set in config.txt

### ISSUE THREAD

**Issue by zx0223winner** [ndierckx/NOVOPlasty#17]
Hi NOVOPlasty supporting team,

I have paired end Illumina Raw reads in three samples:  Sample_Algae1A,  Sample_Algae2A, Sample_Algae3A.  

In each sample file, I have the forward and reverse reads: Algae1A_R1.fastq,  Algae1A_R2.fastq ;  Algae2A_R1.fastq,  Algae2A_R2.fastq;  Algae3A_R1.fastq,  Algae3A_R2.fastq.

How to set the Forward and reverse reads path in the config.txt file? Like this? 
Forward reads        = *R1.fastq   
Reverse reads        = *R2.fastq

Or Run each sample separately?
Forward reads        = Algae1A_R1.fastq.
Reverse reads        = Algae1A_R2.fastq

Forward reads        = Algae2A_R1.fastq.
Reverse reads        = Algae2A_R2.fastq

Forward reads        = Algae3A_R1.fastq.
Reverse reads        = Algae3A_R2.fastq

Will thank for debugging!

**Comment by ndierckx** [comment]
Hi,

Are the read lengths and insert sizes of your three datasets the same?
If so, just merged them together (with cat on command line)
If the insert size or read lengths are different, you have to pick one.
But I will add a multiple library option in the near future

Greets

**Comment by zx0223winner** [comment]
Thanks for your reply. Yes,  the three libraries which are intend to acquire more coverage have same read lengths and insert sizes. So I could simply merge the files by using: 

Forward reads = *R1.fastq
Reverse reads = *R2.fastq

Did I understand you correctly?

**Comment by ndierckx** [comment]
No, NOVOPlasty can't do that, you have to physically merge them before you run the assembly
Do it in the command line like this:

cat file_1_R1.fastq file_2_R1.fastq >> file_merged_R1.fastq
cat file_1_R2.fastq file_2_R2.fastq >> file_merged_R2.fastq

**Comment by zx0223winner** [comment]
Thanks, problems have been solved. I will let you know if I need more information from my side.
