### ISSUE TITLE
Results and input are the same size

### ISSUE THREAD

**Issue by bioramg** [ndierckx/NOVOPlasty#171]
Hello sir,
I'm trying to assemble the plant chloroplast genome. So, I used the rbcL gene from the same cp genome as a seed for the assembly.  But, the results are just my input seed sequence data only. I have used matK seed sequence and 65kb contig as the seed sequences. But getting the same results. What could be the problem? How to solve it?

I've attached the extended log file.
[log_extended_cpl.txt](https://github.com/ndierckx/NOVOPlasty/files/6325176/log_extended_cpl.txt)

Looking forward to hearing from you
I really appreciate any help you can provide.
Best,

**Comment by ndierckx** [comment]
Hi,

I saw you didn't fill in crucial information in the config file

You left genome range, read length and insert size blank

Greets,

Nicolas

________________________________
From: bioramg ***@***.***>
Sent: 16 April 2021 14:57
To: ndierckx/NOVOPlasty ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ndierckx/NOVOPlasty] Results and input are the same size (#171)


Hello sir,
I'm trying to assemble the plant chloroplast genome. So, I used the rbcL gene from the same cp genome as a seed for the assembly. But, the results are just my input seed sequence data only. I have used matK seed sequence and 65kb contig as the seed sequences. But getting the same results. What could be the problem? How to solve it?

I've attached the extended log file.
log_extended_cpl.txt<https://github.com/ndierckx/NOVOPlasty/files/6325176/log_extended_cpl.txt>

Looking forward to hearing from you
Thank you in advance
Best,

**Comment by bioramg** [comment]
Dear Nicolas,
Thank you for the suggestion.
It's working perfectly now.
