### ISSUE TITLE
Genome Range for chloro

### ISSUE THREAD

**Issue by anupullanhi** [ndierckx/NOVOPlasty#173]
Hello, what is the genome range to be given for chloroplast in NOVOPlasty. I am running this pipeline for the first time. There is a difference in base pairs when changing the genome range. The data I am using is of bellflower.
Any help regarding this query is appreciated. 
Thank you

**Comment by ndierckx** [comment]
Hi,

Depends on the size of your accepted genome. For chloroplast genomes I used to take 120000-200000

**Comment by ndierckx** [comment]
It will try to circularize the assembly within this range by looking for overlaps on both ends of the assembly
