### ISSUE TITLE
Output path does not work

### ISSUE THREAD

**Issue by aburzynski** [ndierckx/NOVOPlasty#178]
The new option introduced in v4.3.1 in config, named "Output path" takes a path as an argument. However, in my case the text entered here is just prepended to the output filenames which are still stored in the same directory.

**Comment by ndierckx** [comment]
Hi,
Thanks for letting me know. I only tested it on Linux, are you using Windows or Mac? If that is the problem I will try to fix it.

**Comment by aburzynski** [comment]
I am also using your (amazing) Novoplasty on linux so this must be something else. I will try to experiment with various strings and let you know if there are some specific conditions for this to reproduce.

**Comment by ndierckx** [comment]
Can you send the config file you used?

**Comment by aburzynski** [comment]
I investigated some more and this actually kind-of-work. However, there are two non-obvious conditions. One is that the output directory must exist. The second that the "/" slash has to be present at the end of the path in config file.
So this config works when the subdirectory "version_with_31mers" is present:

Project:
-----------------------
Project name          = my_project
Type                  = mito
Genome Range          = 20000-60000
K-mer                 = 31
Max memory            = 115
Extended log          = 0
Save assembled reads  = no
Seed Input            = bait.fasta
Extend seed directly  =
Reference sequence    =
Variance detection    =
Chloroplast sequence  =

Dataset 1:
-----------------------
Read Length           = 150
Insert size           = 350
Platform              = illumina
Single/Paired         = PE
Combined reads        =
Forward reads         = left.fq.gz
Reverse reads         = right.fq.gz
Store Hash            =

Heteroplasmy:
-----------------------
MAF                   =
HP exclude list       =
PCR-free              =

Optional:
-----------------------
Insert size auto      = yes
Use Quality Scores    = yes
Output path           = version_with_31mers/


Without the slash the path is just prepended to the output files created in the current directory, without the subdirectory (but with the slash) the program will not run, complaining about inability to write to a log file.

**Comment by ndierckx** [comment]
Ok thanks for letting me know, I will fix it with the next update!
