### ISSUE TITLE
running software but displayed "permission denied"

### ISSUE THREAD

**Issue by 20182531027** [ndierckx/NOVOPlasty#186]
Hi, I downloaded the software to assemble circular genome, why did this displayed "permission denied", but i actually installed perl, and add it to my environment variables "bash.rc";
 i  am sorry that my basic skill of perl are not solid. can you be kind enough to tell what's wrong with that?
![image](https://user-images.githubusercontent.com/92516659/157365289-d33d435e-02df-4404-887f-294e0fd7db50.png)

![image](https://user-images.githubusercontent.com/92516659/157365352-a6cf8539-d73b-4d12-8ee7-c8d9633dd918.png)

**Comment by ndierckx** [comment]
Hi,

Sorry for the late reply.
I never saw this error before... It must be a problem with your permissions for the installed software?
Did you add the 5, because it doesn't need to be perl5, just perl should be fine
