### ISSUE TITLE
What's the meaning of KWWM and SCTWW in the assembled sequences?

### ISSUE THREAD

**Issue by CS-CH** [ndierckx/NOVOPlasty#188]
Hi, I find there are some special signs such as KWWM and SCTWW in the assembled sequences, and the mapping coverage at these sites seems extremely low. I am wondering if the linkage relationship of these regions could be accepted. Thank you!

**Comment by ndierckx** [comment]
HI,
These are IUPAC codes, so positions that couldn't be called accurately This could be variation but in your case it are probably homopolymers (illumina has low quality in these regions)
http://www.bioinformatics.org/sms2/iupac.html

What you mean by "linkage relationship of these regions could be accepted."?
