### ISSUE TITLE
Several contigs with same sequence

### ISSUE THREAD

**Issue by OctavioSerra** [ndierckx/NOVOPlasty#19]
Hi Nicolas,

First of all I would like to thank you for this great tool! 

I've been working with NOVOPlasty for several days now, testing different parameters and getting used with it. I have observed with my data that without a reference genome, NOVOPlasty gets stuck at repetitive regions and generates large extended log files (an issue that was raised before). However when using a reference genome from a related species, the problem was solved for me.

I was not able to get my final chloroplast assembly in one single contig. In fact NOVOPlasty generated 10 contigs, but only 2 of them were unique (lets say contig1 and contig2 for simplicity). For the remaining contigs, I observed that contig3 = contig5 = contig7 = contig9. The same for contig4 (= contig6=contig8=contig10). I'm not sure if it is related or not, but the "merged contigs" had no sequences and the "Option" files were not generated.

It did not represent a problem for the final assembly, since I just excluded the duplicated contigs after confirming they were 100% equal, and I was able to manually join the remaining ones accurately. 

Nevertheless, I think you can look into your code and probably fix it easily.

Keep the good work!

**Comment by ndierckx** [comment]
Hi,

Thanks for reporting the problem!
Could you send me the extended log so I can find the exact problem?

Greets

**Comment by OctavioSerra** [comment]
Sure, here it is.

Hope it helps!

[log_extended.txt](https://github.com/ndierckx/NOVOPlasty/files/1251851/log_extended.txt)

**Comment by ndierckx** [comment]
Hi,

I think I found the problem, if you have time could you run it again with latest version?
And the reason why it doesn't circularize is because of a high AT-rich region with low coverage and very low sequence quality. Are the reads trimmed, if so I would advice not to, because it sometimes completely deletes regions like that

**Comment by OctavioSerra** [comment]
Hi Nicolas,

I tried it this morning once, it seems to work great now. I send you the new extended log file just in case you want to check anything. In theory my data is just filtered for adaptor removal, but I will check everything again just to be sure. 

I will try this new version for mitochondria assembly soon too, because I think I had a similar behaviour for mitochondria in previous attempts.

Thanks a lot for the quick answers and keep the good work :) 


[log_extended_NOVOPlasty2.6.3.txt](https://github.com/ndierckx/NOVOPlasty/files/1260013/log_extended_NOVOPlasty2.6.3.txt)

**Comment by ndierckx** [comment]
Looks like it circularized now
I found a bug in one my latest adjustments that can lead to an infinitive loop
It is fixed now, so better download it again

**Comment by OctavioSerra** [comment]
Yes, it performs quite nice now.

Thanks once again!
