### ISSUE TITLE
NOVOplasty error assembly

### ISSUE THREAD

**Issue by labrechai** [ndierckx/NOVOPlasty#194]
(ee) nbfgr@nbfgr-Precision-3650-Tower:~/Software$ NOVOPlasty4.3.1.pl -c config.txt 

-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 4.3.1
Author: Nicolas Dierckxsens, (c) 2015-2020
-----------------------------------------------

Input parameters from the configuration file:   *** Verify if everything is correct ***

Project:
-----------------------
Project name          = CM_assembly
Type                  = mito
Genome range          = 12000-22000
K-mer                 = 21
Max memory            = 100
Extended log          = 1
Save assembled reads  = yes
Seed Input            = /home/nbfgr/Software/seed.fasta
Extend seed directly  = 
Reference sequence    = 
Variance detection    = 
Chloroplast sequence  = 

Dataset 1:
-----------------------
Read Length           = 150
Insert size           = 300
Platform              = illumina
Single/Paired         = PE
Combined reads        = 
Forward reads         = /home/nbfgr/Software/CM-1030-Blood-300bp_R1.fastq
Reverse reads         = /home/nbfgr/Software/CM-1030-Blood-300bp_R2.fastq
Store Hash            = yes

Heteroplasmy:
-----------------------
Heteroplasmy          = 
HP exclude list       = 
PCR-free              = 

Optional:
-----------------------
Insert size auto      = yes
Use Quality Scores    = 
Output path           = /home/nbfgr/Software/Mito_assembly/

Reading Input......OK

Building Hash Table...

bu i am not getting assembly or the logs after 2-3 hrs the terminal atomically closed and all file are of 0 bytes including logs please help 

![Screenshot from 2022-08-11 13-59-12](https://user-images.githubusercontent.com/111047346/184094334-e7a78804-f71a-4375-b814-513047570891.png)

**Comment by ndierckx** [comment]
Hi, The problem is resolved?

**Comment by labrechai** [comment]
Yes thanks for your concerns
