### ISSUE TITLE
Incorrect Input data metrics in log files in the batch mode

### ISSUE THREAD

**Issue by DenisGoryunov** [ndierckx/NOVOPlasty#208]
Hello Nicolas,

I ran 57 samples as one batch  with NOVOPlasty Version 4.3.1 and found very strange **Input data metrics** in log files for the majority of the samples. E.g. for the sample №55 i got:

**-----------------------------------------Input data metrics-----------------------------------------

Total reads                : 4456742
Aligned reads           : 6700394
Assembled reads      : 5452210
Organelle genome % : 150.34 %
Average organelle coverage : 7471**

Then i reran NOVOplasty, but left only one sample №55 in the batch file. Now **Input data metrics** of the sample looks much more realistic:

**-----------------------------------------Input data metrics-----------------------------------------

Total reads                : 4456742
Aligned reads            : 365934
Assembled reads       : 294278
Organelle genome %  : 8.21 %
Average organelle coverage : 408**

How can i get the correct **Input data metrics** for the large batch with 57 samples, as i need this statistics for the paper preparation?

Many thanks,
Denis

**Comment by ndierckx** [comment]
Hi, I think I never adapted the metrics for the batch function, so I guess I need to change it in the code in a way it outputs it per sample. But you will need to rerun it if you need those statistics, is it urgent?

**Comment by DenisGoryunov** [comment]
Hi Nicolas,
Thanks for your response!
There are two weeks or so before i will have to rerun the assemblies to be
in time.

Regards,
Denis

чт, 8 июн. 2023 г. в 08:21, Nicolas Dierckxsens ***@***.***>:

**Comment by ndierckx** [comment]
Hi, Will have a look if it is an easy fix..

**Comment by DenisGoryunov** [comment]
Hi Nicolas,

Thank you so much!

пт, 9 июн. 2023 г. в 05:19, Nicolas Dierckxsens ***@***.***>:

**Comment by DenisGoryunov** [comment]
Hello Nicolas,

I'm wondering if there are any updates regarding the issue?

Regards,
Denis

**Comment by ndierckx** [comment]
Hi Denis,

Sorry I completely forgot about it. I think I fixed it today, will do some testruns tomorrow and then send you the new version.

Greets,

Nicolas

**Comment by DenisGoryunov** [comment]
Hello Nicolas,

Thank you very much for your reply and the good news!

Regards,
Denis

**Comment by ndierckx** [comment]
I uploaded a new version (4.3.3), can you check if it works now ( it does for me)
Also download the config file again, because it is also updated..

You can now add output paths to the batch script now, it will make the folder and output the results in there....

**Comment by DenisGoryunov** [comment]
Hello Nicolas,
Thanks a lot! I greatly appreciate your help and efforts! The file system of our HPC cluster is scanning for errors now. When it is finished, i will try to run the new Novoplasty version in batch mode to check the assemblies statistics.
Thank you again!

Regards,
Denis

**Comment by DenisGoryunov** [comment]
Hello Nicolas,
I've tested the NOVOPlasty Version 4.3.3 on the same batch consisting of 57 samples.
Unfortunately, the "Organelle genome %" and "Average organelle coverage" metrics still permanently increase for each subsequent sample in the batch. It seems that the same is true for the "Aligned reads" and "Assembled reads" metrics.
Could you help me please?
If you leave me your email, i may send you privately the one large log file for all samples.
Regards,
Denis

**Comment by ndierckx** [comment]
Hi,

Ah sorry, I tested it once and it worked, so will have to take a look why it doesn't work for you...
You can find my mail on the home page of this repository..
You can send me the file..

greets,
Nicolas

**Comment by ndierckx** [comment]
Maybe send me the config file and batch file that you are using...

**Comment by ndierckx** [comment]
Think it is fixed now, could you try again with 4.3.4?

**Comment by DenisGoryunov** [comment]
Hello Nicolas,
Thanks a lot! Do you need my log, config and batch file or should i try Novoplasty version 4.3.4 first?
Regards,
Denis

**Comment by ndierckx** [comment]
Maybe try 4.3.4 already, I think it should work now

**Comment by DenisGoryunov** [comment]
Hello Nicolas,

NOVOPlasty Version 4.3.4 gives correct metrics on my batches.

Many thanks,
Denis
