### ISSUE TITLE
Query about "Input data metrics" section in log file

### ISSUE THREAD

**Issue by daniellesloan** [ndierckx/NOVOPlasty#210]
Hi, I was hoping you could provide clarity on "Input data metrics" section within the log file. I have ran NOVOPlasty twice using the same seed and read data but changed the k-mer size. As you can see from the attached images, the "Input data metrics" section for the k-mer 33 assembly lists 3 values whilst the section for the k-mer 55 assembly lists 5 values, including "Organelle genome %" and "Average organelle coverage". What do these two values mean, and does this mean that there is no mitogenome organelle assembled by the k-mer 33 run? 
![k-mer33_log_screenshot](https://github.com/ndierckx/NOVOPlasty/assets/78738760/4c20da95-ff51-47b4-89c3-f4cd65a2e819)
![k-mer53_log_screenshot](https://github.com/ndierckx/NOVOPlasty/assets/78738760/6f675c30-9891-4ddb-ad1c-4218f4996b68)

**Comment by ndierckx** [comment]
it only gives these two metrics when it was able to circularize the assembly. The 33 is maybe missing a small part, so it didn't circularize.. the % is an estimation of the fraction of mitoreads in the dataset, and the other one is the sequencing depth.. Seems very high in your case
