### ISSUE TITLE
Read Length 151 versus 150

### ISSUE THREAD

**Issue by Phismil** [ndierckx/NOVOPlasty#211]
Dear Nick,
Thank you for maintaining and updating the repository.
When one sets the read length to 150  for sequences that are actually 151 bp, does NOVOplasty automatically remove this last base at position 151 and trim it to 150? In my case, I see that setting the read length to 150 or 151 results in identical assembly.
Thank you in advance

**Comment by ndierckx** [comment]
Hi,
No it will nver trim reads, because it can also handle different lengths.
Few bps won't make any difference, but for optimal use it is better to not be too far off

Greets

**Comment by Phismil** [comment]
Thanks.
