### ISSUE TITLE
Using Nanophore reads for Mitochondrial Genome assembly

### ISSUE THREAD

**Issue by Millawati** [ndierckx/NOVOPlasty#215]
Hi, can we use Nanophore reads for the Mitochondrial genome assembly using Novoplasty? Or it still only for Illumina data?

**Comment by ndierckx** [comment]
Only for Illumina data, do you want to combine short and long or only long?
Will soon have a targeted long read assembler available: https://github.com/ndierckx/NOVOLoci

**Comment by Millawati** [comment]
Hi,

Thank you for your respond. We want combine both short and long. Is there
any assembler you can you suggest?

**Comment by Millawati** [comment]
Alright. Thank you for your help. Really appreciate it.
