### ISSUE TITLE
no output &  a  long smallest contig

### ISSUE THREAD

**Issue by wenjiexiaomeng** [ndierckx/NOVOPlasty#22]
Hi,
Thanks for u smart assembler, it is amazing!!!
I tried to  assmble two mito sequences and one chloroplast genome, it played well !!
But this time there was some problems ,  I don't know what caused it, could you give me some suggestions ？
And I also used the bwa to map the data to reference chloroplast genome, there is 0.92%  propair mapped reads, and it may  be 4500X about the chloroplast genome , so I downsize the data to about 400x coverage of the chloroplast genome, but it still had this problem.
The log text is added below.
 #############################################################################
-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.3
Author: Nicolas Dierckxsens, (c) 2015-2017
-----------------------------------------------

Input parameters from the configuration file:   *** Verify if everything is correct ***

Project name         = WC036A_chloro
Insert size          = 170
Insert size auto     = yes
Read Length          = 50
Type                 = chloro
Genome range         = 120000-200000
K-mer                = 39
Insert range         = 1.6
Insert range strict  = 1.2
Paired/Single        = PE
Max memory           = 30
Extended log         = 1
Save assembled reads = yes
Combined reads       =
Forward reads        = read_1.fq
Reverse reads        = read_2.fq
Seed Input           =  yinxing_read.fa
Reference sequence   = yinxing_chloroplast.fasta
Chloroplast sequence =

Subsampled fraction: 94.46 %

Initial read retrieved successfully: AAGAACATCTTCAAAGAGCAATTCATTCAGTTGAATGATGTGAACAATGA

Start Assembly...

------------Assembly 1 finished: Contigs are automatically merged in Merged_contigs file------------
Total contigs              : 0
Largest contig             : 0 bp
Smallest contig            : 1000000000000000000000000000000000 bp
Average insert size        : 170 bp

-----------------------------------------Input data metrics-----------------------------------------

Total reads                : 55960628
Aligned reads              : 0
Assembled reads            : 0
----------------------------------------------------------------------------------------------------
############################################################################################################################################################

**Comment by ndierckx** [comment]
Hi,

It is because your read length is only 50 and kmer 39.
As mentioned in the explanation of the different parameters, when your read length is below 90,
you have to decrease your kmer to 23.
But since you have only 50, which I never tried before, I would use a kmer of 18
and then adjust something in the code:
Change
my $left = '9';
my $right = '15';
to
my $left = '4';
my $right = '9';
They are line 13 and 14 of the code so easy to change

**Comment by wenjiexiaomeng** [comment]
Thanks for your  advice, I will try this and give the result here.

**Comment by wenjiexiaomeng** [comment]
Hi,
I tried with the 23 mer , it played well.
And I also change the scripts, then I used the 18 mer you suggested, but it didn't play well...
btw, I got some gap in my genome...
Thanks for u smart  tools again.
Best,
