### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by lightworms** [ndierckx/NOVOPlasty#221]
Hello I'm receiving the following error:

THE INPUT READS HAVE AN INCORRECT FILE FORMAT!
PLEASE SEND ME THE ID STRUCTURE!

version: 4.3.3

**Forward:**

@ERR104974.12 HWI-ST427_0113:1:1101:1265:2704#GNNGNGNG/1
AGGGGATCATGGCAACATACAATCTAATTATCACCGATGTTACGCAGTACGGCAACTCATACTACGGCATCCGATATTGCGTAGCTGGATGGGACATCGAT
+
HHHHHHHHHHHHHFFFHHHHFHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHFHHHHHHHHHFHFGHHHBFGGGGHBEEHBFF;FCDD>.00;=7E
@ERR104974.13 HWI-ST427_0113:1:1101:1471:2707#GNNGNGNG/1
CTTTTTGCTGGTCCATCACAAAGAGCCCCGTTCCGCATATCACAAAGACAGATCGGAAGAGCGGTTCAGCAGGAATGCCGCGATCTCGTATGCCGTCTTCT
+
HHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHEHHHHHFHHHHHHHGFHHFHHHHFHHEHFHHHFHHHGGHGG>5.ABC?;FGDGGFHHFH6

**Reverse:**

@ERR104974.11 HWI-ST427_0113:1:1101:1453:2688#GNNTNANG/2
TACTGGCGATCCTAATTATAAGATACAATTTCTAATTCCAACGGTACCTATCTTATATTTAGTATCGCCAGTAAGATCGGAAGAGCGTCGTGTAGGGAAAG
+
HHHHHHEH;@FGHGBBCBDDGGFEGHHHGHBHHGFHHFCHFGFFBHHFHFGGHGHHHEFHFGHHFHHGGFHHHHHGFEFFA=DADCEAEE?A=<DEE>BDB
@ERR104974.12 HWI-ST427_0113:1:1101:1265:2704#GNNGNGNG/2
TTCCCTGGACCGACGTATTTCGAATCCCAGAAACGAGAAAGCTCAACTGCGGCGTTTGCCTCAAGCGGCTCCGGACGGATCATCCGTTTTCGATCGATGTC
+
HHHHHHHHHHHHFHHHHHHHHHHHHHHHEHFFHHHHHHFHHCFHEHHHHFHHHHFHHHHHHHFHHHFBFHFHFHBDFF,CEEEEEF@EFE:<CDCCCAE<<

All the best

**Comment by ndierckx** [comment]
Hi, these read ids should not be a problem, can you send me your log file? Are you sure you didn't switch the forward and reverse path?

**Comment by lightworms** [comment]
Thank you for getting back to me; here's the log file.
[log_ERR104974_Floridensis_Test.txt](https://github.com/ndierckx/NOVOPlasty/files/14163304/log_ERR104974_Floridensis_Test.txt)

**Comment by lightworms** [comment]
Whoops, the problem was that I was using a compressed version and an uncompressed for my forward and backward reads.
Resolved!
