### ISSUE TITLE
New regex error

### ISSUE THREAD

**Issue by edgardomortiz** [ndierckx/NOVOPlasty#23]
Hi Nicolas,

This happened now, please let me know if you need the extended log:
```
-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.3
Author: Nicolas Dierckxsens, (c) 2015-2017
-----------------------------------------------


gzip: stdout: Broken pipe

Reading Input......OK

Input parameters from the configuration file:   *** Verify if everything is correct ***

Project name         = Aaegi_A102_S13_k23
Insert size          = 300
Insert size auto     = yes
Read Length          = 151
Type                 = chloro
Genome range         = 120000-200000
K-mer                = 23
Insert range         = 1.6
Insert range strict  = 1.2
Paired/Single        = PE
Max memory           =
Extended log         = 1
Save assembled reads = yes
Combined reads       = ../../Aaegi_A102_S13_PE_clPE.r150.fq.gz
Forward reads        =
Reverse reads        =
Seed Input           = ../Adesmia_rbcL.fasta
Reference sequence   =
Chloroplast sequence =


Building Hash Table......OK

Subsampled fraction: 100.00 %

Retrieve Seed......OK

Initial read retrieved successfully: AAAGCAAGTGTTGGGTTCAAAGCTGGTGTTAAAGATTATAAATTGACTTATTATACTCCTCAATATGAAACGAAAGATACTGATATCTTGGCAGCATTCCGAGTAACTCCTCAACCTGGAGTTCCTCCTGAAGAAGCGGGTGCCGCGGT

Start Assembly...

219618 bp assembledNested quantifiers in regex; marked by <-- HERE in m/.** <-- HERE T*AGAATTCTTCTTTTCTTTTTTTTTTTT/ at /home1/02728/emo347/bin/NOVOPlasty/NOVOPlasty2.6.3.pl line 16886, <INPUT3> line 22.
```

**Comment by ndierckx** [comment]
Hi,

Thanks for reporting, but the line number doesn't match.
Could you send the NOVOPlasty file you used, maybe  fixed on github already

I didn't had the time to check your references yet, I tried with Vaccinium before, are the one you send me closer?

**Comment by edgardomortiz** [comment]
I used Novoplasty 2.6.3 (is this what you are asking?), and yes, Vaccinium is the closest reference there is. I will clone again just in case.

**Comment by ndierckx** [comment]
Yeah but could you send the 2.6.3 file, I think I changed something without changing the version number.
Then I tried with the closest reference, looks like a complicated genome and I don't have time this week to put more time in it. I will first fix the error you send me, takes 1 min if I know the correct line

**Comment by edgardomortiz** [comment]
Sorry, our cluster was down for maitenance, this the exact NOVOplasty I used.

[NOVOPlasty2.6.3.pl.txt](https://github.com/ndierckx/NOVOPlasty/files/1318995/NOVOPlasty2.6.3.pl.txt)

**Comment by ndierckx** [comment]
Thanks, the problem should be fixed now
