### ISSUE TITLE
novoplasty output more shorter contigs than input contigs

### ISSUE THREAD

**Issue by orangeSi** [ndierckx/NOVOPlasty#24]
Hi Nicolas,
     I have a mostly 1M scaffold and it has a gap about 30k bp,then i split the scaffold at the gap to be two contigs . so i run novoplasty with the two contigs and illuniate short reads,but output 220  contigs (about 2M),like this:
$ cat Contigs_1_AOB_chloro.fasta |grep \>|head
>Contig01+10857171
>Contig02+c977_c197_c186_1782
>Contig03+2782
>Contig04+11128
>Contig05+c1172_c465_c459_21128
>Contig06+2938
>Contig07+c9537_c7419_c6354_c6213_c5458_c5198_c4405_c2753_c2247_22805
>Contig08+c9605_c7487_c6422_c6281_c5526_c5266_c4473_c2821_c2315_2217
>Contig09+210643
>Contig10+13822

All four output files is:
Contigs_1_AOB_chloro.fasta
log_AOB_chloro.txt
contigs_tmp_AOB_chloro.txt
Merged_contigs_AOB_chloro.txt

thanks~
Si

**Comment by ndierckx** [comment]
Hi,

What are you trying to assemble and what kind of data do you have?

**Comment by orangeSi** [comment]
sorry, I just notice the message~
the 1M scaffold is a chromosome of yeast, I use pacbio to assembly and scaffold withe pb reads to get the 1M scaffold,it only has one gap. I use Illuminate 500bp library PE150 reads to run the novoplasty.

**Comment by ndierckx** [comment]
Can you send the config file? It's the standard use of NOVOPlasty, so probably have to chance some things.

**Comment by ndierckx** [comment]
And the input contig is only used to find one read to start the assembly, so it's normal that it so shorter in your case
