### ISSUE TITLE
INVALID SEED, PLEASE TRY AGAIN WITH A NEW ONE

### ISSUE THREAD

**Issue by jazz7787** [ndierckx/NOVOPlasty#25]
Hey, 

we have a lot of PE reads and want to assemble the cpdna from them using a seed from the **same species**. We get the above mentioned error with different seeds (ndhf, atpb). What can be the cause of the error?

Thank you very much !
Radu

**Comment by jazz7787** [comment]
-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.3
Author: Nicolas Dierckxsens, (c) 2015-2017
-----------------------------------------------


Input parameters from the configuration file:   *** Verify if everything is correct ***

Project name         = ATPB_chloro
Insert size          = 500
Insert size auto     = yes
Read Length          = 300
Type                 = chloro
Genome range         = 120000-200000
K-mer                = 39
Insert range         = 1.6
Insert range strict  = 1.2
Paired/Single        = PE
Max memory           = 
Extended log         = 0
Save assembled reads = no
Combined reads       = /home/manuel/Desktop/novoplasty_atpb/Sem-20_S4_L001.assembled.fastq.gz
Forward reads        = 
Reverse reads        = 
Seed Input           = semele_atpb.fasta
Reference sequence   = 
Chloroplast sequence = 

Subsampled fraction: 100.00 %


INVALID SEED, PLEASE TRY AGAIN WITH A NEW ONE

^ the log

**Comment by ndierckx** [comment]
Hi,

Could you send me the structure of your read ids?
And do you also have a separate file for forward and reverse reads?

**Comment by jazz7787** [comment]
Hi, we used pe reads and we get another error during seed retrieval, 
[log_MATK_chloro.txt](https://github.com/ndierckx/NOVOPlasty/files/1333293/log_MATK_chloro.txt)
that the coverage is too low.

I am asking myself why that is the case, since we know the data to be of relatively good quality, and definitely not below 10x. Is there a way around this?

**Comment by ndierckx** [comment]
You know how much the coverage is?
And did you trim the reads?
Maybe try with kmer 23, otherwise I could lower the threshold, but if the coverage is that low, I don't know if you will get a good assembly

**Comment by jazz7787** [comment]
Sorry, we tried with the trimmed reads, thus with a small amount of data. We tried it now and its actually working great ! Thanks for replying !
