### ISSUE TITLE
Read name error

### ISSUE THREAD

**Issue by melop** [ndierckx/NOVOPlasty#26]
Hello,

I'm trying Novoplasty on some fish MT genomes. So far it's working great! Except for this one species where I have a read file exported from genbank. I named the sequences with numbers, 1, 2, 3 etc.

Obviously the script is trying to parse the Illumina read names, so it throws the following error:

```
THE INPUT READS HAVE AN INCORRECT FILE FORMAT!
PLEASE SEND ME THE ID STRUCTURE!

```
Is there any reason why the program tries to enforce an Illumina ID format in the read files?

Best Regards,
Ray

**Comment by ndierckx** [comment]
Hi,

Most type of read id's are supported, but if you send me a few lines from the forward and reverse id's, I will add them to the list..

**Comment by melop** [comment]
Hello,

       yeah it's just an integer:

@1
AGCTATGTGCCCATCTTCTCCGCACTTAAAACAGTATCCAGGCTTTGGTCTGGGCACCACTGCTGTTATCTGCTGAATCTGTTTGGGCTCATCTGGAAT
+
4=DFFFFHHHHHJJJJJJJJJJJHIIJIJGIIJJIIIIJIIIJJIJJJHJJJJIIJJJJJJJJJHHFHHHHFFFFFFEEEEEDEDBDDDDDDDDDDCCC
@2
TTTTTGGCAGAAATTATCCTGAATCTGAGGTAAAAGAAAAAGAAATCCTGTTATTCTCCTTCTTTGTTTAATTGTCTCGAGATTTAAATGTGTTAGCAT
+
4=DDFFFHHHHHJIJIJJIIJIHHIJJGIJHHHJJJJJJJJJJJJJJIJJJJIJIJIIGHJJJJJJIJJGEHHHHHHFFDFDDEEDDCDEEEFDD:ACD
@3
CCGTGAATTAAACTTCAAGGTTCAGGTGGTCCAGACAGCTTCAAATCAATTTAGAGCCTCTTTCTTGTTTGGTGTCTAAGGCTTTCTCGTGACACTTGA
+
1:BBDDBDDDDAEEEC:ACAFFF<CFFCFEEEEEEDCDDDDB<?DBBDDDDEIDEEBCECCCD7ACCCEIAC=ADDD@;?A@AAAA@;;?=;=>>AAA:
@4
TTATAAGCCAACAATTGTGTAATTGGACTTCTTCTTTAAATTGACACCAGATCCGGTGACATTTTGGGACATGGTTTGACCCCCTTAGGAAAGTGCTAT
+
1=BDDDEHHHHHJIIJJHIHHHHIJJGHIJFHIHIJJHIDHHHFGHIJFHHIIJIJJIIIGHIJJJJIHHHHFFFFFDEDEEDDDDDDD>CADDDDEDD
@5
TTTTTAGATGAGTACATTAGCTGGTTAAGCTAGTGGGAGCTTGTGCCATGGAGAAGTGCAAGTTTAATGGTAACTGGATTATTAATCCCACGTTCACGA
+
1=DDDBDHDFHHEDHEGI?IACHHBFB?FCHEHFEFC3D:DDAHG@GCGEHFGIIGC@GC<C@FHGGGEG@E=C=?A;?CDEE@>D;>C<AB=?B>@?5


Ray

**Comment by ndierckx** [comment]
Is it not paired end then? Or the just have the same number in separate files?

**Comment by melop** [comment]
Hi,

      sorry for not making it clear. The mates in the read 2 file have the same name as read 1, both files are synchronized with the read names 1 , 2, 3 ... .

Ray

**Comment by melop** [comment]
Hi,

      I have "combined reads" blank and have each read separated for read1 and read2 in the config:

Save assembled reads = no
Combined reads       = 
Forward reads        = read1.fq.gz
Reverse reads        = read2.fq.gz

Ray

**Comment by ndierckx** [comment]
Are you sure the first line of read1.fq.gz is identical to read2.fq.gz
Because if those lines are identical it can't give that error

**Comment by melop** [comment]
Ok, something weird happened. 
I unzipped these files and it reads them fine.

Perhaps some issues with reading gzipped files?

Ray

**Comment by ndierckx** [comment]
It's an internal perl function but it could be there a some problems with it sometimes.
I will add it to the error message for the next update

**Comment by melop** [comment]
I see. I usually use a pipe to call the system "zcat -f" command for reading in gzipped files. 
Not sure if that helps in this case though.

Best
Ray

**Comment by OmonkeyGOD** [comment]
Hi,
I got the same error as the two files' first lines are not identical. The IDs contain read length information and the read length for forward-sequencing and reverse sequencing are different.
I downloaded sra data and use fastq-dump --skip-technical --split-files --clip sra_id to generate fastq files. Should I delete the length information in the first line? Or any parameters I can use to ignore that?

@ERR2017218.1 HISEQ:273:C3YCJACXX:6:1101:1847:2188 length=100
CACACGTGTGTACCGCTTTTTTCGTGCCGCGGTTATTTTGGCTCATTCTAACAGATTAATCATCCTTGTATACCGTCCATCGCTTTTGGTTTCCCCAATC
+ERR2017218.1 HISEQ:273:C3YCJACXX:6:1101:1847:2188 length=100
CCCFFFFFHHHHHJJJJJJJJJJIHIJJIJIJFHHIJJJIIHHHHHHFFFFFFEEEEEEEDDDDDDDDDDEEFDDDDDDEDDDDDDDDDBDDDCDDDDDD
@ERR2017218.1 HISEQ:273:C3YCJACXX:6:1101:1847:2188 length=101
GGAGCTATTTGAGAAACTGCGGGGAATGTGAGCGACAGGTACTGTAGGAAGAATGACTTACGAAATGTTCGAGCAGCAATGTAGAGAGGGTAGTTGATCCA
+ERR2017218.1 HISEQ:273:C3YCJACXX:6:1101:1847:2188 length=101
CCCFFFFFHHHGHJJJJJJJJJJJIJJJHIJJJJIJJIJAHHHHHFFFFFEEEEEEEDDDDDDDDDDFEEDDDDDDDDDDDDEEEDDDDD8ABCEDDDDDD

**Comment by ndierckx** [comment]
Hi, Either the ids need to indicate if they are forward or reverse or the pairs have to be identical.
So it is best to remove the lengths indeed

**Comment by OmonkeyGOD** [comment]
Okey. thanks

**Comment by OmonkeyGOD** [comment]
Hi,
I still have some questions.
After assembling the mitochondrial genome, I also want to annotate it. I notice there is a Circos folder in this repository; I am curious which program do you use to annotate the genome? 
And if I want to analyze the SNPs, I should use other programs, right? Thanks!

**Comment by ndierckx** [comment]
Hi,

What do you mean by analysing the SNPs? And the cricos folder is only for heteroplasmy detection. It provides annotation of the human mitogenome, but for any other species you need to do the annotation with another tool. I haven't done it for years so I am not much help there
