### ISSUE TITLE
Result has repeated segments and many incomplete genes

### ISSUE THREAD

**Issue by melop** [ndierckx/NOVOPlasty#27]
Hello,

I am seeing that in one genus of fish the output MT assembly is consistently around 12kb - 13kb, which is shorter than normal fish mt of ~16.8kb. The log reports that the assembly was "successful" and it is circularized. 

I am using 100x2 Illumina PE reads as input, and a preliminary mt assembly for a closely related species as seed.
 
Strangely annotation by MITOS shows that the assembly have a whole segment containing 12s and 16s duplicated, while missing many other genes.

Any suggestions on how to proceed?
![screenshot from 2017-09-26 19 17 54](https://user-images.githubusercontent.com/1661121/30874150-d260231a-a2ef-11e7-8df6-cc492587c9a3.png)

**Comment by melop** [comment]
I confirm that in another species of the same genus, the reconstructed assembly also looks the same. Basically it's like 2 identical sequences repeated twice.
If I increase the size range limit to >14kb, then an assembly with 3 repeats will be returned. 
![hit_matrix](https://user-images.githubusercontent.com/1661121/30903619-a96010bc-a36f-11e7-9729-67a715359a98.png)

Ray

**Comment by ndierckx** [comment]
You can send me the extended log, then I will have a look
If everything is repeated, it could be that it has multiple smaller circular mitochondria
Then it will keep going in circles till it reaches the genome range

**Comment by ndierckx** [comment]
Try with a seed of one the missing genes, see what you get then, maybe a small circle again
