### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by reinator** [ndierckx/NOVOPlasty#28]
Hey, thanks for developing such a good organellar assembler! =)
My suggestion is that we could specify an output paramenter, where NOVOplasty would save all the output files.
Guess it's not too difficult to implement that xD

Thanks in advance and best regards!

**Comment by ndierckx** [comment]
What do you mean with all the output files?
Which ones don't output?

Greets

**Comment by reinator** [comment]
It would be just to specify an output directory where to save all the output files generated by NovoPlasty.
