### ISSUE TITLE
Optimizing with small insert size

### ISSUE THREAD

**Issue by owensgl** [ndierckx/NOVOPlasty#29]
Hi,
I'm trying to assemble mitochondria from S. cerevisiae. It's 150bp paired-end data, that I've trimmed for adapters, with an average insert size of ~150-200bp. This is not ideal for assembly, but I'm trying to see what I can get out of the data.  Novoplasty is having a lot of trouble assembling it. Depending on what part of the known mitochondrial genome I use I get between 700 and 7000bp assembled. 
My questions are:
1) Are there any parameters I can tweak to try to get more of its assembled?
2) Is there a prescribed procedure for trying different seeds? If I give it the entire genome as a seed, it only uses one part as a seed. To get better results I've been giving it smaller chunks and testing, but that seems kind of slapdash.

My config file is:
Project name         = Yeast.mitochondria.v1
Insert size          = 200
Insert size aut      = yes
Read Length          = 151
Type                 = mito
Genome Range         = 60000-100000
K-mer                = 45
Insert Range         = 2.0
Insert Range strict  = 1.2
Single/Paired        = PE
Max memory           = 80GB
Extended log         = 1
Save assembled reads = no
Combined reads       =
Forward reads        = MA_ctrl_dip_wt_1_trim_R1.fastq
Reverse reads        = MA_ctrl_dip_wt_1_trim_R2.fastq
Seed Input           = tmp.fasta
Reference            =
Chloroplast sequence =

Thanks for any help.

**Comment by ndierckx** [comment]
Hi,

Could you send me the log and extended log, then I can see if there is improvement possible.
And max memory you should just write 80, don't know if 80GB will work

**Comment by owensgl** [comment]
Here's the log.
[log_extended_Yeast.mitochondria.v1.txt](https://github.com/ndierckx/NOVOPlasty/files/1391959/log_extended_Yeast.mitochondria.v1.txt)

**Comment by ndierckx** [comment]
Thanks, do you also have the normal log file?

**Comment by owensgl** [comment]
Sorry, misread your request. Here's the normal log:

-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.3
Author: Nicolas Dierckxsens, (c) 2015-2017
-----------------------------------------------


Input parameters from the configuration file:   *** Verify if everything is correct ***

Project name         = Yeast.mitochondria.v1
Insert size          = 200
Insert size auto     = yes
Read Length          = 151
Type                 = mito
Genome range         = 60000-100000
K-mer                = 45
Insert range         = 2.0
Insert range strict  = 1.2
Paired/Single        = PE
Max memory           = 80
Extended log         = 1
Save assembled reads = no
Combined reads       =
Forward reads        = MA_ctrl_dip_wt_1_trim_R1.fastq
Reverse reads        = MA_ctrl_dip_wt_1_trim_R2.fastq
Seed Input           = tmp.fasta
Reference sequence   =
Chloroplast sequence =

Subsampled fraction: 100.00 %

Initial read retrieved successfully: CGAAAAAAAGGTATAAACCTTTTCACCTAAAACATAAGGTTTAACTATAAAAGTACGGCCCCTAATTAAATTAATAAGAATATAAATATATTTAAGATGGGATAATCTATATTAATAAAAATTTATCTTAAAATATATATATTATTAATAA

Start Assembly...


------------Assembly 1 finished: Contigs are automatically merged in Merged_contigs file------------

Contig 01                  : 7186 bp

Total contigs              : 1
Largest contig             : 7186 bp
Smallest contig            : 7186 bp
Average insert size        : 215 bp


-----------------------------------------Input data metrics-----------------------------------------

Total reads                : 2204094
Aligned reads              : 12238
Assembled reads            : 7366
Average organelle coverage : 257

----------------------------------------------------------------------------------------------------

**Comment by ndierckx** [comment]
Hi,

The problem is that the assembly ends on both sides because the coverage is too low in those regions.
New Illumina kits have less problem with it but older ones have a strong reduction in coverage in AT rich regions. In your case those regions are quite long and the coverage reduces all the way to zero.

Maybe try with a kmer of 23, that should help with lower coverage, but can't say if it will improve much.
With a larger insert size, NOVOPlasty can use paired read information to skip these regions, but your insert size is a bit short for these long regions.

And isn't there a good reference of this genome, it should be sequenced already no?
Don't know if it will help much for this version, but in the next version you will be able to retrieve a next seed by tracking the reference sequence

**Comment by owensgl** [comment]
Thanks for the advice, I'll try it out. 

There is a good reference for this (actually probably many), but I'm trying to see if there is large scale variation in my set of samples. I've tried giving it the full length mitochondria as the seed, but it tends to do worse, I think because it starts in a bad spot.

**Comment by ndierckx** [comment]
You shouldn't give it as seed, but as a reference. If you want I can send a new version which is also a variance caller, it creates a vcf file compared to the given reference, but still assembles everything de novo

**Comment by owensgl** [comment]
OK, I'll try that. I incorrectly thought that the reference referred to the nuclear genome and that it was doing something to exclude nuclear sequences. 
In the manual it refers to the giving a mitochondrial genome as a seed, so that led me to put the full mitochondrial sequence as a seed. Also, I think it's a little weird that I can give it a full mitochondria as a reference but I still need to give it a seed. In my case, I'm just pulling out a chunk of that reference sequence as a seed.
