### ISSUE TITLE
Can't open the seed file, No such file or directory

### ISSUE THREAD

**Issue by etvedte** [ndierckx/NOVOPlasty#30]
I'm trying to assembly mitochondria using NOVOPlasty v 2.6.3. Here's what prints to terminal, with error message:

-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.3
Author: Nicolas Dierckxsens, (c) 2015-2017
-----------------------------------------------

Can't open the seed file, No such file or directory

I've attached my config file, my seed file, and partials of my read files. I double-checked the path of my seed and even specified other seeds with seed paths to assess whether it was an issue with navigating to the seed. The issue persists. Do you have any suggestions? Thanks in advance.

[config.txt](https://github.com/ndierckx/NOVOPlasty/files/1402320/config.txt)

[DA_500ins_REV_sample.fastq.gz]
(https://github.com/ndierckx/NOVOPlasty/files/1402322/DA_500ins_REV_sample.fastq.gz)

[DA_500ins_FWD_sample.fastq.gz](https://github.com/ndierckx/NOVOPlasty/files/1402323/DA_500ins_FWD_sample.fastq.gz)

[DA_COI.txt](https://github.com/ndierckx/NOVOPlasty/files/1402325/DA_COI.txt)

**Comment by ndierckx** [comment]
It's because you deleted lines from the config line you can't do that.

Greets

**Comment by etvedte** [comment]
Ok, thanks. I figured it was something minor. Running now!
