### ISSUE TITLE
please give me a hand 

### ISSUE THREAD

**Issue by Y369421** [ndierckx/NOVOPlasty#31]
How to download and install the NOVOPlasty, I can't find the where can be downloaded, I want to your help, thank you

**Comment by paulotokimatu** [comment]
The software is here in this repository. Since it seems that you are not familiar with Git, I think the easiest way is to go to https://github.com/ndierckx/NOVOPlasty and click the button "Clone or download", then click in "Download ZIP". Finally, extract the file in your computer.

**Comment by ndierckx** [comment]
I just got back from New York so didn't had the time to respond. 
So thanks Paulo for replying! Maybe you should ask help from colleague?

**Comment by Y369421** [comment]
thank you, I've already downloaded it,  but my colleagues never download the software, no one will install and run it, so it is diffcult for me to run NOVOPlasty, I am trying to learn it.
