### ISSUE TITLE
the ID stucture problem

### ISSUE THREAD

**Issue by MeiyuanJi** [ndierckx/NOVOPlasty#32]
hello, everyone!
I have a problem when I use NOVOPLasty. 
When I have written my txt file, and run my script with the command line: 
perl /NOVOPlasty2.6.3.pl -c *.txt
it has some problems. 
![default](https://user-images.githubusercontent.com/33933620/33355952-bfaf9ae8-d4f4-11e7-85c4-2a4697d55641.png)
but I checked my fastq file, and I am sure the format is correct. there are some parts of my fastq file.
forward file:
![default](https://user-images.githubusercontent.com/33933620/33355825-1939d8b8-d4f4-11e7-9bb5-e7faea0bb7be.png)
reverse file:
![default](https://user-images.githubusercontent.com/33933620/33355833-2719cb1e-d4f4-11e7-9ab6-ec3ae39c452f.png)
anyone has the same problem as me? 
thanks so much!

**Comment by ndierckx** [comment]
Hi,
Could be that the last plus sign is a problem.
I will fix it tomorrow, then you can download the new version.

**Comment by ndierckx** [comment]
I had a look again, I just think you switched the forward with the reverse file..
The forward file should be the one with the '1' after the space

**Comment by MeiyuanJi** [comment]
thanks so much for your help! I have figured out this problem with your solution.
