### ISSUE TITLE
INVALID SEED issues

### ISSUE THREAD

**Issue by Batwarren** [ndierckx/NOVOPlasty#33]
Good afternoon. 

I'm in the process of using NOVOPlasty to generate over 40 mitochondrial genomes from whole genome sequencing data. It has worked excellently for 37 of these and passably well for 3 (two failed to circularise but appear complete with the exception of a tandem repeat region; one apparently did circularlise despite missing this region and the region following it entirely), giving me far superior outputs to any reference-based method. 

I'm trying to get the last two genomes to work, and am hitting opposite problems with them. One will not complete (I've given it different lengths of time and am trying different seeds to see if I can surmount this problem) and the other effectively will not start - I keep getting the 'INVALID SEED, PLEASE TRY AGAIN WITH A NEW ONE' error. 

To generate the seeds that I've used for each genome, I first mapped the reads to a reference and then used a mapped read that blasted to a well-characterised gene in a closely related species. As the seed is very literally taken from the dataset that I am attempting to generate the mitochondrion from, I'm not sure how it could be invalid? 

Any guidance on this very much appreciated!

**Comment by ndierckx** [comment]
Could be the coverage is too low?
And do those reads have the same id structure as the successful ones?
You can always send me the id structure so I can check or if you can send the data I can try myself

**Comment by Batwarren** [comment]
In terms of ID structure it should be the same as the successful ones - all files were generated in the same manner. I even tried using a successful read from another individual (they are members of the same species so should be pretty close), but got the INVALID SEED error there, too. The only seed so far that did not return this error led to the assembly of a single ~600bp contig. Adding a reference sequence to the config file in this case did not seem to make any difference.

I have noticed that there appears to be a much smaller number of reads mapping to a reference mitochondrion from this individual compared to the others, so if this error could be linked to coverage then that is likely the problem. What kind of coverage does NOVOPlasty need in order to run successfully?

**Comment by ndierckx** [comment]
It probably will be a low coverage problem, can you send me the config file, maybe you can adjust some parameters? 
Theoretically a coverage of 10X would be enough, but only when it is equally distributed, which is often not the case, especially not with older illumina kits

**Comment by Batwarren** [comment]
The config file is mostly default: 

Config file: 
Project name         = KwRp036
Insert size          = 300
Insert size aut      = yes
Read Length          = 150
Type                 = mito
Genome Range         = 15500-17500
K-mer                = 39
Insert Range         = 1.6
Insert Range strict  = 1.2
Single/Paired        = PE
Max memory           = 12
Extended log         = 0
Save assembled reads = no
Combined reads       =
Forward reads        = /data/omicsScratch/btw822/MitoMethods/KwRp036_forward_paired.fq.gz
Reverse reads        = /data/omicsScratch/btw822/MitoMethods/KwRp036_reverse_paired.fq.gz
Seed Input           = /data/omicsScratch/btw822/MitoMethods/KwRp036_seed.fasta
Reference            =
Chloroplast sequence =

The seed file is as follows: 
>KwRp036.ND2.read
ATGCTAGAATTTTTCGTAGTTGGGTTTGGTTCAGTCCTCCTCAACCTCCGATCAGAATGGATAGGATGGATATGGTGAGTAGAATGTTTGGGTTAATTGAGTGTGAAATTTGGTAAAGAATTGAAAGGGGGGCTAGTTTTTGTCACGTGA

The original WGS was 5X for a few individuals and 10X for most (including this individual), so organelle coverage should theoretically be well above that. Looking at the successful assemblies, the average organelle coverage as calculated by NOVAplasty is wildly variable, with most between 25 and 300 though one at 975, one at 1089 and one at 41510!

**Comment by ndierckx** [comment]
I had users before with an unexpected low coverage (<2X) of the organelle genome, so it could be very low. Try to put k-mer to 23 and insert range to 1.8, maybe it will help a bit
And did you get this in the log file: Subsampled fraction: 100.00 %
If it is not 100%, you didn't use all the data so you should use a machine with more memory

**Comment by Batwarren** [comment]
I will try that with the kmer and insert range.

The subsampled fraction in this case is 15.06% - across the whole set of individuals it ranges from 13.18 to 26.63% (a sole individual reaches the giddy heights of 54.47%), so I had assumed it was just intentionally downsampling! I am working on a cluster so giving it more memory is easy to do.

**Comment by ndierckx** [comment]
The max memory is for down sampling if you have huge datasets or no enough memory, but if you have more memory, better to use it! Usually 12 GB  is more then enough, but sometimes the organelle fraction is very low, so then better to use higher. So try to increase it for  your problematic regions. If it gets the invalid seed error, it must be very low, so use as much as possible

**Comment by Batwarren** [comment]
Just to update you on this, having followed your advice I have indeed received an error stating that the coverage is too low, rather than just the invalid seed error. So the coverage does appear to be the problem. I'll continue increasing the available memory and see if I can get a high enough read sampling to rectify this. Thank you for your prompt and helpful responses!
