### ISSUE TITLE
reference as seed

### ISSUE THREAD

**Issue by bnsacks** [ndierckx/NOVOPlasty#34]
NOVOPlasty seems like a great program and I am excited to get it to work.  I began a job 6 hours ago and nothing has output to the log file since indicating it is creating the hash table.  It could be taking so long because I used the entire forward and reverse adapter-trimmed fastq.gz files (about 7 MiB each, HiSeq4000 PE150).  On the other hand, I am wondering if perhaps I erred in my config file and this is causing the program to freeze.  Specifically, I used the same fasta file (a conspecific mitogenome) for both the seed and the reference.  
My questions: 
(1) Is there any problem with using a the same fasta file (a conspecific mitogenome) for both the seed and the reference? (as opposed to a distantly related sp. or small fragment of the target sp mitogenome for the seed)
(2) If not a problem, is it safe to assume that the program is working properly even though nothing has been output since the initial indication:

-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.3
Author: Nicolas Dierckxsens, (c) 2015-2017
-----------------------------------------------

Reading Input......OK

Input parameters from the configuration file:   *** Verify if everything is correct ***

Project name         = elk_mito
Insert size          = 300
Insert size auto     = yes
Read Length          = 150
Type                 = mito
Genome range         = 12000-20000
K-mer                = 39
Insert range         = 1.6
Insert range strict  = 1.2
Paired/Single        = PE
Max memory           = 
Extended log         = 0
Save assembled reads = yes
Combined reads       = 
Forward reads        = /mnt/steelhead/remote/Data_Shared/2015-12-05/trimmed/trimmed_S14-2919_S80_L007_R1_001.fastq.gz
Reverse reads        = /mnt/steelhead/remote/Data_Shared/2015-12-05/trimmed/trimmed_S14-2919_S80_L007_R2_001.fastq.gz
Seed Input           = /mnt/steelhead/remote/ben/MitogenomeReference/CelaphusMitogenomeRef.fa
Reference sequence   = /mnt/steelhead/remote/ben/MitogenomeReference/CelaphusMitogenomeRef.fa
Chloroplast sequence = 

Scan reference sequence......OK

Building Hash Table...
Thanks!
Ben

**Comment by ndierckx** [comment]
Hi,

It probably got stuck because you ran out of memory...
How much memory you have available? 
And there is a max memory option, it's best to fill it in (only numbers in GB)

**Comment by bnsacks** [comment]
Thanks for your rapid response. I tried specifying memory and had the same problem. I was not sure of the memory limits of that linux box, so I moved onto a cluster and am attempting with '20' written in for max memory. I seem to be stuck now with a different problem: the programs says it cannot find my files, yet I have verified the paths and filenames are correct as specified (I realize that I left a 't' out of NOVOPlasty when naming the working directory, but that is consistent and not the problem). Here is my config file:
Project name         = S16-4558_mito
Insert size          = 300
Insert size aut      = yes
Read Length          = 150
Type                 = mito
Genome Range         = 12000-20000
K-mer                = 39
Insert Range         = 1.6
Insert Range strict  = 1.2
Single/Paired        = PE
Max memory           = 20
Extended log         = 1
Save assembled reads = yes
Combined reads       =
Forward reads        = ~/elk-roos-rm/trimmedreads/trimmed_S16-4558_S83_L002_R1_001.fastq.gz
Reverse reads        = ~/elk-roos-rm/trimmedreads//trimmed_S16-4558_S83_L002_R2_001.fastq.gz
Seed Input           = ~/bin/NOVOPlasy-Master/seedfragment.fa
Reference            = ~/bin/NOVOPlasy-Master/CcanadensisReference.fa
Chloroplast sequence = 

ODDLY, I GET AN ERROR MESSAGE SAYING NO SUCH PATH OR FILE FOR THE TRIMMED READS, BUT I HAVE VERIFIED BOTH ARE CORRECT. SAME WITH SEED FILE.

==========================================
SLURM_JOB_ID = 17785809
SLURM_NODELIST = c9-68
==========================================
-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.6.3
Author: Nicolas Dierckxsens, (c) 2015-2017
----------------------------------------------
gzip: ~/elk-roos-rm/trimmedreads/trimmed_S16-4558_S83_L002_R1_001.fastq.gz: No such file or directory
Can't open the seed file, No such file or directory
===========================================================================
Job Finished

**Comment by bnsacks** [comment]
(the extra slash in the reverse pathname was fixed and not the problem; same result)

**Comment by bnsacks** [comment]
ok, when I substituted explicit path specification from the /home/ directory in place of ~/ in the config file, it ran!  (It is running, so hopefully will work now...)

**Comment by bnsacks** [comment]
It worked!! Thanks!

**Comment by ndierckx** [comment]
Great!
