### ISSUE TITLE
Incorrect file format with fastq data from SRA

### ISSUE THREAD

**Issue by reubwn** [ndierckx/NOVOPlasty#36]
Hi Nicolas,

NOVOPlasty appears not to play nicely with fastq data downloaded directly from SRA. I think it's just a simple fastq header format issue. Headers look like this:
```
@ERR321927.976 MERCURE_0067:7:1:2983:2129 length=101
```
and result in the error:
```
THE INPUT READS HAVE AN INCORRECT FILE FORMAT!
PLEASE SEND ME THE ID STRUCTURE!
```
but a simple reformatting to this:
```
@MERCURE_0067:7:1:2983:2129
```
removes the problem.

I don't know if the above is the universal format for SRA files (or just for these ones), but it would be great were NOVOPlasty able to recognise it.

Thanks for the great tool!

reubwn

**Comment by ndierckx** [comment]
Hi,

thanks for reporting this, I will add the structure to the next version!
It's not all SRA data, because I used some before

**Comment by ndierckx** [comment]
Could you also send me the header of the reverse file?

**Comment by reubwn** [comment]
Sure. It's actually the same as the F file:
```
@ERR321927.976 MERCURE_0067:7:1:2983:2129 length=101
```

**Comment by ndierckx** [comment]
Then it should work though, unless you use a combined file.
Did you use the separate paired files in your config file?

**Comment by reubwn** [comment]
Yes I used separate fastq files. Thanks again!

**Comment by ndierckx** [comment]
Could you send me the config file you used?
An which SRA accession is it, maybe I will try myself.

**Comment by reubwn** [comment]
The config looked like this:
```
Project name         = mito
Insert size          = 225
Insert size aut      = yes
Read Length          = 101
Type                 = mito
Genome Range         = 12000-20000
K-mer                = 39
Insert Range         = 1.6
Insert Range strict  = 1.2
Single/Paired        = PE
Max memory           = 40
Extended log         = 0
Save assembled reads = yes
Combined reads       = 
Forward reads        = tmp_1.fq
Reverse reads        = tmp_2.fq
Seed Input           = mito.full_genome.fasta
Reference            = 
Chloroplast sequence = 
```
where `tmp_*.fq` were the reformatted fastq files.

I had to do this for data from SRA accessions SRR801084 and ERR321927 (from approx 2012, so a while ago now!)

**Comment by ndierckx** [comment]
If the 'Combined reads' line is empty and the read ids are identical, it should work.
But sometimes the config file can creates errors when it get modified, maybe the download the latest version with the new config file. If this new version doesn't work I will check those data files myself

**Comment by Ajit81** [comment]
Hi Nicolas,
I have downloaded fastq from SRA using command:

fastq-dump -O Genomic --split-files --origfmt --gzip

And the fastq format look like this.

@HWI-ST1324:206:C2E8CACXX:3:1101:1474:1992
NTAGCAATTTCATAAATTGTGGTACAATAGTTGATGGAAATATATTCTTGTAGGATAAACGCGGTATATTCCGACACATTAAGGACGCATTGAGAAATGAA
+HWI-ST1324:206:C2E8CACXX:3:1101:1474:1992
#1:BABDBDDFHFIIIIIGFHGGH@<AAA?AHH>FHB@FCFD49DDAGG*:B@F:DBFBDEB:@;@;=@;?EFEEBCC<CC@55>A@@@?B:A>ACCC3>>
@HWI-ST1324:206:C2E8CACXX:3:1101:1613:1912
NGGTAAGTTGACGAACGGTTGTATGGCTGATATGACTGGAAATCGGCAATGATAACTGCAGAAATGTTAAGCTTTTAAATTTAGATGAGAATATCGAGATT
+HWI-ST1324:206:C2E8CACXX:3:1101:1613:1912
#1:=BDDBCADHAEHGGHDGBHGIICGGCGEHIGGGIABFEI<DEEGHEAHAEADEGHGGGGFFB@BCCC>ACCCCCCCCDCC@CCCACCC:@>3<ABBBC

After running NOVOplasty, got same error as Reuben.

THE INPUT READS HAVE AN INCORRECT FILE FORMAT!
PLEASE SEND ME THE ID STRUCTURE!

Please suggest me, if I have to download from SRA with a different option and if it needed to reformat fastq before running. Please help me in reformatting the fastq file.

I am attaching the config and log file.

Thank you
[config.txt](https://github.com/ndierckx/NOVOPlasty/files/1892503/config.txt)
[log.txt](https://github.com/ndierckx/NOVOPlasty/files/1892504/log.txt)
[SRR1556038_1_head.fastq.txt](https://github.com/ndierckx/NOVOPlasty/files/1892505/SRR1556038_1_head.fastq.txt)

**Comment by ndierckx** [comment]
I will have a look at it, could you send me the also the head of the reverse file?
Greets

**Comment by Ajit81** [comment]
Thank you Nicolas.

Have a good day.

Ajit

Ajit Kumar Patra
Post-Doc Research Scientist, Team of Marine Bio-Informatics
National Marine Biodiversity Institute of Korea
75, Jangsan-ro 101beon-gil, Janghang-eup, Seocheon-gun,
Chungcheongnam-do, Korea, 33662
Tel: +82-41-950-0785 <041-950-0785> Mob: +82-10-3177-9805 <010-3177-9805>

**Comment by ndierckx** [comment]
Hi, I uploaded version 2.6.6, could you try this one

Greets

**Comment by Ajit81** [comment]
Hi Nicolas,
Its now working.
Thank you for your help.

Regards

Ajit

**Comment by huieli** [comment]
Hi,

i used the version 2.6.6 to run chloroplast genome, but i got too many contigs and no circularized one, i want to send you the  log_extended file, but i was told that was too big to send, could you please help me to improve the run and get a  circularize whole cp genome?
Thanks so much!
Best!




--


李慧娥

贵州大学农学院

贵州贵阳  550025　　　　　

Huie Li 

College of Agriculture, Guizhou University

Guiyang, Guizhou, 550025




 


At 2018-04-10 10:23:07, "Nicolas Dierckxsens" <notifications@github.com> wrote:


I found the problem, will upload a new version tomorrow..

**Comment by huieli** [comment]
I will have a look at it when I have time, I have to change some code for it...
________________________________
From: 李慧娥 <greenhopeli@126.com>
Sent: 20 April 2018 2:50
To: ndierckx/NOVOPlasty; nicolasdierckxsens@hotmail.com
Subject: too many contigs from NOVOPlasty

Hi,
i used the version 2.6.6 to run chloroplast genome, but i got too many contigs and no circularized one, i want to send you the  log_extended file, but i was told that was too big to send, could you please help me to improve the run and get a  circularize whole cp genome?
Thanks so much!
Best!



--

李慧娥

贵州大学农学院

贵州贵阳  550025　　　　　

Huie Li

College of Agriculture, Guizhou University

Guiyang, Guizhou, 550025




At 2018-04-10 10:23:07, "Nicolas Dierckxsens" <notifications@github.com> wrote:

I found the problem, will upload a new version tomorrow..

―
