### ISSUE TITLE
No input file found, make sure it are fastq files No such file or directory

### ISSUE THREAD

**Issue by ZhouHYe** [ndierckx/NOVOPlasty#37]
my config file is as below
------

Project name          = Test
Type                  = chloro
Genome Range          = 12000-22000
K-mer                 = 39
Max memory            = 
Extended log          =0
Save assembled reads  = yes
Seed Input            = Seed_Bstr.fasta
Reference sequence    = 
Variance detection    = no
Heteroplasmy          = 
Chloroplast sequence  = 

Read Length           = 150
Insert size           = 619000
Insert size aut       = yes
Platform              = illumina
Single/Paired         = PE
Combined reads        = read.test.fq
Forward reads         = 
Reverse reads         = 

Insert size auto      = yes
Insert Range          = 1.6
Insert Range strict   = 1.2

---
the read.test.fq was under the path of this software and it was really fastq format. I do not know what was wrong. Thank you.

**Comment by ndierckx** [comment]
Hi, 

You should keep the config file structure the same. I see you deleted some lines. And i just uploaded a new version with a new config file so make sure you download both new files
