### ISSUE TITLE
Options for "Saved assembled reads" don't match the manual

### ISSUE THREAD

**Issue by edgardomortiz** [ndierckx/NOVOPlasty#38]
Hello,
I wrote "no" for this setting and the script says is expecting either 1 or 2, what does 1 mean in this case, and what does 2.

Edgardo

**Comment by edgardomortiz** [comment]
Not really and issue. I got it now, just leave it empty.

**Comment by ndierckx** [comment]
Hi,
Sorry I forgot to answer. I changed that for a user, 1 is the same as yes, but if you type 2, it will keep the original read ids in the saved file, but this will require more virtual memory.
