### ISSUE TITLE
illumina error?

### ISSUE THREAD

**Issue by quattrinia** [ndierckx/NOVOPlasty#39]
Tried using this for the first time and receiving this error

Platform has to be 'illumina' or 'ion', please check the configuration file! 

here is my config file
Project:
-----------------------
Project name          = SAF067
Type                  = mito
Genome Range          = 12000-26000
K-mer                 =39 
Max memory            = 
Extended log          = 0
Save assembled reads  = no
Seed Input            = SAF067.fasta
Reference sequence    = 
Variance detection    = no
Heteroplasmy          = 
Chloroplast sequence  = 

Dataset 1:
-----------------------
Read Length           = 150
Insert size           = 350
Platform              = illumina
Single/Paired         = PE
Combined reads        =
Forward reads         = /data/mcfadden/apentico/Data/SAfric/SAF0671.fq
Reverse reads         = /data/mcfadden/apentico/Data/SAfric/SAF0672.fq

Optional:
-----------------------
Insert size auto      = yes
Insert Range          = 1.8
Insert Range strict = 1.3

**Comment by ndierckx** [comment]
Hi,

You must have changed something in the structure of the config file, so you should redownload it.
Or you are not using version 2.6.4

Greets

**Comment by quattrinia** [comment]
thanks. not sure what happened but its working now.
