### ISSUE TITLE
thanks for the free software, but I don't how to use it

### ISSUE THREAD

**Issue by SkyStarStear** [ndierckx/NOVOPlasty#41]
I want to assembly the Plant mitochondria.And i have some questions for your help:
1.the seed sequence  I don't know whether it's the beginning of the Mitochondrial ring or just one kind of short sequence must be in my data.And i see RUBP sequences can be used to chloroplast assembly,and i can find it in my chloroplast of Pine.Or i can use the reference sequence just as seed.
2.we know the Plant mitochondria is too long,and i don't know how to ensure the parameter,such as
Project:
-----------------------
Project name          = R102mio
Type                  = mito_plant
Genome Range          = 100000-500000
K-mer                 = 39
Max memory            = 
Extended log          = 0
Save assembled reads  = yes
Seed Input            = /home/liuzl/zz/R102/tiadong.fasta
Reference sequence    = /home/liuzl/zz/R102/tiadong.fasta
Variance detection    = yes
Heteroplasmy          = 
Chloroplast sequence  = /home/liuzl/zz/R102/zuzhuang.fasta

Dataset 1:
-----------------------
Read Length           = 50
Insert size           = 170
Platform              = illumina
Single/Paired         = PE
Combined reads        =
Forward reads         = /home/liuzl/zz/R102/Pine_H722-R102_good_fq_trimmed.fastq
Reverse reads         = /home/liuzl/zz/R102/Pine_H722-R102_good_2fq_trimmed.fastq
Optional:
-----------------------
Insert size auto      = yes
Insert Range          = 
Insert Range strict   =
Actually I am new here for the assembly  Plant mitochondria as just an Chinese university student.Luckily i find this software which can be used for  Plant mitochondri ,I don't how to show my thanks to you.I try it some times,but the reasult is still 0 kb.And i really need your help,thanks!!!

**Comment by SkyStarStear** [comment]
I means I can't find RUBP sequences in chloroplast  of Pine.

**Comment by SkyStarStear** [comment]
![9_](https://user-images.githubusercontent.com/37580451/37653377-abd46e9a-2c79-11e8-92c6-83a6a7064d75.jpg)

**Comment by ndierckx** [comment]
Hi,

Did you tried to assemble the chloroplast already? Maybe first star with that. And you don't have to use the RUBP sequence. You can also use a different species as seed. Just use a sequence that is not often duplicated in the mitochondrial genome. 

As for the mitochondrial assembly, it is quite complicated and I see you have reads of 50 bp, that's very short so wouldn't expect much from that data

**Comment by SkyStarStear** [comment]
Thank you,ndierckx
I have assembled the chloroplast already,but not use this software.
And the seed suquence means the most impossible sequence,right?that's to say if i assembled the chloroplast,i need to select the sequence not in chloroplast.
And I want to know what's the Read Length and Insert size  usually be to assemble mito_plant.
BEST

**Comment by ndierckx** [comment]
For the Seed sequence: Look for the closest related mitochondrial genome and take a sequence to doesn't align to your assembled chloroplast sequence. 
And are you sure the read length is 50 bp? Or is it very old data?
And I see you trimmed it, I shouldn't do that it's already short enough! :)
You can also not use a kmer of 39 with a read length of 50, that won't work.
So try a kmer of 19...

As for the read length, the longer the better, but at least 100 bp. These days people don't sequence below 150 bp anyway.. As for the insert size, it depends on the assembly algorithm you use...
