### ISSUE TITLE
platform

### ISSUE THREAD

**Issue by huieli** [ndierckx/NOVOPlasty#42]
I have set the platform as 'illumina', but when i run the pro, i was still told that 'Platform has to be 'illumina or 'ion', please check the configration file'', the below is my config file:
roject name          = YNMAYchloro

Test
Type              = chloro

Genome Range          = 12000-22000

K-mer                 = 39

Max memory            = 

Extended log          = 1

Save assembled reads  = no

Seed Input            = ../desktop/NOVOplasty/Seed/Seed.fasta

Reference sequence    = 

Variance detection    = no

Heteroplasmy          = 

Chloroplast sequence  = 
Read Length           = 148
Insert size           = 300

Platform              = illumina
Single/Paired         = PE

Combined reads        = ../desktop/NOVOplasty/Reads/reads.fastq
Forward reads         = 

Reverse reads         = 

Insert size auto      = yes

Insert Range          = 1.8

Insert Range strict   = 1.2

**Comment by huieli** [comment]
can i send the config file to your email? the stucture seems changed when i post here

**Comment by ndierckx** [comment]
This is weird because that error is only possible if the config file has been modified incorrectly
I will send a version to your mail to test what's happening

**Comment by huieli** [comment]
I know the reason why now, the Win system could not support this program very well, especially for the config file......

**Comment by MorneDuPlessis** [comment]
Hi, 

Any solution yet, as I have exactly the same error. Only changes I made to the original file was to point to the seed reference and then to the Forward and Reverse reads respectively

Regards,

Morne

**Comment by ndierckx** [comment]
Hi,

I think it works now for huieli, so maybe he can tell what the problem was. But I think it it is some problem with the Windows editor you use to modify the file. I will fix it when I am back from holiday the 15th. You could maybe try with an older version where the config file is not yet divided in the three parts

Greets,

Nicolas

**Comment by MorneDuPlessis** [comment]
Hi,

That would make sense. I have had similar situations to this before. Will try different editors and see.

Thanks,

Morne
________________________________

**Comment by ndierckx** [comment]
Hi 
Do you still have the problem (with version 2.6.8)?

**Comment by hhhh5** [comment]
I just had the same error message and the simple fix was to convert the Windows to Unix line endings.

**Comment by ndierckx** [comment]
ok thanks for reporting.
So you are running it in Windows and the config file is not compatible?
And may i ask what the difference is with Windows and Unix line endings.

**Comment by hhhh5** [comment]
Windows uses carriage return and line feed ("\r\n") as a line ending, while Unix uses just line feed ("\n").
http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html

I edited the config file on Windows and uploaded it to an Ubuntu server to run NOVOPlasty, that's when I got the error message. Maybe you could run config files trough `dos2unix` to avoid this problem in the future.

By the way, the de novo assembly of my NGS data from 54 mitochondrial genomes just finished and your program worked beautifully: except for one it returned for all samples single contig of the right length.

**Comment by Angele97** [comment]
Hello, I encountered the same problem than you and I would like to know how exactly you fixed it.

I used NOVOPlasty and config on Windows and want to run it on Windows Terminal Command Prompt while I am connected to a server.

Like you, I only changed the Seed Input and Forward/Reverse reads.

I also used NOVOPlasty3.7.pl and not NOVOPlasty3.2.pl as reported in the code (I don't if something is changed with that)

Thank you for your help !

I am a beginner in bioinformatics, I like that and you can't imagine how frustrating it is for me when it doesn't work.

**Comment by hhhh5** [comment]
The easiest solution would be to open your config file using Sublime Text (https://www.sublimetext.com/, free evaluation period) and change the line endings to whatever you need (Windows, Unix, Mac OS; look in the "View" menu), save it again and upload it to the server where you are running NOVOPlasty.

**Comment by ndierckx** [comment]
@hhhh5 Thanks for answering

@Angele97 I am currently on holiday so can't fix it, but will try to solve it when i am back

**Comment by Angele97** [comment]
That work with Sublime Test !

@hhhh5 Thank a lot !

**Comment by uzma-researcher** [comment]
Hi Nicolas,
I also got the same problem. I have emailed you my configure file. Would you please see and help me?
Best,

**Comment by matiaskohler** [comment]
I got the same issue, and apparently was able to fix using the Sublime Text and changing the line endings of the config.txt to Unix. 

Thanks @hhhh5 .

**Comment by ndierckx** [comment]
I think the problem should be fixed in version 3.7.1

**Comment by uzma-researcher** [comment]
Yes, indeed, I have checked!
