### ISSUE TITLE
config file processing error

### ISSUE THREAD

**Issue by asinensis** [ndierckx/NOVOPlasty#49]
I think the "Project" section of the config.txt has 1 character cut off when processing. I circumvented the problem by adding extra space (total 2 after =) but you may want to update your code...

**Comment by ndierckx** [comment]
Hi,
Thanks for pointing it out. Do you have the problem with Windows or also with Linux?

**Comment by ndierckx** [comment]
that's weird I never had that problem, I will be back from holiday in 3 days, I will do some tests then

**Comment by ndierckx** [comment]
I changed the way NOVOPlasty reads the config file in 2.6.8 so maybe you could try this version?

**Comment by ndierckx** [comment]
Hi,

there was a bug in 2.6.8, but 2.7.0 should work fine
