### ISSUE TITLE
Problem at line 22160?

### ISSUE THREAD

**Issue by lyr6714** [ndierckx/NOVOPlasty#53]
Hi
I just ran NOVOPlasty on Illumina PE data from a fish species with a mtDNA reference. It seemed to run OK but ended with the message: "Can't use an undefined value as a symbol reference at NOVOPlasty2.7.1.pl line 22160."

I don't really think it is a problem, but I am not sure what it means . I hope you can clarify. Thanks.

**Comment by ndierckx** [comment]
Hi,
It will be fixed with the next version, it is just because I had switch something off 
Does it still outputs the results or does it abort the run?

**Comment by lyr6714** [comment]
Hi

The outputs look fine. Thanks for clarifying.
