### ISSUE TITLE
Smallest contig  : 1000000000000000000000000000000000 bp

### ISSUE THREAD

**Issue by kajsah** [ndierckx/NOVOPlasty#58]
Hello,

I have now run reads from 33 individuals with NOVOPlasty. Most of them works very well. But some are not. For example this one. The total reads are almost 60 millions but aligned reads are only 9318. Not a single contig is assembled. But the smallest contig is nonetheless  1000000000000000000000000000000000 bp. 

Do you know what could have gone wrong?
Thank you
Kajsa

Total contigs              : 0
Largest contig             : 0 bp
Smallest contig            : 1000000000000000000000000000000000 bp
Average insert size        : 361 bp
-----------------------------------------Input data metrics--------------------
Total reads                : 59881462
Aligned reads              : 9318
Assembled reads            : 0
--------------------------------------------------------------------------------

**Comment by ndierckx** [comment]
You can ignore the 1000000000000000000000000000000000 bp
It seems nothing is assembled, try maybe a different seed

**Comment by kajsah** [comment]
Ok, will do.

**Comment by kajsah** [comment]
Hello, I have now tried with another seed and two of the three were assembled. Then I tried yet another seed with the one not assembled. And I get one suggestion for assembly of several different contigs. How sure can I be that this suggestion is correct? I also wonder why just this individuals reads are so hard to assemble when the other very similar individuals from the same species has been so easy?

**Comment by kajsah** [comment]
Hello again,

I have now tried some different seeds with the last individual. And I don't get a Circularized_assembly file. But I get an Option_1 file with what seems to be the whole mt genome since it is very similar with the other mt genomes. Now I just wonder, what's the difference between a Circularized_assembly file and a Option_1 file?

**Comment by ndierckx** [comment]
Hi,

If you get a circularized file, it means it assembled a contig until it formed a circle (in one go) Option files mean there were overlapping contigs that were merged in to one circular genome.

About your previous question, I can't say without looking at the assembly, but could be because of lower coverage or repetitive regions in control region (can differ a lot between individuals)

**Comment by kajsah** [comment]
Ok, thank you!

If it is repetitive regions that make it hard to assemble, how can I continue to resolve the repetetive area? Or is it even possible to do that?

**Comment by ndierckx** [comment]
Hard to say, without extra data not much I guess, short reads have their limit
