### ISSUE TITLE
Error "gzip: stdout: Broken pipe"

### ISSUE THREAD

**Issue by AGrusz** [ndierckx/NOVOPlasty#59]
I am attempting to run novoplasty.pl but received the error message "**gzip: stdout: Broken pipe**". 

Do you happen to know if this is an error with my config/input files or could it be something related to submission on our computing cluster?

Any suggestions would be much-appreciated!

Thanks, 
AG

**config.txt**
Project:
-----------------------
Project name          = PF-S8_LL
Type                  = chloro
Genome Range          = 120000-200000
K-mer                 = 39
Max memory            = 
Extended log          = 0
Save assembled reads  = no
Seed Input            = /home/grusza/shared/RNA_RATES/rbcl_myrlin.txt
Reference sequence    = 
Variance detection    = no
Heteroplasmy          = 
HP exclude list       =
Chloroplast sequence  = 

Dataset 1:
-----------------------
Read Length           = 150
Insert size           = 300
Platform              = illumina
Single/Paired         = PE
Combined reads        =
Forward reads         = /home/grusza/algrusz/Myriopteris_Illumina/PF-S8/PF-S8_S8_L001_R1_001_PE.fastq.gz
Reverse reads         = /home/grusza/algrusz/Myriopteris_Illumina/PF-S8/PF-S8_S8_L001_R2_001_PE.fastq.gz

Optional:
-----------------------
Insert size auto      = yes
Insert Range          = 1.8
Insert Range strict   = 1.3
Use Quality Scores    = no

Project:
-----------------------
Project name         = Choose a name for your project, it will be used for the output files.
Type                 = (chloro/mito/mito_plant) "chloro" for chloroplast assembly, "mito" for mitochondrial assembly and 
                       "mito_plant" for mitochondrial assembly in plants.
Genome Range         = (minimum genome size-maximum genome size) The expected genome size range of the genome.
                       Default value for mito: 12000-20000 / Default value for chloro: 120000-200000
                       If the expected size is know, you can lower the range, this can be useful when there is a repetitive
                       region, what could lead to a premature circularization of the genome.
K-mer                = (integer) This is the length of the overlap between matching reads (Default: 39). 
                       If reads are shorter then 90 bp or you have low coverage data, this value should be decreased down to 23. 
                       For reads longer then 101 bp, this value can be increased, but this is not necessary.
Max memory           = You can choose a max memory usage, suitable to automatically subsample the data or when you have limited                      
                       memory capacity. If you have sufficient memory, leave it blank, else write your available memory in GB
                       (if you have for example a 8 GB RAM laptop, put down 7 or 7.5 (don't add the unit in the config file))
Extended log         = Prints out a very extensive log, could be useful to send me when there is a problem  (0/1).
Save assembled reads = All the reads used for the assembly will be stored in seperate files (yes/no)
Seed Input           = The path to the file that contains the seed sequence.
Reference (optional) = If a reference is available, you can give here the path to the fasta file.
                       The assembly will still be de novo, but references of the same genus can be used as a guide to resolve 
                       duplicated regions in the plant mitochondria or the inverted repeat in the chloroplast. 
                       References from different genus haven't beeen tested yet.
Variance detection   = If you select yes, you should also have a reference sequence (previous line). It will create a vcf file                
                       with all the variances compared to the give reference (yes/no)
Heteroplasmy         = If yo uwant to detect heteroplasmy,first assemble the genome without this option. Then give the resulting                         
                       sequence as a reference and as a seed input. And give the minimum minor allele frequency for this option 
                       (0.01 will detect heteroplasmy of >1%)
HP exclude list      = Option not yet available  
Chloroplast sequence = The path to the file that contains the chloroplast sequence (Only for mito_plant mode).
                       You have to assemble the chloroplast before you assemble the mitochondria of plants!

Dataset 1:
-----------------------
Read Length          = The read length of your reads.
Insert size          = Total insert size of your paired end reads, it doesn't have to be accurate but should be close enough.
Platform             = illumina is for now the only option
Single/Paired        = For the moment only paired end reads are supported.
Combined reads       = The path to the file that contains the combined reads (forward and reverse in 1 file)
Forward reads        = The path to the file that contains the forward reads (not necessary when there is a merged file)
Reverse reads        = The path to the file that contains the reverse reads (not necessary when there is a merged file)

Optional:
-----------------------
Insert size auto     = (yes/no) This will finetune your insert size automatically (Default: yes)
Insert Range         = This variation on the insert size, could lower it when the coverage is very high or raise it when the
                       coverage is too low (Default: 1.6). 
Insert Range strict  = Strict variation to resolve repetitive regions (Default: 1.2).                                
Use Quality Scores   = It will take in account the quality scores, only use this when reads have low quality, like with the    
                       300 bp reads of Illumina (yes/no)

**submission.pbs**
#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=8,mem=16gb
#PBS -N novoplasty_LL
#PBS -o novoplasty_LL.out.txt
#PBS -e novoplasty_LL.err.txt
#PBS -m abe
#PBS -M algrusz@d.umn.edu

module load  perl/5.26.1

perl /home/grusza/shared/RNA_RATES/NOVOPlasty2.7.2.pl -c /home/grusza/shared/RNA_RATES/config.txt

**seed_file.txt**
>rbcl_Myrlin
GTTGGATTCAAAGCTGGTGTCAAAGATTACCGATTGACCTATTACACTCCCGAATACAAGACCAAAGATA
CTGATATCTTAGCAGCTTTCCGAATGACCCCCCAACCTGGAGTACCGGCTGAGGAAGCTGGAGCTGCAGT
AGCTGCGGAATCTTCTACGGGTACATGGACCACGGTATGGACAGACGGACTTACTAGTCTTGATCGCTAC
AAGGGTCGATGCTATGATATTGAGCCCGTCGCTGGGGAAGAGAATCAGTATATTGCATACGTAGCTTATC
CTCTGGATTTATTCGAGGAAGGTTCCGTTACCAATATGCTGACTTCTATTGTAGGTAATGTTTTTGGATT
TAAGGCCCTACGCGCTCTGCGTCTGGAAGACCTACGAATTCCTCCTGCTTATTCCAAAACTTTTATCGGA
CCCCCCCATGGTATTCAGGTGGAAAGGGATAAACTAAACAAATACGGACGTCCCCTACTGGGATGTACAA
TCAAGCCAAAATTGGGCTTGTCTGCCAAGAATTATGGTAGAGCAGTTTATGAATGCCTTCGTGGTGGACT
TGATTTCACAAAAGATGATGAAAACGTGAATTCCCAACCGTTTATGCGTTGGAGAGATCGATTCTTATTC
GTAGCAGAAGCCCTTTTTAAATCTCAGGCTGAAACGGGCGAAATCAAGGGGCATTACTTAAATGCCACTG
CAGGTACGTGTGAAGAGATGATGAAGAGGGCTGTTTTCGCCAGAGAATTGGGTGTACCAATCGTCATGCA
TGACTACCTGACGGGAGGGTTTACCGCAAATACCAGCTTAGCTCATTACTGCAGAGACAATGGACTACTT
CTTCATATTCACCGGGCGATGCATGCTGTCATTGATAGACAACGGAATCACGGTATGCATTTCCGTGTAT
TAGCCAAAGCATTACGCATGTCCGGTGGGGATCATATCCATGCCGGAACTGTAGTGGGCAAATTAGAAGG
TGAACGAGAAGTCACCCTGGGATTTGTCGACTTACTCCGTGACGATTATATCGAAAAGGATCGTAGCCGT
GGCATCTATTTTACCCAAGATTGGGTATCCATGCCGGGCGTACTCCCAGTAGCTTCAGGGGGTATTCATG
TCTGGCACATGCCTGCCTTAACTGAAATTTTTGGGGACGACTCTGTTCTACAATTCGGCGGGGGAACATT
GGGACACCCTTGGGGAAATGCACCCGGTGCCGTGGCTAACCGAGTTGCATTAGAGGCTTGCGTACAGGCT
CGTAATGAGGGCCGTGACCTCGCTCGTGAAGGTAAT

**Comment by ndierckx** [comment]
Hi,

It is probably a problem with your seYou can try by updating Perl
Or just unzip your fastq files and then you won't have that problem anymore
