### ISSUE TITLE
Seed coverage issue?

### ISSUE THREAD

**Issue by jullee** [ndierckx/NOVOPlasty#60]
I'm attempting to assemble a sunflower mitochondrial genome using NOVOPlasty but am getting an error during running. The program stops after seed retrieve and indicates that "COVERAGE IS TOO LOW, SHOULD BE MORE THAN 10X".  I'm using the sunflower COXIII gene as the seed. This is a genome skimming dataset but I expect the coverage to be >10x. Any thoughts?

My parameters are:

Project:
-----------------------
Project name          = Test_mt_ANN01
Type                  = mito_plant
Genome Range          = 200000-300000
K-mer                 = 39
Max memory            = 
Extended log          = 0
Save assembled reads  = no
Seed Input            = /home/leeyaw/mt_skimming_assembly/annuus_coxIII.fasta
Reference sequence    = /home/leeyaw/mt_skimming_assembly/sunflower_mt_ref.fa
Variance detection    = no
Heteroplasmy          = 
HP exclude list       =
Chloroplast sequence  = /home/leeyaw/mt_skimming_assembly/ANN01-CWIA_cp.fasta

Dataset 1:
-----------------------
Read Length           = 100
Insert size           = 300
Platform              = illumina
Single/Paired         = PE
Combined reads        = /home/leeyaw/mt_skimming_assembly/ann01-cwIA.all_reads.fastq
Forward reads         = 
Reverse reads         = 

Optional:
-----------------------
Insert size auto      = yes
Insert Range          = 1.8
Insert Range strict   = 1.3
Use Quality Scores    = no

**Comment by ndierckx** [comment]
Hi,
The coverage will be lower than the chloroplast coverage. If it gives that error, it is probably too low, but try with kmer 23, then you need a bit less coverage
