### ISSUE TITLE
Out of Memory!

### ISSUE THREAD

**Issue by yaradua** [ndierckx/NOVOPlasty#61]
Thank you for proving us with this programme. I want to assemple chloroplast genome from WGS, reading inputs are Ok, but after the programme run for about an hour it shows "Out of Memory". I need help please. Thank you.
-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.7.2
Author: Nicolas Dierckxsens, (c) 2015-2018
-----------------------------------------------

Input parameters from the configuration file:   *** Verify if everything is correct ***

Project:
-----------------------
Project name          = Test
Type                  = mito
Genome range          = 150000-180000
K-mer                 = 39
Max memory            = 200
Extended log          = 0
Save assembled reads  = no
Seed Input            = C:\Users\SAMAILA YARADUA\Desktop\reference genome of acantheceae\Strobilanthes cusia.fasta
Reference sequence    = C:\Users\SAMAILA YARADUA\Desktop\reference genome of acantheceae\Strobilanthes cusia.fasta
Variance detection    = no
Heteroplasmy          =
HP exclude list       =
Chloroplast sequence  =

Dataset 1:
-----------------------
Read Length           = 151
Insert size           = 300
Platform              = illumina
Single/Paired         = PE
Combined reads        = C:\Users\SAMAILA YARADUA\Desktop\training\S8_DSW63438-V_HL5LKCCXY_L1_1.fastq
Forward reads         =
Reverse reads         =

Optional:
-----------------------
Insert size auto      = yes
Insert range          = 1.8
Insert range strict   = 1.3
Use Quality Scores    = no

Reading Input......OK

Scan reference sequence......OK

Building Hash Table...Out of memory!

**Comment by ndierckx** [comment]
Just lower the max memory a bit, that option is not 100% accurate, it is more like an estimation
How much memory you have?
If you have 200 GB of RAM, you should put a bit lower because you can't use it all

**Comment by ndierckx** [comment]
nothing to do with the memory but put the type to chloro (not mito)

**Comment by yaradua** [comment]
I am using windows, 500GB hardisck, 4GB Ram

**Comment by ndierckx** [comment]
that is not much, why do you fill in 200 for max memory?
Try to put 4 but you should better work on a server

**Comment by yaradua** [comment]
Ok, Thank you let me try. how much times does it normally takes for the assembly?
Thank you.

**Comment by yaradua** [comment]
I have run the programme with 4 as the maximum memory and I change to chloro. it is running for the past 15 hours, still building hash table.

-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.7.2
Author: Nicolas Dierckxsens, (c) 2015-2018
-----------------------------------------------


Input parameters from the configuration file:   *** Verify if everything is correct ***

Project:
-----------------------
Project name          = Test
Type                  = chloro
Genome range          = 150000-180000
K-mer                 = 39
Max memory            = 4
Extended log          = 0
Save assembled reads  = no
Seed Input            = C:\Users\SAMAILA YARADUA\Desktop\reference genome of acantheceae\Strobilanthes cusia.fasta
Reference sequence    = C:\Users\SAMAILA YARADUA\Desktop\reference genome of acantheceae\Strobilanthes cusia.fasta
Variance detection    = no
Heteroplasmy          =
HP exclude list       =
Chloroplast sequence  =

Dataset 1:
-----------------------
Read Length           = 151
Insert size           = 300
Platform              = illumina
Single/Paired         = PE
Combined reads        =
Forward reads         = C:\Users\SAMAILA YARADUA\Desktop\S8_DSW63438-V_HL5LKCCXY_L1_1.fq-1\Blepharis.fastq
Reverse reads         = C:\Users\SAMAILA YARADUA\Desktop\S8_DSW63438-V_HL5LKCCXY_L1_1.fq-1\Blepharis2.fastq

Optional:
-----------------------
Insert size auto      = yes
Insert range          = 1.8
Insert range strict   = 1.3
Use Quality Scores    = no


Reading Input......OK

Scan reference sequence......OK

Building Hash Table...


Is everything alright?
how much times does it takes to finish the assembly?

Thank you.

**Comment by ndierckx** [comment]
Put 3 because you probably don't have 4 available on your laptop, there are always background processes that need memory

**Comment by yaradua** [comment]
ok, you are right, I will do that now. what is the normal time it takes for the assembly on windows?

Thank you.

**Comment by yaradua** [comment]
I finished running the assembly, this is what I got.

-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.7.2
Author: Nicolas Dierckxsens, (c) 2015-2018
-----------------------------------------------


Input parameters from the configuration file:   *** Verify if everything is correct ***

Project:
-----------------------
Project name          = Test
Type                  = chloro
Genome range          = 150000-200000
K-mer                 = 39
Max memory            = 4
Extended log          = 0
Save assembled reads  = no
Seed Input            = C:\Users\Muzammil Bacha\Desktop\TRAINING\reference genome of acantheceae\Strobilanthes cusia.fasta
Reference sequence    =
Variance detection    = no
Heteroplasmy          =
HP exclude list       =
Chloroplast sequence  =

Dataset 1:
-----------------------
Read Length           = 151
Insert size           = 300
Platform              = illumina
Single/Paired         = PE
Combined reads        =
Forward reads         = C:\Users\Muzammil Bacha\Desktop\TRAINING\S8_DSW63438-V_HL5LKCCXY_L1_1.fastq
Reverse reads         = C:\Users\Muzammil Bacha\Desktop\TRAINING\S8_DSW63438-V_HL5LKCCXY_L1_02.fastq

Optional:
-----------------------
Insert size auto      = yes
Insert range          = 1.8
Insert range strict   = 1.3
Use Quality Scores    = no


Reading Input......OK

Building Hash Table......OK

Subsampled fraction: 18.55 %

Retrieve Seed......OK

Initial read retrieved successfully: CGGTTGATGATATCAGCCCAAGTATTAATTACACGGCCTTGACTATCAACTACAGATTGGTTGAAATTGAAACCATTTAGGTTGAAAGCCATAGTGCTGATACCTAAAGCAGTGAACCAGATACCCACTACAGGCCAAGCAGCTAGGAAG

Start Assembly...


------------Assembly 1 finished: Contigs are automatically merged in Merged_contigs file------------

Contig 01                  : 132719 bp
Contig 02                  : 18169 bp
Contig 03                  : 18017 bp

Total contigs              : 3
Largest contig             : 132719 bp
Smallest contig            : 18017 bp
Average insert size        : 321 bp


-----------------------------------------Input data metrics-----------------------------------------

Total reads                : 6532710
Aligned reads              : 712764
Assembled reads            : 392224

----------------------------------------------------------------------------------------------------


Thank you for using NOVOPlasty!

In the folder, there is contigs 1 test, 
option 1 test
option 2 test

in contig 1 file have the following
>Contig01+13759541
base pairs
>Contig02+1132719
base pairs
>Contig03+2132719
base pairs

which of the file contain the complete chloroplast genome?

Thank you.

**Comment by ndierckx** [comment]
you are lucky, you got a complete assembly with only 18% of the reads.
It is in the merged files, it is all stated in the manual

**Comment by yaradua** [comment]
Hello Nicholas,

In addition to my earlier comment, I annatotated contig1 and both of the two option but the position of the inverted repeat is same in all and the position of the inverted repeats is not OK. what can I do?

**Comment by ndierckx** [comment]
just align by blast or run again with a reference to pick the correct one

**Comment by yaradua** [comment]
I run again with reference but still the same ....

**Comment by ndierckx** [comment]
blast against reference then or check annotation

**Comment by yaradua** [comment]
okay, thank you.

**Comment by yaradua** [comment]
can u suggest annotation tool for me? I used geseq in chlorobox
