### ISSUE TITLE
Input reads no trimming?

### ISSUE THREAD

**Issue by jullee** [ndierckx/NOVOPlasty#62]
Hi I'm wondering why the documentation says not to trim reads? Our usual protocol in the lab is to remove adaptors and to trim the leading and trailing ends of reads where base quality is low. Is it possible to use NOVOplasty after this type of trimming of reads? Thanks

**Comment by ndierckx** [comment]
Yes you can still use it, just wouldn't recommend it. Can only cause problems and has no advantages.
But in most cases it won't affect the assembly
