### ISSUE TITLE
Inverted repeats, SSC and LCS not in right positions

### ISSUE THREAD

**Issue by yaradua** [ndierckx/NOVOPlasty#63]
Hello Nicholas,

I assembled 3 chloroplast genome but the postions of IR, SSC and LCS are not in the right positions I used complete cp genome of related species as seed and reference. can you help out please.

Thank you.

**Comment by yaradua** [comment]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\1802204>cd Desktop\NOVOPlasty-master

C:\Users\1802204\Desktop\NOVOPlasty-master>perl NOVOPlasty2.7.2.pl -c config.txt


-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.7.2
Author: Nicolas Dierckxsens, (c) 2015-2018
-----------------------------------------------


Input parameters from the configuration file:   *** Verify if everything is correct ***

Project:
-----------------------
Project name          = Barleria spp.
Type                  = chloro
Genome range          = 150000-180000
K-mer                 = 31
Max memory            = 10
Extended log          = 0
Save assembled reads  = no
Seed Input            = C:\Users\1802204\Desktop\reference genome of acantheceae\seed.fasta
Reference sequence    =
Variance detection    = no
Heteroplasmy          =
HP exclude list       =
Chloroplast sequence  =

Dataset 1:
-----------------------
Read Length           = 151
Insert size           = 300
Platform              = illumina
Single/Paired         = PE
Combined reads        =
Forward reads         = C:\Users\1802204\Desktop\10\S10_DSW63440-V_HL5LKCCXY_L1_1.fastq
Reverse reads         = C:\Users\1802204\Desktop\10\S10_DSW63440-V_HL5LKCCXY_L1_2.fastq

Optional:
-----------------------
Insert size auto      = yes
Insert range          = 1.8
Insert range strict   = 1.3
Use Quality Scores    = no


Reading Input......OK

Building Hash Table......OK

Subsampled fraction: 41.87 %

Retrieve Seed......OK

Initial read retrieved successfully: AGAACAAGAAAGAGTTTATTGCTCCTTGATTTTCTTTTCAATTAGTATTTTTTTAGTAATATTATATTTACCTAGACTTTTCTTCTTTCCATTCCAGAAACCATTTCAGAAAAAGAAAGGGAAGTCATTCTATTCTTAAGGTTTGATTAA

Start Assembly...


------------Assembly 1 finished: Contigs are automatically merged in Merged_contigs file------------

Contig 01                  : 134414 bp
Contig 02                  : 18975 bp
Contig 03                  : 18822 bp

Total contigs              : 3
Largest contig             : 134414 bp
Smallest contig            : 18822 bp
Average insert size        : 319 bp


-----------------------------------------Input data metrics-----------------------------------------

Total reads                : 16496028
Aligned reads              : 481738
Assembled reads            : 305756
Organelle genome %         : 2.92 %
Average organelle coverage : 478

----------------------------------------------------------------------------------------------------


Thank you for using NOVOPlasty!


C:\Users\1802204\Desktop\NOVOPlasty-master>

if you look at the ouput, total read is 16496028 while read is  481738. what is the problem?
Thanks

**Comment by ndierckx** [comment]
That's normal, organelle reads are a small portion of the complete dataset
