### ISSUE TITLE
problem with orientation

### ISSUE THREAD

**Issue by kyalosaina** [ndierckx/NOVOPlasty#64]
Thank you for developing this programme. I assemble one genome successfully, the position of the IRs, SSC and LSC is correct. but for other samples the orientation is not correct. what is the problem.

Kyalo

**Comment by ndierckx** [comment]
Did you had multiple options in the merged file of those assemblies?

**Comment by kyalosaina** [comment]
thank you for your response. Yes, there are two options, Option 1 and Option 2

**Comment by ndierckx** [comment]
Hi, sorry forgot to answer.
If you have two options, one of the two should have the correct orientation...
