### ISSUE TITLE
very few reads assembling

### ISSUE THREAD

**Issue by jullee** [ndierckx/NOVOPlasty#65]
I'm stumped over the results I'm getting from the program (vs. 2.7.2) when trying to assemble the chloroplast. 

I provide a reference chloroplast from the same species (151 000 bp) and use the rbcL gene as the seed. The program runs but produces only one very small contig and the output says only 22 reads have been assembled. The reads are untrimmed (only adaptor removed with Trimmomatic) fastq.gz files, and only reads with a pair have been provided (unpaired reads output from Trimmomatic were not included). Curious why this might be happening? We have decent coverage for the nuclear genome so I doubt its a coverage issue...

My log file is 
[log_Test_cp_ANN01.txt](https://github.com/ndierckx/NOVOPlasty/files/2474938/log_Test_cp_ANN01.txt)
included. Any help would be greatly appreciated.

**Comment by ndierckx** [comment]
You have put max memory to 1 so subsampled only 5 % of your data. You must have more than 1 GB of RAM available?

**Comment by jullee** [comment]
Hi thanks for the suggestion but now when I leave the memory parameter
black, it gives the same error during the hashtag table build. How much
memory does the program require? The cluster machines are each 5 IBM 3550
computers with 8 cores and 8 GB of ram (I am using one core but given that
it should be possible to run Novoplasty on my desktop, I don't know why
this would matter). My fastq.gz files are 1.5 GB.

Thanks!

**Comment by jullee** [comment]
I moved to a bigger computer and it seems to have worked.
