### ISSUE TITLE
Post-processing of contigs

### ISSUE THREAD

**Issue by jullee** [ndierckx/NOVOPlasty#66]
My output contains 9 contigs when assembling the chloroplast genome. They have the following headers:

>Contig01+58914932
>Contig02+152441912
>Contig02+152441912
>Contig03+76160031
>Contig03+76160031
>Contig03+76160031
>Contig03+76160031
>Contig03+76160031
>Contig03+76160031

My question is why so many are called "Contig03"? 

And what is the recommended way for assembling these further? I'm comparing the results from NOVOplasty to MITObim which returns one single long contig...why might NOVOplasty be resulting in a fragmented assembly? 

Thanks

**Comment by ndierckx** [comment]
Hi,

Hard to say with this information. Can you send me the log and the 'merged' file?
And with MITObim, did you use the de novo or mapping stand? And did it gave a circularize contig?

**Comment by jullee** [comment]
Also to answer the questions about MITOBim: I used the two step process (so first MIRA to create a new ref). As for creating a circular contig: I challenged the program differently, asking for a linear molecular without the second repeat. One of the advantages of NOVOplasty over MITObim is I suspect NOVOplasty will have better handling of the repeat...perhaps I'm wrong?

**Comment by ndierckx** [comment]
I would not trust the mapping mode of MITObim, It sometimes just copies the reference you used. If it was the de novo mode you can trust the results i think

And you should run NOVOPlasty again because you put read length 100 bp in the config file, while it should be 150

**Comment by jullee** [comment]
Thank you for your continued help. I reran NOVOplasty with the read length set to 100 bp instead of 150 and now my output contains four "Option" files. If I understand correctly, these are various alternative assemblies of the contigs in the "Contigs" file. 

Does it make sense that the Contigs file now has many more contigs than when I ran the program at 150 bp? 

Is it that the Options file assemblies have already been show to circularize or do I have to check that separately? 

What do you recommend for verifying or choosing among alternative assemblies? 

Thanks again!

**Comment by ndierckx** [comment]
When you have multiple options, they are all circularized
And it's normal you have more contigs with 100 bp because 150 bp is incorrect and can lead to early termination.
If you used already the closest reference during the assembly, it won't be resolved automatically
You can align manually to your closest reference and visually inspect
Can you send me the merged file?

**Comment by jullee** [comment]
I'm confused by the response. Above you suggested to use 150 bp as the insert size. Is this correct?

All the circularized options for the chloroplast assembly also seem to contain mitochondrial genes (genes found only in the mitochondria) as per my post here: https://github.com/ndierckx/NOVOPlasty/issues/67

Here is the log and merged files
[log_Test_cp_ANN01.txt](https://github.com/ndierckx/NOVOPlasty/files/2563311/log_Test_cp_ANN01.txt)
[Merged_contigs_Test_cp_ANN01.txt](https://github.com/ndierckx/NOVOPlasty/files/2563312/Merged_contigs_Test_cp_ANN01.txt)
