### ISSUE TITLE
Mitochondrial reads in chloroplast assembly

### ISSUE THREAD

**Issue by jullee** [ndierckx/NOVOPlasty#67]
I assembled the chloroplast genome in order to then assemble the mitochondrial genome of a plant. For the mitochondrial genome, I used the COXIII gene as a seed. But my mitochondrial assembly produces only two very short contigs. 

I did a quick check of the alignment of the COXIII seed to my NOVOplasty chloroplast assembly and see that I get perfect alignment, suggesting the software may be assembling part of the mitochondria in the chloroplast. Any tips for overcoming this problem or is it simply not going to be possible to use NOVOplasty for my species?

**Comment by ndierckx** [comment]
chloroplast assemblies should be correct because those reads are much more abundant
but plant mitogenoems are full of chloroplast sequences so you need a seed that is not present in the chloroplast else the assembly won't work

I always use this seed for chloroplast assemblies, but I don't have much experience with plant mitochondria
[Seed_RUBP.txt](https://github.com/ndierckx/NOVOPlasty/files/2561420/Seed_RUBP.txt)

**Comment by jullee** [comment]
The seed I'm using is a mitochondrial gene not found in the true chloroplast genome. The problem is that my chloroplast assemblies contain this gene. In other words, I can't trust the assemblies because they obviously contain mitochondrial sequences. I see that in the paper there was this problem mentioned for some of the plant assemblies....is it likely to be common then?

**Comment by ndierckx** [comment]
I never encountered this problem so I should check if it generates hybrid assemblies. Was this assembly the only output or were there different options? If it is not with all options it’s no problem, sometimes some options are hybrid assemblies. Could you send me the merged file of this chloroplast assembly?

**Comment by jullee** [comment]
It happened with all Options. Here is the merged file. Also happy to send you the full set of input files for the analysis offline .
[Merged_contigs_Test_cp_ANN01.txt](https://github.com/ndierckx/NOVOPlasty/files/2563482/Merged_contigs_Test_cp_ANN01.txt)

**Comment by ndierckx** [comment]
I am on my phone now, i will check it later! Maybe i can try myself with your data

**Comment by jullee** [comment]
That would be so great. I've been struggling to get the software running for a few weeks now and clearly still having issues.

**Comment by ndierckx** [comment]
Seems you have a problematic case, I will try myself. Can you share them?

**Comment by jullee** [comment]
I am working on creating a Google Drive folder link that I can share with
you with all the data. Thanks!

**Comment by jullee** [comment]
Dropbox link with the input files sent! Thanks again for looking into this.
