### ISSUE TITLE
Illegal division by zero at NOVOPlasty2.7.2.pl line 21094

### ISSUE THREAD

**Issue by ycuenot** [ndierckx/NOVOPlasty#68]
Hi,
I run NOVOPlasty2.7.2 to assemble a fish mitochondrial. The seed is the sequence of 12S from the same species. It seems that it is not running.
I get this message:

------------Assembly 1 finished: Contigs are automatically merged in Merged_contigs file------------
Total contigs              : 0
Largest contig             : 0 bp
Smallest contig            : 1000000000000000000000000000000000 bp
Average insert size        : 300 bp
Illegal division by zero at NOVOPlasty2.7.2.pl line 21094.

I attached the log_extended.txt.
[log_extended_Test.txt](https://github.com/ndierckx/NOVOPlasty/files/2561848/log_extended_Test.txt)

Can you help me?
Thank you,
Yves

**Comment by ndierckx** [comment]
Hi,
Could you also send me the normal log file?

**Comment by ndierckx** [comment]
The error can only exist when there are no reads in the input files, so something must have gone wrong there. Can you send me a screenshot of the first lines of your data files

**Comment by ycuenot** [comment]
Here the logfile:
[log_Test.txt](https://github.com/ndierckx/NOVOPlasty/files/2562249/log_Test.txt)

**Comment by ycuenot** [comment]
You answered to my question. It was a data file problem. I just delete it and download it again and now NOVOPlasty is running. I will wait the output file to see the results,
Thanks a lot and excuse me for that,
Yves
