### ISSUE TITLE
input file size limit

### ISSUE THREAD

**Issue by aremkho** [ndierckx/NOVOPlasty#69]
Good day Nikolas,
Thank you for maintaining and updating the repository.
 I am wondering if there is any limit in input file size.
I have a forward and reverse fq files each 159 GB.
I run them  in our cluster with 800 GB RAM and 54 CPUs.
After quiet a few hours i see that log/contig files are both zero in size.
I have attached my extended log.
I will appreciate your kind advice.
Thanks
[log_extended_Cryptopygus_51.txt](https://github.com/ndierckx/NOVOPlasty/files/2585682/log_extended_Cryptopygus_51.txt)

**Comment by arsalane1978** [comment]
by the way my forward and reverse reads are merged files of different runs ...
Thanks

**Comment by ndierckx** [comment]
Hi,

No there is no limit, but it will slow down the process a lot. I see you have a coverage above 20000, which is not necessary:) so use the max memory option to subsample your data automatically. Try max memory of 50, that is already a lot

**Comment by arsalane1978** [comment]
Thanks Nicolas!
