### ISSUE TITLE
Meaning of Coverage Cut off

### ISSUE THREAD

**Issue by CheWeiHsu** [ndierckx/NOVOPlasty#7]
Hi Nicolas,
Thank you for the software! 
I would like to know more about the meaning of the parameter : Coverage Cut off
Why do you choose 1000 as the default? Does it have anything to do with coverage of the data set? 
For example, If my coverage for mitochondrion and chloroplast is estimated to have around 50X and 350X respectively, how should I tune the parameter? or should I change it ?

Best regards,
Willy

**Comment by ndierckx** [comment]
It means that NOVOPlasty won't look for any further matches after 1000. Lowering can speed up the assembly if you have high coverage but not necessary, could be useful if you need to assemble many samples routinely. So I wouldn't change it

**Comment by CheWeiHsu** [comment]
Got it! Thanks a lot.
