### ISSUE TITLE
Processing Circularized assembly fasta

### ISSUE THREAD

**Issue by jullee** [ndierckx/NOVOPlasty#70]
I'm analyzing a new dataset and assembling the chloroplast genome. 

The program seems to complete correctly and but the outputs are not the same as those listed in the Readme file. Instead, I get a fasta file called "Circularized_assembly_1_sample.fasta", a log file, and a "contigs_tmp" file. The Circularized_assembly file contains five contigs. What are the steps for putting these together? Do I just align to the reference genome?

My output files are attached (the fasta converted to text to upload here)

Thanks!

[Circularized_assembly_1_sample.txt](https://github.com/ndierckx/NOVOPlasty/files/2646387/Circularized_assembly_1_sample.txt)
[log_sample.txt](https://github.com/ndierckx/NOVOPlasty/files/2646390/log_sample.txt)
[contigs_tmp_sample.txt](https://github.com/ndierckx/NOVOPlasty/files/2646395/contigs_tmp_sample.txt)

**Comment by jullee** [comment]
My goal is to actually assemble the mitochondria. Can I use this
Circularized file as my chloroplast assembly for this process? In other
words, does it matter if the chloroplast assembly has multiple contigs when
assembling the mitochondria? OR would it be better for me to use the
reference chloroplast (i.e. as if I hadn't assembled the chloroplast) as
input when assembling the mitochondrial genome?

Many thanks again for your continued help!

**Comment by ndierckx** [comment]
It is best to use the assembled chloroplast, it is no problem that there are multiple contigs.
Plant mitochondrial genomes can very complex, so the assembly of it won't be easy
