### ISSUE TITLE
Too small size of Novoplasty assembled mitochondrion genome

### ISSUE THREAD

**Issue by lakhujanivijay** [ndierckx/NOVOPlasty#71]
Hi Nicolas,

Hope you are doing well. I am kind of stuck in the assembly process and I thought I would ask you directly about the same here. I have 2 mitochondrion samples from  _Saccharomyces cerevisiae_, the details of the PE, Illumina data is given below

file           |format|type|num_seqs|sum_len   |min_len|avg_len|max_len
:--------------|:-----|:---|:-------|:---------|:------|:------|:------
sam1_R1.fq.gz|FASTQ |DNA |22439284|2916398955|40     |130.0  |150
sam1_R2.fq.gz|FASTQ |DNA |22439284|2920279652|40     |130.1  |150
sam2_R1.fq.gz|FASTQ |DNA |17376826|2395552980|40     |137.9  |150
sam2_R2.fq.gz|FASTQ |DNA |17376826|2396372076|40     |137.9  |150

I have created the Novoplasty config file [here](https://raw.githubusercontent.com/lakhujanivijay/datasharing/master/config.txt) (I have made individual files for both samples)

While I am getting a good assembly for sample#1 (sam1, stats given below), I am having trouble with sample#2 (sam2) which is no where near the actual / expected size.

**Sample#1 assembly stats**

file                  |format|type|num_seqs|sum_len|min_len|avg_len|max_len
:---------------------|:-----|:---|:-------|:------|:------|:------|:------
sam1.fasta|FASTA |DNA |10      |84907  |149    |8490.7 |58848

**Sample#2 assembly stats**

file                  |format|type|num_seqs|sum_len|min_len|avg_len|max_len
:---------------------|:-----|:---|:-------|:------|:------|:------|:------
sam2.fasta|FASTA |DNA |1       |322    |322    |322.0  |322

**Novoplasty log files link**

sam1 - https://raw.githubusercontent.com/lakhujanivijay/datasharing/master/sam1_novoplast_log_file
sam2 - https://raw.githubusercontent.com/lakhujanivijay/datasharing/master/sam2_novoplast_log_file

Note that I am using the already available/published organelle genome (mitochondrian for _Saccharomyces cerevisiae_ ) as seed file for both the samples, whose stats are given below:

file      |format|type|num_seqs|sum_len|min_len|avg_len|max_len
:---------|:-----|:---|:-------|:------|:------|:------|:------
seed.fasta|FASTA |DNA |1       |84776  |84776  |84776.0|84776

**Comment by ndierckx** [comment]
Hi,

You should send me the extended log from the second sample. Run it again with extended log to 1
And why do you have so much variation on your read length, it works better with uniform readlength, so if its because of post-processing, I would use the raw files
