### ISSUE TITLE
Pooling extractions from different organisms

### ISSUE THREAD

**Issue by ghost** [ndierckx/NOVOPlasty#72]

**Comment by aremkho** [comment]
Good day Nick,
Thanks for maintaining the repository. 
I have a question regarding the old issue of "pooling or not pool".
Do you have any recommendations regarding the performance of NOVOPlasty  when it comes to pooling  several or  dozen  of  independent extractions  from   different individual of the same species in the assembly read pools.
I tested it myself on an Antarctic species and the results are pretty consistent. Meanwhile your expert  recommendations will be highly  appreciated.
Thanks
 Arsalan

**Comment by ndierckx** [comment]
Hi,
Pooling is ok, as long as the read lengths and insert sizes are close to each other.
There will probably be some ambiguous nucleotides because of differences between the individuals.

greets

**Comment by aremkho** [comment]
Fantastic! Many thanks.
