### ISSUE TITLE
Circularized genome output file missing!

### ISSUE THREAD

**Issue by ghost** [ndierckx/NOVOPlasty#74]
Good day Nick,
Thanks for updating and maintaining the repository. Wish you a fruitful 2019.
One of many  mitogenome assembly runs on an Antarctic  insect species ends with producing a full 15K mitogenome and another 5K long contig.
The 15k output is not actually  circularized. Is it because there are two contigs or it might be an another issue with 15k long contig? 
Do you recommend any external tool for circularizing  the long contig?
Thanks in advance
Arsalan

**Comment by ndierckx** [comment]
I could be a repetitive control region, which are very hard to assemble with short reads. Have you checked if the second contig is repetitive?

**Comment by ekarsalan** [comment]
Thanks Nick,
It seems that you are correct. When I use another "relatively closely related species" as reference. The end of the assembly is something like the sequence I have  embedded below. The small contig disappeared totally.However the 15K assembly is still not circularized.
I appreciate your kind advice. I can send you log files incase needed.
Cheers

TTTTACTTACTGAAATGTAGTAGCCAGTTTAGGTTCTATTGTGTCTGTGATTTCTGTYATATTTTTTTTATTTATTATTTGAGAAGCTTTTGTCAGGCATCGGCCAGCTTTGTCGAGGAATCACTTGTCTTCTTCTTTGGAAATAATACACTCGTTCCCGCCGTTAAACCATAGATATTCTTCTATTCCCGTTATTAGAAATAAGTTATATATAAGTGTTTTGCATTAGAAATTTTGATTTTCTAGGACGTAATTAAAAATTATGATATATAGCGAGTATACTTACCTTATTTATTGGTTACTGACTTCYTGAGAGAGAAAAAAAAAAGMAAMCAAGTTTACTTCAGTAGTTTTAAAWTTTTGATTACGAAATTATTATTTTTTTGCTATTTTATTAATAGTCTAGCGWGTGGGGGGGGGGGGGGGGGGG

**Comment by ndierckx** [comment]
For repetitive control regions, it's no point in giving a reference, there is to much variation, even between individuals of the same species. Run it again without the reference with extended log option to 1 and send me that log and the merged file, I will check if it is possible to circularize

**Comment by ekarsalan** [comment]
Thanks Nick! It is very kind of you.
Please find attached the file that you requested.
Highly appreciate your kind time.

[config.txt](https://github.com/ndierckx/NOVOPlasty/files/2778572/config.txt)

[config.txt](https://github.com/ndierckx/NOVOPlasty/files/2778573/config.txt)
[Contigs_1_copepod_noref.fasta.txt](https://github.com/ndierckx/NOVOPlasty/files/2778574/Contigs_1_copepod_noref.fasta.txt)
[log_copepod_noref.txt](https://github.com/ndierckx/NOVOPlasty/files/2778575/log_copepod_noref.txt)
[log_extended_copepod_noref.txt](https://github.com/ndierckx/NOVOPlasty/files/2778576/log_extended_copepod_noref.txt)
