### ISSUE TITLE
Post-Assembly

### ISSUE THREAD

**Issue by nsmt89** [ndierckx/NOVOPlasty#75]
Hi,
I am very new to genomic assembly world. I did follow your instructions on how to execute novoplasty script. Am I supposed to get circularized output file? Because I did not get it after finished assembly. I am trying to assemble plant chloroplast genome. I am not even sure whether I did it correctly. Could you assist me? Here are my config.txt and output files:
[config.txt](https://github.com/ndierckx/NOVOPlasty/files/2849980/config.txt)
[log_C_elliptica.txt](https://github.com/ndierckx/NOVOPlasty/files/2849982/log_C_elliptica.txt)
[log_extended_C_elliptica.txt](https://github.com/ndierckx/NOVOPlasty/files/2849986/log_extended_C_elliptica.txt)

output files:

**Comment by ndierckx** [comment]
Hi,

You put a way too low genome range for chloroplast assembly. I f you have no idea, use the value mentioned in the config file description. You are also only using half the coverage because you lack the memory, but that should not be a problem.

**Comment by nsmt89** [comment]
Hi,
Thanks for fast reply. I did change the genome range and get these output:
[log_C_elliptica.txt](https://github.com/ndierckx/NOVOPlasty/files/2850042/log_C_elliptica.txt)
[log_extended_C_elliptica.txt](https://github.com/ndierckx/NOVOPlasty/files/2850043/log_extended_C_elliptica.txt)
[Merged_contigs_C_elliptica.txt](https://github.com/ndierckx/NOVOPlasty/files/2850044/Merged_contigs_C_elliptica.txt)
how can I know if I can circularized my data or not?

**Comment by ndierckx** [comment]
Seems you have some low coverage regions, would be best to use the complete dataset, can't you run it on server with more memory, probably need something between 25-30 GB of RAM

**Comment by nsmt89** [comment]
My current pc is 15.6 GB, if I manage to find 25-30 GB RAM pc do I still need to set for max memory usage? I tried up to 15 GB and it took few hours to finish and it still haven't output circularized output.

**Comment by ndierckx** [comment]
yeah you can't use all the memory of your laptop, it would get stuck...
still better to use the max memory option, but could be there will still be no coverage in those regions...

**Comment by nsmt89** [comment]
I tried lowered the K-mer value and manage to get output uncircularized output with 
[log_Test_elliptica.txt](https://github.com/ndierckx/NOVOPlasty/files/2853955/log_Test_elliptica.txt)

is it possible to get such output? what is your suggestion for me to complete the circularization of my dataset if there is no coverage in those region?

**Comment by ndierckx** [comment]
Try with different seeds of reference chloroplast. You can get the contigs before and after the gap. But if there is no data you can circularize completely of course., just try to run on a server to be sure

**Comment by ndierckx** [comment]
*can not circularize.

**Comment by nsmt89** [comment]
Hi again,
I did tried with so many reference and seed, and I did not able to get circularized data. I got new sample recently and run NOVOPlasty script and did get forward and reverse read without pair. What does it mean? 
[log_C_longicauda.txt](https://github.com/ndierckx/NOVOPlasty/files/3046272/log_C_longicauda.txt)

**Comment by ndierckx** [comment]
It means there were no pair reads found for many reads, which could indicate a problem with data files
Could be caused by the read ids or does the forward and reverse files have different sizes?
