### ISSUE TITLE
Issue with output files

### ISSUE THREAD

**Issue by ycuenot** [ndierckx/NOVOPlasty#76]
Hello,

I am using NOVOPlasty to assemble mitochondrial genomes. For most of my samples everything is fine with one circularized assembly output. However, for some of the samples, I get one circularized assembly, one contig_1 (with the sequences of the different contigs of the sample) and option1 and option2 output files. I taught that option 1 and option 2 were two ways of the assembly and the circularized was one of the two options. I aligned the circularized with option1 and option2. Option1 and 2 are similar expected few nucleotide but circularized is really different of option1 or option2. Can you explain what these option files are? What file is better to use for downstream analysis?
Thank you in advance,
Yves

**Comment by ndierckx** [comment]
Hi,

Could you send me the log file? Normally there should not be a circularized and options together, I am guessing the circularized is incorrect and contains the repetitive control region.

**Comment by 29503079** [comment]
Hello，
Using NOVOPlasty to assemble plant-Mito,finally, I get 20 different options. Can you give me some advice on how to choose a option for the subsequent analysis. Thank you !

**Comment by ndierckx** [comment]
Hi,

Plant mitochondria are very complex with many chloroplast duplications and can differ between samples, so not easy to assemble with short reads. You can probably exclude most options by annotating them, see for which all the genes are present. Or maybe some options are too short in length....

**Comment by 29503079** [comment]
Thank you very much. 
I have another question what the NOVOPlasty is based on giving the option1 ,option2......

**Comment by ndierckx** [comment]
When the assembly is split up in different contigs, it will generate paths that circularize the genome. During the assembly when a contig terminates and splits in multiple options, it will remember the path. So all those options are circularized assemblies, but most are not correct of course..

**Comment by ycuenot** [comment]
Hello,

Excuse me to answer you so late, I was in holliday. I resolved my problem, it was a mistake of me.
I have a new issue and I do not know where it come from. I am using an external cluster and I do not know if the problem come form Novoplasty or the cluster. It is during the building Hash table. I send you the slurm out with the error message.
Can you tell me if it is a cluster problem because each work I send with all my samples I get the same problem.
Thank you in advance,
Yves Cuenot

March 4, 2019 4:19:00 AM CET Nicolas Dierckxsens <notifications@github.com> wrote:
Hi,
Could you send me the log file? Normally there should not be a circularized and options together, I am guessing the circularized is incorrect and contains the repetitive control region.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ndierckx/NOVOPlasty","title":"ndierckx/NOVOPlasty","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ndierckx/NOVOPlasty"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ndierckx in #76: Hi,\r\n\r\nCould you send me the log file? Normally there should not be a circularized and options together, I am guessing the circularized is incorrect and contains the repetitive control region."}],"action":{"name":"View Issue","url":"https://github.com/ndierckx/NOVOPlasty/issues/76#issuecomment-469104743"}}}[{"@context": "http://schema.org","@type": "EmailMessage","potentialAction": {"@type": "ViewAction","target": "https://github.com/ndierckx/NOVOPlasty/issues/76#issuecomment-469104743","url": "https://github.com/ndierckx/NOVOPlasty/issues/76#issuecomment-469104743","name": "View Issue"},"description": "View this Issue on GitHub","publisher": {"@type": "Organization","name": "GitHub","url": "https://github.com"}}]

Yves Cuenot - Lab technician
Murienne group - DEEP team - EDB laboratory
4R1 building - Office: 140
Paul Sabatier University
118 route de Narbonne
F-31062 Toulouse cedex 9
Phone: +335.61.55.86.78


-----------------------------------------------
NOVOPlasty: The Organelle Assembler
Version 2.7.2
Author: Nicolas Dierckxsens, (c) 2015-2018
-----------------------------------------------


Input parameters from the configuration file:   *** Verify if everything is correct ***

Project:
-----------------------
Project name          = Vel-CHY17-12
Type                  = mito
Genome range          = 12000-22000
K-mer                 = 39
Max memory            = 
Extended log          = 1
Save assembled reads  = yes
Seed Input            = Veliidae.fasta
Reference sequence    = 
Variance detection    = no
Heteroplasmy          = 
HP exclude list       = 
Chloroplast sequence  = 

Dataset 1:
-----------------------
Read Length           = 151
Insert size           = 452
Platform              = illumina
Single/Paired         = PE
Combined reads        = 
Forward reads         = Vel-CHY17-12_AGTTCAGG-TCTGTTGG-AH2MYYBBXY_L001_R1.fastq.gz
Reverse reads         = Vel-CHY17-12_AGTTCAGG-TCTGTTGG-AH2MYYBBXY_L001_R2.fastq.gz

Optional:
-----------------------
Insert size auto      = yes
Insert range          = 1.8
Insert range strict   = 1.3
Use Quality Scores    = no


Reading Input......OK

Building Hash Table.../var/spool/slurm/d/job4597983/slurm_script: line 6: 10289 Killed                  NOVOPlasty.pl -c config.txt
slurmstepd: error: Detected 2 oom-kill event(s) in step 4597983.batch cgroup.

**Comment by ndierckx** [comment]
Never saw this problem, but it is coming from the server. You need to ask why the server kills the process
Probably memory problem, or maybe you need to allocate enough memory before you run a job...
