### ISSUE TITLE
useless "Genome range" setting?

### ISSUE THREAD

**Issue by moveAFs** [ndierckx/NOVOPlasty#77]
sometimes I want the assembler only output a assembly with length within some range, so I set this in config file with "Genome range = lowerbound-upperbound". but from the stdout status, I can see the program have been assembled out of that range. 

no temporary output assembly, no option for controlling the program to stop, relevant functions is really needed under some scenario.

**Comment by ndierckx** [comment]
It is not useless, it's needed to know when to circularize the assembly. I don't think you can stop any assembler at any given point...
