### ISSUE TITLE
more reads or longer reads?

### ISSUE THREAD

**Issue by ekarsalan** [ndierckx/NOVOPlasty#78]
Dear Nick,
Thank you for maintaining and updating the repository.
I have a very general question about NOVOplasty.
Based on your experience with the pipeline, do you recommend users to use more random shotgun reads  (e.g. PEX150) or alternatively using less but longer shotgun reads (e.g.  PE 2x250)?
Thanks in advance
Arsalan

**Comment by ndierckx** [comment]
Once you have a coverage above 60x, higher would only help for heteroplasmy detection or resolving SNR regions a bit better. So definitely 250, that could make a big difference (but not grantee). Don't go for 300 bp reads, they seem to be full of errors...

**Comment by ekarsalan** [comment]
Thanks, Nick for your kind email.
Regarding insert size in library prep, do you have any recommendations? The sequencing facility usually asks if we have any preferable insert size?
Cheers

**Comment by ndierckx** [comment]
Usually they do an insert size of 500, but 800 or 1000 would be even better, but they are harder to prepare. If they can make larger insert sizes with an ok distribution, I would go for 800 or 1000. But don't go below 500.
