### ISSUE TITLE
Selecting the correct orientation

### ISSUE THREAD

**Issue by o-william-white** [ndierckx/NOVOPlasty#79]
Hello, 

I just wanted to clarify something you mentioned in the readme file related to chloroplast assembly.

I have two out files, Option_1 and Option_2 that are equal in length, which only differ presumably in the orientation of the three contigs that were identified.

The readme suggests mapping the assemblies to a chloroplast reference and using the graphics option on blast to show which orientation is correct. Apologies this is the first time I have attempted to assemble such a dataset, but I was just wondering if you could provide some more detail on how to do this? Or point me in the direction of somewhere I can find out more about it.

I have searched the issues raised but I am sorry if this has already been discussed and I have missed it.

Kind regards 
Ollie

**Comment by ndierckx** [comment]
Hi,

Try to do the assembly again but give the closest reference genome you have. It will use that  reference to resolve the orientation of the inverted repeat. If it didn't work, come back to me...

**Comment by o-william-white** [comment]
Hello, 

Thanks for the message. I am trying to assemble the chloroplast genome for a species in the Malvales, and I have trialed reference genome sequences of Gossypium hirsuitum and Theobroma cacao which are both closely related, but both give a similar result. For the seed I have been using an rbcL marker from the same genus.

Best wishes
Ollie

**Comment by ndierckx** [comment]
blast them both to the closest reference and check in which one the orientation of the region between the inverted repeats is not flipped

**Comment by o-william-white** [comment]
Hello again, 

Thanks for the reply. I can blast them both to the reference no problem but I do not know how to check the orientation of the reads? Can you provide me with a little more detail please? 

Best wishes
Ollie

**Comment by ndierckx** [comment]
BLAST both options online against the closest reference and then press graphics. Maybe take a screenshot of both alignments and then I can show you

**Comment by o-william-white** [comment]
Hi Nicolas,

I have screen shots of the two blast searches below, hopefully I am using
the correct blast search options and this makes some sense

Best wishes
Ollie

Option 1
[image: image.png]

Option 2
[image: image.png]

**Comment by ndierckx** [comment]
Hi,

I can't see the images, maybe mail them

**Comment by o-william-white** [comment]
Option 1
![image (1)](https://user-images.githubusercontent.com/10031094/55945836-778ffc80-5c43-11e9-9e2e-eed848458c68.png)

Option 2
![image (2)](https://user-images.githubusercontent.com/10031094/55945892-8c6c9000-5c43-11e9-8e15-c99f92e798e5.png)

Apologies, I replied by email before and it didn't seem to like the images, hopefully this works

**Comment by ndierckx** [comment]
Thanks can see the pics now, but could show the whole genome. Those pics only show a region. You should extend the blue frame completely till both ends

**Comment by o-william-white** [comment]
Hi Nicholas, 

Hope these images are ok, I had to zoom out slightly so the whole plot could be seen. Let me know if you would like greater detail.

Best wishes
Ollie

Option 1
![image](https://user-images.githubusercontent.com/10031094/56151209-acd07d80-5fa8-11e9-8c7d-9a1e6463175a.png)

Option 2
![image](https://user-images.githubusercontent.com/10031094/56151345-ee612880-5fa8-11e9-9484-2b865c29b674.png)

**Comment by ndierckx** [comment]
You can see option 2 is the correct one. The region between the inverted repeats has the wrong orientation in option 1. Can see at the bottom of each pic

**Comment by o-william-white** [comment]
Hi Nicholas, 

Ok I understand now, thank you for your patience with this

Best wishes
Ollie

**Comment by Silverfoxcome** [comment]
The region between the inverted repeats is, aprox, the region between 105 K and 120 K right? (Sorry for the question)

**Comment by ndierckx** [comment]
Yes around there

**Comment by Silverfoxcome** [comment]
Hi! I re-ran novoplasty with the new version (3.3) and with Max memory = 20 (Average organelle coverage : 784) (is this ok, or is this too much coverage of the chloroplast? )

This gave me three contigs 

> Contig 01 : 100782 bp
> Contig 02 :   40719 bp
> Contig 03 :   40994 bp

And with this, the program gave me two assembly options:

> OPTION 1
> -------------------
> Contig Arrangement : 01+02
> Assembly length    : 140459 bp

and 

> OPTION 2
> -------------------
> Contig Arrangement : 01+03
> Assembly length    : 140458 bp

I blasted them against the chloroplast reference genome. I took screenshot of the alignment of Option 1:
[https://ibb.co/DWjc8Vf](url)

And a screenshot of the alignment of Option 2:
[https://ibb.co/BL1VkCf](url)

I think both are very similar, but I'm very new to this topic so perhaps I'm missing something. 

Thanks a lot for all you help :)

**Comment by ndierckx** [comment]
Seems similar indeed :)
You used a reference in your config file? (if so it resolved your inverted repeat automatically)

Maybe blast the two against each other, see where the difference is

**Comment by Silverfoxcome** [comment]
Hi Nicolas!
Really, thank you for all your help, sorry to bother you so much.
Yeah! I used the reference chloroplast genome of Zea mays B73v4. I also used the latest version (Novoplasty 3.3) and ran the program with Max memory = 20 (Average organelle coverage : 784) (is this ok, or is this too much coverage of the chloroplast? ). With this, I got two assembly options instead of five :D 
I blasted the option 1 (as query) against option 2 (as subject). The dotplot I got was:
![image](https://user-images.githubusercontent.com/11965123/61018582-ebce5f00-a35c-11e9-9a00-4faf228e56a1.png)

And the screenshot of the alignment:
![image](https://user-images.githubusercontent.com/11965123/61018934-094ff880-a35e-11e9-99f6-7fb0a2fd8303.png)

But I still have trouble seeing which should I take as the better assembly. I was annotating them in CpGavas to see the completeness but the latest version seems to have some troubles with that * in the last base pairs

`GGGGG*CCAAGTCAGGTTAGATCTATATCTTTAATGCCTATAAGACAGTCA`

Could I erase the * and the following base pairs? 

Thank you for your kind help in advance and sorry for all the questions :)

**Comment by ndierckx** [comment]
Hi,

Sorry forgot to answer, seems there is almost no difference between two?
You could check by aligning reads against the two assemblies and check what aligns best in the region of the difference
I can't see from the picture but if it's just one or two basepares, it doesn't matter that much i guess, could be heteroplasmy for example. You can remove the star, check manual on github, there is more info on that
