### ISSUE TITLE
About seed retrieval

### ISSUE THREAD

**Issue by CheWeiHsu** [ndierckx/NOVOPlasty#8]
Hi Nicolas,
I'm running NOVOPlasty with the following config:

Project name         = NIppon_chloro
Insert size          = 400
Insert size aut      = yes
Read Length          = 300
Type                 = chloro
Genome Range         = 120000-200000
K-mer                = 73
Insert Range         = 1.5
Insert Range strict  = 1.2
Single/Paired        = PE
Coverage Cut off     = 250
Extended log         = 1
Combined reads       = 
Forward reads        = /home/willy/file/DeNovoAssembly/fastq/NIppon_1_pairedout.fastq
Reverse reads        = /home/willy/file/DeNovoAssembly/fastq/NIppon_2_pairedout.fastq
Seed Input           = /home/willy/file/DeNovoAssembly/fastq/Nippon_seed.fasta

**And then it stuck at Retrieve Seed... for over 24 hr.**
I am running NOVOPlasty on a Intel i5 machine containing 4 cores and 16GB of RAM.
My data set size is 6 GB in total (Illumina Miseq 300bp PE), the ratio of chloroplast reads and mitochondrion reads is 3.5% and 1.8 % respectively and the estimated coverage of chloroplast and mitochondrion is 500X and 120X respectively.

Is there anything that I can do to speed up my assembly?
Should I subsample the dataset or just change some parameter in the config file?

Thank you!

Willy

**Comment by ndierckx** [comment]
Hi,
Thanks for the comment, older updates caused seed retrieval problems with some users, so I will make a new update today to fix it! You could already try to lower the K-mer to 43, could help to the bug for now.
I saw you lowered the coverage cut-off but that's not necessary, that's good if you want to speed the assembly, but this is a different problem.
And do you have Illumina reads? Didn't knew they had already 300 bp long reads

**Comment by ndierckx** [comment]
Hi,
Found the bug, was too hasty in a previous update, it is fixed now, so download version 2.3 and let me know if there is still a problem!

Greets

**Comment by CheWeiHsu** [comment]
Thank you for your reply! It helps! 
P.S You can get 300 bp long PE reads from illumina Miseq ~

**Comment by ndierckx** [comment]
The update was not complete so 2.3.2 should have fixed the seed retrieval problem completely

**Comment by ulaszewski** [comment]
@ndierckx In my case I use Illumina 110 bp reads, and try to assemble a mitochondrial genome. 
After Building Hash Table, the Seed retrival goes for ages, this is the problem #1. The problem #2 is that some fasta seeds (downloaded from NCBI) does not work. I'm using NOVOPlasty v 2.4 on Ubuntu.

**Comment by ndierckx** [comment]
Hi,

Are you using whole genome data and do you have sufficient coverage?
And what is the error with seed sequences that don't work?

**Comment by fangdm** [comment]
Hi Nicolas,
I'm running the newest NOVOPlasty (2.6.3), with 3 GB data in total (Illumina PE 100bp) of WGS, and using rbcL gene of Arabidopsis thaliana as a seed, but only 4.8 Kb in final assembly. And i try a second seed (matK, ~7.8 Kb) or complete chloroplast genome (0 Kb, why???), and there is nothing wrong with that. 
I also subsample 5 and 10 Gb from raw data, 5.5 and 13.5 Kb assembly results can be achieved with the rbcL seed.
Is there anything that I can do to improve my assembly? Should i increase the sequencing data or just change some parameter in the config file?

Thank you!

The config as following:
Insert size          = 180
Insert size aut      = yes
Read Length          = 100
Type                 = chloro
Genome Range         = 120000-200000
K-mer                = 31
Insert Range         = 1.6
Insert Range strict  = 1.2
Single/Paired        = PE
Max memory
Extended log         = 0
Save assembled reads = yes
Combined reads       =
Forward reads        = Xxx_1.fq.gz
Reverse reads        = Xxx_2.fq.gz
Seed Input           = At_rbcL.fa
Reference            =
Chloroplast sequence =

**Comment by ndierckx** [comment]
Hi,
I can tell you the problem if you send me the extended log (put option to 1)
As for the seed, it could be that the start of the seed has a duplicated region in the mitochondrial genome.
Therefore I always use a RuBP sequence as seed.
And if you have more raw data, use all of it.. 
You can always use the max memory option to automatically subsample

**Comment by fangdm** [comment]
Thank you very much.
Chloroplast assembly with 3Gb data in total while run NOVOplasty, 
the three files  in attachment: the input config file, running process file and the result file. 




dongmingfang
 
From: Nicolas Dierckxsens
Date: 2017-11-29 20:58
To: ndierckx/NOVOPlasty
CC: fangdm; Comment
Subject: Re: [ndierckx/NOVOPlasty] About seed retrieval (#8)
Hi,
I can tell you the problem if you send me the extended log (put option to 1)
As for the seed, it could be that the start of the seed has a duplicated region in the mitochondrial genome.
Therefore I always use a RuBP sequence as seed.
And if you have more raw data, use all of it..
You can always use the max memory option to automatically subsample

**Comment by ndierckx** [comment]
There are no files in the mail, you can drop in the textbox on the github site or you mail them directly to me

**Comment by fangdm** [comment]
[config.txt](https://github.com/ndierckx/NOVOPlasty/files/1513964/config.txt)
[contigs_tmp_SG-WTS-WGS.txt](https://github.com/ndierckx/NOVOPlasty/files/1513965/contigs_tmp_SG-WTS-WGS.txt)
[log_SG-WTS-WGS.txt](https://github.com/ndierckx/NOVOPlasty/files/1513966/log_SG-WTS-WGS.txt)

OK, thanks and how about this?

**Comment by ndierckx** [comment]
That works but still need the extended log not just the log :)
You have the option in the config on 0, switch it to 1 and run it again
And are you sure the insert size is 180?

**Comment by fangdm** [comment]
OK. i will run it with all the raw data now, and reset the following parameters :
Extended log = 1
Max memory = 80
It may take some time to finish,  i'll send it to you later. 
Thank you.

**Comment by ndierckx** [comment]
Ok, but 80 is not necessary :) 20 should be more then enough
I saw you deleted the "=" at max memory option, so make sure you put it back and align correctly compared to the other parameters

**Comment by fangdm** [comment]
[config.txt](https://github.com/ndierckx/NOVOPlasty/files/1514018/config.txt)
[SG-WTS-WGS.sort.mq60.IS.pdf](https://github.com/ndierckx/NOVOPlasty/files/1514060/SG-WTS-WGS.sort.mq60.IS.pdf)

OK. Config file Settings as above, and it is running well now.  
The experiment library has a size of ~180bp, but only ~140bp while mapping to assembly with MITOBIM. Must it be accurate? and other question?
Thank you.

**Comment by ndierckx** [comment]
no that's fine, will fine tune automatically

**Comment by fangdm** [comment]
Hi, i try to set Max memory for 20, 50 and 80, the corresponding results (log_* and log_extended_*) are shown in the attachment. 
Then there is anything to tell me that I can do to improve my assembly.

Thank you.

[log_extended_SG-WTS-WGS_Max_memory_20.txt](https://github.com/ndierckx/NOVOPlasty/files/1516201/log_extended_SG-WTS-WGS_Max_memory_20.txt)
[log_SG-WTS-WGS_Max_memory_20.txt](https://github.com/ndierckx/NOVOPlasty/files/1516202/log_SG-WTS-WGS_Max_memory_20.txt)
[log_extended_SG-WTS-WGS_Max_memory_50.txt](https://github.com/ndierckx/NOVOPlasty/files/1516204/log_extended_SG-WTS-WGS_Max_memory_50.txt)
[log_SG-WTS-WGS_Max_memory_50.txt](https://github.com/ndierckx/NOVOPlasty/files/1516205/log_SG-WTS-WGS_Max_memory_50.txt)
[log_extended_SG-WTS-WGS_Max_memory_80.txt](https://github.com/ndierckx/NOVOPlasty/files/1516206/log_extended_SG-WTS-WGS_Max_memory_80.txt)
[log_SG-WTS-WGS_Max_memory_80.txt](https://github.com/ndierckx/NOVOPlasty/files/1516207/log_SG-WTS-WGS_Max_memory_80.txt)

**Comment by ndierckx** [comment]
It looks like you don't have many chloroplast reads in your dataset, this is very weird...
What kind of data is it? And did you align a lot of reads when you used MITObim?

**Comment by fangdm** [comment]
The sample is a holoparasitic plant. Is the case, it has less the chloroplast reads: We use the data from a random sample of 10,000 reads, then mapping to chloroplast database with blastn, only 0.0038 mapping ratio as result.

**Comment by ndierckx** [comment]
Maybe try with the complete dataset, if you have enough memory...
And put kmer to 23 and insert range to 1,8

**Comment by fangdm** [comment]
Alright, I'll give it a try.
For our current situation, we have 18 parasitic plants, base on different random subsample (3g, 5g and 10g). Using the result “Contigs_1_*.fasta” file of NOVOPlasty for statistics, which may contain multiple sequences, half failed to assembly. 
Compared the mapping ratio with chloroplast database, there is not very strong correlation. We also attempts to assemble only with the reads that mapping to chloroplasty database, but fail...
[Result of NOVOPlasty.xlsx](https://github.com/ndierckx/NOVOPlasty/files/1516859/Result.of.NOVOPlasty.xlsx)


Thank you very much.

**Comment by ndierckx** [comment]
I just wonder if the mitochondrial presence is also as low as the chloroplast.
If the mitochondria are more abundant then the chloroplasts it could be that NOVOPlasty will start to assemble the mitochondria since it expects a higher rate of chloroplast sequences

**Comment by fangdm** [comment]
Hi,
For the sample SG-WTS-WGS, I try the parameter “Max memory” for setting up 200, and the assembly results show that the size has been increasing, but it has reached the maximum memory of our compute nodes. For this low level of chloroplast in plants, what can I do aside from “Max memory” with the newest NOVOPlasty?

**Comment by ndierckx** [comment]
besides the kmer to 23 not much, if there is no data, it's not possible to assemble
Some assemblers will just cope the reference when the coverage is too low, but that's not accurate of course..
You have no bigger nodes available? You could also rent one online..
