### ISSUE TITLE
How to use the batch mode in version 3

### ISSUE THREAD

**Issue by edgardomortiz** [ndierckx/NOVOPlasty#81]

**Comment by ndierckx** [comment]
Hi,

I am writing the wiki today, will make a page about that, so should be online by tomorrow

**Comment by edgardomortiz** [comment]
Cool, thanks!

**Comment by ndierckx** [comment]
I explained the batch function in the wiki tab. Let me know if it is clear enough

**Comment by edgardomortiz** [comment]
All clear, thanks.
