### ISSUE TITLE
Add a test data set

### ISSUE THREAD

**Issue by nterhoeven** [ndierckx/NOVOPlasty#82]
Hi @ndierckx 

we are currently working on a benchmarking of chloroplast assembly tools (see https://github.com/chloroExtractorTeam/benchmark). In this context, I installed NOVOPlasty and noticed a minor issue.

It would be nice to have a test data set, that can be used to check if the installation was successful and NOVOPlasty is working as intended.

Best,

Niklas

**Comment by ndierckx** [comment]
Hi,

I could add a dataset, I will have a look which one I can upload. 

I didn't add one because NOVOPlasty doesn't need an installation, you just need to fill in the config file and run the script

**Comment by nterhoeven** [comment]
That would be great - thanks a lot :+1:

**Comment by ndierckx** [comment]
Hi, I added a test dataset for chloroplast assembly, it is a public dataset of rice. 
Found a bug in the 3.0 version while running the test dataset, so updated it to 3.1
