### ISSUE TITLE
Config file several reads

### ISSUE THREAD

**Issue by SIlviaHinojosa** [ndierckx/NOVOPlasty#83]
Hi

I was wondering how I can use several reads in the config file, do I merge all the r1 and r2 or can I put them comma separated.

Cheers,
Silvia

**Comment by ndierckx** [comment]
Hi, 

Do you mean several datasets of one sample?

**Comment by SIlviaHinojosa** [comment]
Hi

Yes, several datasets of one sample

**Comment by ndierckx** [comment]
Sorry forgot to answer, probably way too late, but you can only use one dataset. Merging is possible when the read lengths are the same
