### ISSUE TITLE
assembledQuantifier follows nothing in regex

### ISSUE THREAD

**Issue by siknkrt** [ndierckx/NOVOPlasty#85]
Hi, I am trying to assemble Geraniaceae chloroplast genome using rbcL as a seed and _Geranium incanum_ plastid genome (accession No. KT760575.1)  as reference. But the following message appeared and after that the NOVOplasty stop. 
[log_seed_rbcL.txt](https://github.com/ndierckx/NOVOPlasty/files/3225944/log_seed_rbcL.txt)

Many repeat sequences might be included in my input data.
Could you give me some advice?

Best regards

**Comment by ndierckx** [comment]
Hi,

That's a bug. Could you redownload the NOVOPlasty file and rerun?

If the problem is still there let me know!

**Comment by siknkrt** [comment]
Hi,

Thank you for speedy response. I redownloaded the NOVOPlasty file and the run succeeded. Thank you very much.

Best wishes,

**Comment by ndierckx** [comment]
No problem

I would recommend to look at the 'Interpretation and post-processing' section in the readme, as you may have some * in the fasta output

**Comment by siknkrt** [comment]
Thanks. I will check the readme and interpretations.
