### ISSUE TITLE
Paired has to be 'SE' or 'PE', please check the configuration file!

### ISSUE THREAD

**Issue by hgreenia** [ndierckx/NOVOPlasty#86]
Hello, 
I am attempting to run the homo sapiens test files with NOVOPlasty thru ubuntu linux, and another student and I are receiving this error. The program will process our code and spit out the config file , although not showing any of our entries for the config file (with the exception of showing the platform and insert size auto options) . bit will spit out the error above. Do you have any suggestions as to how we can resolve this? 

Thank you!
Haley

**Comment by ndierckx** [comment]
Hi,

It seems to be a problem with your config file, you must have changed it in a way it got corrupted.
You should only change the parameters. Just redownload the config file again
