### ISSUE TITLE
Is there a single-end read workaround?

### ISSUE THREAD

**Issue by srgill2** [ndierckx/NOVOPlasty#88]

**Comment by ndierckx** [comment]
there is SE option, just forgot to change it in the config file, put SE in stead of PE
Although it won't work as good as a PE library

**Comment by srgill2** [comment]
Ah, thank you. Any suggestions for optimizing it for SE and short reads? (~80bp average)

**Comment by ndierckx** [comment]
use a short kmer 23
For the rest you can't do that much

**Comment by srgill2** [comment]
Thanks, I've tried that and switching around other parameters without much luck. Is there any danger in dropping the kmer below 23?

**Comment by ndierckx** [comment]
Can go until 20 maybe, but if the dataset is not good enough it probably won't help
