### ISSUE TITLE
Input reads have and incorrect file format

### ISSUE THREAD

**Issue by Silverfoxcome** [ndierckx/NOVOPlasty#89]
Hi!! I'm using NOVOPlasty to assemble the chloroplast genome of purple maize :) 
I run this config file:

Project:
-----------------------
Project name = test_chloro
Type = chloro
Genome Range = 120000-180000
K-mer = 39
Max memory = 
Extended log = yes
Save assembled reads  = no
Seed Input = /home/maiz/Documentos/mac/cp_zm_sp/Seed_RUBP.fasta
Reference sequence    = /home/maiz/Documentos/mac/cp_zm_sp/cp_ref.fasta
Variance detection    = no
Chloroplast sequence  =

Dataset 1:
-----------------------

Read Length           = 151
Insert size           = 600
Platform              = illumina
Single/Paired         = PE
Combined reads        = 
Forward reads         = /home/maiz/Documentos/mac/cp_zm_sp/cp_reads/cp_trim_1P.sc.fastq
Reverse reads         = /home/maiz/Documentos/mac/cp_zm_sp/cp_reads/cp_trim_2P.sc.fastq

**Optional:**

-----------------------
Insert size auto      = yes
Insert Range          = 1.9
Insert Range strict   = 1.3
Use Quality Scores    =

But the program told me this:

> Reading Input...
> 
> THE INPUT READS HAVE AN INCORRECT FILE FORMAT!
> PLEASE SEND ME THE ID STRUCTURE!

The ID's of my reads are like this:

**cp_trim_1P.sc.fastq**
@ST-E00130:738:HKNNFCCXY:5:1203:28290:58339
GTCGATTTAGTTCGGGGAAAGGGGAAGGGGAAAAAAATTCTATGAACCTTTCCTTTTTTCGTTAAGTTCAAGTCTGGCGAGAATAATATTCTACAACTAACAACTCATTTATTTTGAGACCGACCCACTTCCTATCTAGAATTTTTTTTAC
+
AAAFFJJJFJJJJJJJJFFFJJJJJJJJJJJJJJFFJJJJJFJJJJJJJJFJJJJJJJJAFFJJFJJJJJJJJJJJJJJJJJFJJJJFJJFFJFJJJJJJJAJJJJJJJFFJFJJFAFFAFJJJJAJJJJJJJJJJJJJJJJFJFJJJJJA

and for the pair:

**cp_trim_2P.sc.fastq**
@ST-E00130:738:HKNNFCCXY:2:2102:12936:27099
ACTAGTAAAAAAAATTCTAGATAGGAAGTGGGTCGGTCTCAAAATAAATGAGTTGTTAGTTGTAGAATATTATTCTCGCCAGACTTGAACTTAACGAAAAAAGGAAAGGTTCATAGAATTTTTTTCCCCTTCCCCTTTCCCCGAACTAAAT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJFJFJJJJJJJJJJJJJJJJJFAJJJJJFJJJJJJJJFJJJJJJFJJJJJJJFJJJJJJJJJJJJJJJJJAAFFJFJJJJJJJJFFFJJJJJJJJJJJJJJJJJJJJJJJJFAJFJJJJJJJ<<A<

Can anyone help me please? where is the mistake? 
Thanks in advance :)

**Comment by ndierckx** [comment]
Hi,
Your read ids don't indicate which are the forward and reverse reads, which is unusual
Did you used any pre-processing software that alter the read ids, because they seem incomplete?
If you did use some trimming software, just use the raw dataset....

**Comment by Silverfoxcome** [comment]
You are right! in the raw dataset, the names of the reads are:

> zcat ZM1_R1.fastq.gz | head
> @ST-E00130:738:HKNNFCCXY:1:1101:17756:1344 **1**:N:0:NAATGCGC+NGGCTATA

> zcat ZM1_R2.fastq.gz | head
> @ST-E00130:738:HKNNFCCXY:1:1101:17756:1344 **2**:N:0:NAATGCGC+NGGCTATA

But in the dataset I used, the names of the reads are:

> cp_trim_1P.sc.fastq
> @ST-E00130:738:HKNNFCCXY:5:1203:28290:58339

> cp_trim_2P.sc.fastq
> @ST-E00130:738:HKNNFCCXY:2:2102:12936:27099

I only used Trimomatic and Seqtk, one of those programs should have caused this...

thanks, i'll look for what happened :)
