### ISSUE TITLE
About Insert Range & Insert Range Strict

### ISSUE THREAD

**Issue by CheWeiHsu** [ndierckx/NOVOPlasty#9]
Hi Nicolas,

I wonder if you can explain more about the parameters: Insert Range & Insert Range Strict

My understanding is that if you set the Insert size to 500 bp, Insert Range to 1.5, then NOVOPlasty will consider insert size between 250~750bp (500 x (1.5 - 1.0) = 250, minimum = 500 - 250 = 250, maximum = 500 + 250 = 750 ) , is that correct? 

As for Insert Range Strict , I don't even have a clue ... what does 1.2 (default) mean? could you please give an example?

Thanks a lot!

Willy

**Comment by ndierckx** [comment]
Hi,
Yes the insert range defines the insert size, slightly different formula but something around that.
Insert range strict will be used for problematic regions like repeats (only when there is enough coverage) to filter out reads who have statistically more chance to be incorrect.
