### ISSUE TITLE
help for detecting heteroplasmy

### ISSUE THREAD

**Issue by Mirror1211** [ndierckx/NOVOPlasty#90]
Hi everybody,
I'm Eda. Recently, I am going to detect the heteroplasmy within chloroplast genome to investigate wether there is biparental heteroplasmy within my samples. I am really glad to find the NOVOPlasty since it can detect heteroplasmy for chloroplast genome.
However, there is no detailed introductions to this analysis and I always obtained blank result files for heteroplasmy analyses. Could anybody help me for the settings of the configure file???
Thanks a lot!

**Comment by Mirror1211** [comment]
I have already obtained the complete chloroplast genomes assembled by my colleague, and took them as their own reference genome and seed genome, while the results files also were blank.

**Comment by ndierckx** [comment]
Hi, could you send me the log, so I can check if all the parameters are correct. And do you have enough coverage for heteroplasmy detection? I haven't test it much on chloroplast genome but it is more complicated because of the many duplicated regions in the mitochondrial genome

**Comment by Mirror1211** [comment]
The mean coverage of cp genomes ranged from 200 to 7900 X. So, I think the coverage of cp genomes is enough to detece heteroplasmy. I have deleted the log file. I will conduct this analysis this afternoon and upload the log files here. 
Thanks a lot

**Comment by Mirror1211** [comment]
[heter.txt](https://github.com/ndierckx/NOVOPlasty/files/3269147/heter.txt)
This is my configure and logfiles.
[log_test_chloro.txt](https://github.com/ndierckx/NOVOPlasty/files/3269149/log_test_chloro.txt)

**Comment by Mirror1211** [comment]
Reading Input......OK

Scan reference sequence......OK

Building Hash Table......OK

Subsampled fraction: 100.00 %

Retrieve Seed...


However, there was no futher infomation for the next step. I guess there may be some errors in my configure files.

**Comment by Mirror1211** [comment]
[heter.txt](https://github.com/ndierckx/NOVOPlasty/files/3269156/heter.txt)
[log_test_chloro.txt](https://github.com/ndierckx/NOVOPlasty/files/3269157/log_test_chloro.txt)
Here are my configure and log files. Thanks

**Comment by ndierckx** [comment]
Your MAF is way too low, you are looking for heteroplasmy of 0,01%, that is impossible. If you want 1%, put 0,01. I will put an automatic allert in the next version. Try what it gives with 0,01. But i see you have reads of 90bp, that means they are old i guess, so less accurate. So definitely don't go below 0.01

**Comment by Mirror1211** [comment]
Thanks. Actually, I used 0.01 for MAF first. The result files were still blank.

**Comment by Mirror1211** [comment]
Could I know when the next version will be uploaded in gitub????

**Comment by Mirror1211** [comment]
Is there any errors in my configure files except for MAF????

**Comment by ndierckx** [comment]
Send me the log of the 0,01 then

**Comment by Mirror1211** [comment]
OK. I will upload the log of the 0.01 this afternoon.

**Comment by ndierckx** [comment]
ok, and when you did it before, it also got stuck at Seed retrieval?
With a MAF lower than 0.01 that can happen

**Comment by Mirror361025** [comment]
yes, it also got stuck at Seed retrieval.

**Comment by Mirror361025** [comment]
Sorry, our serve is maintaining, so I can not download the logfile.

**Comment by Mirror361025** [comment]
Exactly, I have arond 50 accessions that need to conduct the heteroplasmy detection.

**Comment by ndierckx** [comment]
Hi,

Could you send me the seed file?

**Comment by Mirror361025** [comment]
ok. The serve maintaince will be finished tommorrow. After that, I will upload my seed file.

**Comment by Mirror361025** [comment]
[results.zip](https://github.com/ndierckx/NOVOPlasty/files/3279178/results.zip)
hi, I have analyzed another sample with two different MAF. I obtained the results of heteroplasmy. Here are the all results.

**Comment by Mirror361025** [comment]
I don't know whether the analysis is correct. In addition, the results confused me.

**Comment by ndierckx** [comment]
Did you use the chloroplast assembly as a reference and seed or some online reference?

**Comment by ndierckx** [comment]
Because you have a lot of homoplasmies, so your reference is probably not from that dataset?
if you run again, please use the extended log (set to 1), then I can see when something went wrong.
And you should try a high coverage dataset first

**Comment by ndierckx** [comment]
Ah sorry coverage seems enough.., but results are bit weird indeed, if you send me one dataset, I can also try myself if you want

**Comment by ndierckx** [comment]
But since all heteroplasmy is found in one short region, I would guess there is no heteroplasmy, something surely went wrong in that area

**Comment by Mirror361025** [comment]
yes, I used the assembled chloroplast genome as reference genome. I am sure the chloroplast genome is consistent with the reads I used. I wonder whether I should use the raw reads from the whole-genome resequencing or use the filtered data that only contained chloroplast reads??

**Comment by Mirror361025** [comment]
I wonder whether I can have your email for the upload of raw data???

**Comment by ndierckx** [comment]
nicolasdierckxsens at hotmail dot com

**Comment by Mirror361025** [comment]
Thanks

**Comment by Mirror361025** [comment]
hello, the reads should be the raw whole-genome sequences or the filter data that only contained chloroplast reads??

**Comment by ndierckx** [comment]
How did you filter them? And are the raw files very large?

**Comment by Mirror1211** [comment]
We used related complete control genomes as reference genomes to screen out the cp genomes reads. The raw reads are ～40 G

**Comment by Mirror1211** [comment]
hi, I have deleted some files and compressed them while there is also   8 G data.  I  will send these files in three emails to you. Thanks.

**Comment by ndierckx** [comment]
Hi, Sorry was busy and was on holiday so didn't had the time to try it any further
Are you still interested in heteroplasmy detection?

**Comment by Mirror1211** [comment]
yes. Would you have any suggestions for my analyses???

在2019-07-10 02:54:21，Nicolas Dierckxsensnotifications@github.com写道：

Hi, Sorry was busy and was on holiday so didn't had the time to try it any further
Are you still interested in heteroplasmy detection?

**Comment by ndierckx** [comment]
Did you already have a successful chloroplast assembly?

**Comment by Mirror1211** [comment]
yes. In fact, the cp genome was assembled by my colleague using other software, and I conducted the following phylogenetic analyses.  I think that it is also important for us to test the bioparental interitance by detecting the heteroplasmic sites between different accessions. Fortunatelly, I found your software. The coverage of cp genomes is up to 9065 X and raw reads is around 40G.

在2019-07-15 12:28:12，Nicolas Dierckxsensnotifications@github.com写道：

Did you already have a successful chloroplast assembly?

**Comment by ndierckx** [comment]
Hi, 
Ok as the heteroplasmy function is quite new and I am fixing some problems at the moment, it is better to wait until tomorrow or the day after to run the latest version

I haven't tried many chloroplast sequences, so when you do a run you can send me the results.

At the moment, you can already filter your reads to speed up the heteroplasmy detection:
https://github.com/ndierckx/NOVOPlasty/wiki/Heteroplasmy-detection

Use the filter_read.pl script on your original dataset

**Comment by Mirror1211** [comment]
OK. Thanks.

在2019-07-15 17:10:18，Nicolas Dierckxsensnotifications@github.com写道：

Hi,
Ok as the heteroplasmy function is quite new and I am fixing some problems at the moment, it is better to wait until tomorrow or the day after to run the latest version

I haven't tried many chloroplast sequences, so when you do a run you can send me the results.

At the moment, you can already filter your reads to speed up the heteroplasmy detection:
https://github.com/ndierckx/NOVOPlasty/wiki/Heteroplasmy-detection

Use the filter_read.pl script on your original dataset

**Comment by Mirror1211** [comment]
Hi
I also wanna know whether the genome in the first step for the heteroplasmy detection must be assembled by NOVOPlasty???
could I use a complete genome assembled by other programs ?? Because most of the studied cp genomes have already assembled by my colleague last year.

在2019-07-15 17:10:18，Nicolas Dierckxsensnotifications@github.com写道：

Hi,
Ok as the heteroplasmy function is quite new and I am fixing some problems at the moment, it is better to wait until tomorrow or the day after to run the latest version

I haven't tried many chloroplast sequences, so when you do a run you can send me the results.

At the moment, you can already filter your reads to speed up the heteroplasmy detection:
https://github.com/ndierckx/NOVOPlasty/wiki/Heteroplasmy-detection

Use the filter_read.pl script on your original dataset

**Comment by Mirror1211** [comment]
oh, sorry
Also, the introduction of perl scripts said that no repeatitive sequences should be inclueded in this analysis. Cp genomes have two large repeative copies (also called IRa and IRb) that were reverse and complementary with each other. So should I remove these two sequences and concatenate the remaing sequences as a new whole sequence to conduct this analysis, or should I keep one of the two IR regions?

在2019-07-15 17:10:18，Nicolas Dierckxsensnotifications@github.com写道：

Hi,
Ok as the heteroplasmy function is quite new and I am fixing some problems at the moment, it is better to wait until tomorrow or the day after to run the latest version

I haven't tried many chloroplast sequences, so when you do a run you can send me the results.

At the moment, you can already filter your reads to speed up the heteroplasmy detection:
https://github.com/ndierckx/NOVOPlasty/wiki/Heteroplasmy-detection

Use the filter_read.pl script on your original dataset

**Comment by ndierckx** [comment]
Always better to use a NOVOPlasty assembly, but you can also do it with assembled genome, as long as it is from the same dataset. You can keep the IR, but if they are not identical, there will be false positives in those regions. I am still working on the heteroplasmy model, still needed some debugging, so I will upload a new version tomorrow (best to wait for that one)

**Comment by Mirror1211** [comment]
Thanks a lot!

在2019-07-23 20:33:09，Nicolas Dierckxsensnotifications@github.com写道：

Always better to use a NOVOPlasty assembly, but you can also do it with assembled genome, as long as it is from the same dataset. You can keep the IR, but if they are not identical, there will be false positives in those regions. I am still working on the heteroplasmy model, still needed some debugging, so I will upload a new version tomorrow (best to wait for that one)

**Comment by ndierckx** [comment]
Hi,

Sorry took a bit longer, but the new version is uploaded, should perform better

**Comment by Mirror1211** [comment]
Thanks

在2019-07-31 10:25:58，Nicolas Dierckxsensnotifications@github.com写道：

Hi,

Sorry took a bit longer, but the new version is uploaded, should perform better
