### ISSUE TITLE
Running time 

### ISSUE THREAD

**Issue by Silverfoxcome** [ndierckx/NOVOPlasty#91]
Hi! I was wondering how much time should take for my data to finish running?
I gave NOVOPlasty my raw dataset of two compressed fastq files (.fastq.gz) of 35,0 GB each. 
Uncompressed they are almost 130 GB each. 
My pc has a RAM of 147 and 12 processors.

How much time should I expect my process to last? (It has been running for 48 hours already)

Thank you in advance :)

**Comment by ndierckx** [comment]
That are huge files, so you probably won't have enough memory, you should cancel the run

Just use the max memory option, you don't need that much data at all. Put 10 or 15 as max memory, that should be more than enough. If you want to check for heteroplasmy, let me know, then I will send you an extra script

**Comment by Silverfoxcome** [comment]
> That are huge files, so you probably won't have enough memory, you should cancel the run
> 
> Just use the max memory option, you don't need that much data at all. Put 10 or 15 as max memory, that should be more than enough. If you want to check for heteroplasmy, let me know, then I will send you an extra script

What does the program when I set the max memory parameter to 10 or 15? 
Will it use less data from my datasets?

Yes please, I'll love to check for heteroplasmy as well!

Thanks for all your help :)

**Comment by ndierckx** [comment]
seems good will answer tomorrow about heteroplasmy

**Comment by ndierckx** [comment]
Still interested in heteroplasmy detection?

**Comment by Silverfoxcome** [comment]
Hi! Yes please! I'm still very interested in looking for heteroplasmy!
Thank you so much for all your help :D

**Comment by ndierckx** [comment]
As you can't get a good complete assembly, I would test heteroplasmy on a smaller region.
So make a fasta file with maybe 30000 bp sequence that doesn't contain the inverted repeats
Use that file as a seed and reference for the heteroplasmy detection

**Comment by Silverfoxcome** [comment]
> As you can't get a good complete assembly, I would test heteroplasmy on a smaller region.
> So make a fasta file with maybe 30000 bp sequence that doesn't contain the inverted repeats
> Use that file as a seed and reference for the heteroplasmy detection

I'll do that as soon as I can :D 

Thanks for all your help!!!
