### ISSUE TITLE
regex error?

### ISSUE THREAD

**Issue by siknkrt** [ndierckx/NOVOPlasty#92]
Hi,

Sorry to bother you again. I am trying to assemble chloroplast genome by using NOVOPlasty3.3. But I got following error message again. Please tell me how to solve this problem.

[log.txt](https://github.com/ndierckx/NOVOPlasty/files/3284427/log.txt)

**Comment by ndierckx** [comment]
Hi,

No problem, thanks for reporting. Seems some other users had similar problem. I think I found the problem, so could you redownload the 3.3 version?

**Comment by siknkrt** [comment]
Thank you for the prompt correspondence. Reruns succeeded and finished!

Sincerely yours
