### ISSUE TITLE
How to choose between the 8 Options of chloroplast genome?

### ISSUE THREAD

**Issue by Silverfoxcome** [ndierckx/NOVOPlasty#93]
Hi! Thank you so much for this program! it really has helped me a lot!
I run the program and I obteined 7 contigs:

> ------------Assembly 1 finished: Contigs are automatically merged in Merged_contigs file------------

> Contig 01                  : 48121 bp
> Contig 02                  : 52812 bp
> Contig 03                  : 53088 bp
> Contig 04                  : 13526 bp
> Contig 05                  : 13802 bp
> Contig 06                  : 27579 bp
> Contig 07                  : 27301 bp

The program tells me that with this contigs, there are 8 optiones for a chloroplast genome:

> OPTION 1: Contig Arrangement : 01+03+04+06
> OPTION 2: Contig Arrangement : 01+02+04+07
> OPTION 3: Contig Arrangement : 01+03+05+07
> OPTION 4: Contig Arrangement : 01+03+04+07
> OPTION 5: Contig Arrangement : 01+02+05+06
> OPTION 6: Contig Arrangement : 01+03+05+06
> OPTION 7: Contig Arrangement : 01+02+04+06
> OPTION 8: Contig Arrangement : 01+02+05+07

I wanted to ask if there is a standard way to choose the best option. I was going to map all the reads back to each option and see the coverage and also do a BUSCO analysis (though I don't know if this is recomendable for a chloroplast genome). 
I was also looking if the assemblies make sense given that a chloroplast genome has 2 inverted repeats of aprox 22000 bp (contig 6 and 7 seem like IR candidates given their lengths, but there is no option with an assembly with two contigs 6 or 7 between the LSC and the SSC regions).

Thank you in advance for all your kind help :)

**Comment by ndierckx** [comment]
In more complicated assemblies, i will give more than two options, it's just a way to not just give contigs, but also all the possible assemblies. Are there two assemblies with almost exactly the same length? If so those are more likely to be correct. Ideally you get two options with the only difference the orientation of the section between the inverted repeats. If you have a close reference sequence, you could run it with that option to reduce the contigs...

**Comment by Silverfoxcome** [comment]
Hi!! Thank you for your fast answer!
Yes! The program giving all possible assemblies is really helpful!!!

I have a close reference and I gave it to NOVOPlasty!! I'm assembling the chloroplast genome of purple maize so I gave NOVOPlasty the chloroplast reference genome of maize B73v4: NC_001666.2.  

These are the lengths of each possible assembly, but they are all very similar. 

> OPTION 1: Contig Arrangement : 01+03+04+06 - Assembly length    : 140459 bp
> OPTION 2: Contig Arrangement : 01+02+04+07 - Assembly length    : 140459 bp 
> OPTION 3: Contig Arrangement : 01+03+05+07 - Assembly length    : 140457 bp
> OPTION 4: Contig Arrangement : 01+03+04+07 - Assembly length    : 140458 bp
> OPTION 5: Contig Arrangement : 01+02+05+06 - Assembly length    : 140459 bp
> OPTION 6: Contig Arrangement : 01+03+05+06 - Assembly length    : 140458 bp
> OPTION 7: Contig Arrangement : 01+02+04+06 - Assembly length    : 140460 bp
> OPTION 8: Contig Arrangement : 01+02+05+07 - Assembly length    : 140458 bp

The length of the reference (NC_001666.2) is 140384 bp

Is there something that I could use to choose the best or two best options?
Again, thank you a lot for all the help :)

**Comment by Silverfoxcome** [comment]
Hi!

I'm doing mapping to the 8 different assemblies generated by NOVOPlasty to apply the Assembly Likelihood Estimator (https://github.com/sc932/ALE). 

Also, I aligned all the possible assemblies to the reference genome of the chloroplast of Zea mays and this is what it looks like :D :+1: 
[https://i1164.photobucket.com/albums/q564/Maciel_Rodriguez/align_ref_8opts_mauve_zpshd8hhz5y.jpg](url)
(The one at the top is the reference)
