### ISSUE TITLE
Raw or trimmed data set as input?

### ISSUE THREAD

**Issue by Silverfoxcome** [ndierckx/NOVOPlasty#94]
Hi! 
Sometime ago I ran NOVOPlasty using the whole raw dataset because I didn't have enough space to generate datasets with adapters trimmed. Now I have it, so I was wondering if I should ran again NOVOPlasty with the adapters removed like you say in the intructions:

> DO NOT filter or quality trim the reads!!! Use the raw whole genome dataset (Only adapters should be removed)!

Thank you in advance for your help!

**Comment by ndierckx** [comment]
Hi, usually not trimming causes no problem but if evey read has still adapters at the end its best to trim them. Is it assembly with 8 options? And am on holiday do couldn't look at those. With the 8 options you should first look at the orientation of the inverted repeat, so you can exclude some already https://github.com/ndierckx/NOVOPlasty/issues/79

**Comment by Silverfoxcome** [comment]
Hi! thanks for the quick answer! 
I was mistaken and my sequences are already trimmed (the fastqc report shows no adapters or overrepresented sequences). 
Please, can you tell me what tools could I use to look at the orientation of the inverted repeat? I'm pretty new to the field of bioinformatics. I was using Mauve and I got this [https://imggmi.com/full/2019/6/26/5bbd52d4b1d9d4582b568b6c1e1ee2c8-full.jpg.html](url)

**Comment by ndierckx** [comment]
Hi, just got back from holiday.
Didn't you check the previous topic I added in the last comment?
https://github.com/ndierckx/NOVOPlasty/issues/79
