### ISSUE TITLE
choose correct seed when doing mt-genome assembly

### ISSUE THREAD

**Issue by biocoreexpert** [ndierckx/NOVOPlasty#96]
Hi,
Could I use the whole reference mt-genome as the seed? If the reference mt-genome is known, how do I pick the correct seed sequence?
Best,

**Comment by ndierckx** [comment]
it doesn't matter that much with mitochondria (unless plants), just make sure it is no repetitive region. Whole mitochondiral genome references are sometimes incomplete and have repetitive regions at the start of the sequence, so better to take a region in the middle of the reference.
