### ISSUE TITLE
batch function breaks if individual assembly goes awry

### ISSUE THREAD

**Issue by bishopia** [ndierckx/NOVOPlasty#98]
i'm working with plant mitochondial reads, and while the batch function is great, it does happen to terminate the process when it one of the assemblies hits a snag (ie on assembly 4/10, something goes wrong and assemblies 5-10 are not completed.

This has happened twice now, once each with the following log messages:

```
Reading Input......OK

Scan chloroplast sequence......OK

Building Hash Table......OK

Subsampled fraction: 100.00 %

Retrieve Seed...

COVERAGE IS TOO LOW, SHOULD BE MORE THAN 10X
```

```
Reading Input......OK

Scan chloroplast sequence......OK

Building Hash Table......OK

Subsampled fraction: 100.00 %

Retrieve Seed...

INVALID SEED, PLEASE TRY AGAIN WITH A NEW ONE
```

Any way to get a message for the erroneous Projects but keep moving through the rest of the batch file?

**Comment by ndierckx** [comment]
[NOVOPlasty3.5.zip](https://github.com/ndierckx/NOVOPlasty/files/3405432/NOVOPlasty3.5.zip)

**Comment by ndierckx** [comment]
Could you try with this version? Let me know if it works, because I didn't test it

And plant mitochondria are not easy to assemble, so wouldn't expect too much

**Comment by bishopia** [comment]
Yes! That worked perfectly. When a new seed was required ("INVALID SEED, PLEASE TRY AGAIN WITH A NEW ONE"), no files for that assembly were created, and the script moved on to the next Project. Thank you. Also, I defaulted to saying "plant" mito, but really I have Stramenopile (diatom) data, dunno if you have recommendations on how to improve output for eukaryotic algae in particular with NOVOPlasty.
