### ISSUE TITLE
The * at the end of the assembled chloroplast genome

### ISSUE THREAD

**Issue by Silverfoxcome** [ndierckx/NOVOPlasty#99]
Hi!
I have assembled my chloroplast genome using NOVOPlasty :D 
Thank you so much for your help :)
I have a doubt. At the end of the assembled co genome there is a *, like in the last bases:

`GCATTCAGGGGGG*CCAAGTCAGGTTAGATCTATATCTTTAATGCCTATAAGACAGTCA`

I was annotating the cp genome with cpGavas and this tool tells me that my fasta file has invalid characters:

`Error type 2: input FASTA file contain invalid characters, such as 'N'! Only 'A', 'G', 'C' and 'T' are allowed. Please submit a valid FASTA sequence containing only the four characters`

I guess is that * at the end of the genome sequence. I wanted to know what is that * and if there is a way to work with cpGavas :)

Thanks a lot in advance for all your help :)

**Comment by ndierckx** [comment]
It is written in the manual..
it means the nucleotide before is ambiguous, possible deletion
So just remove it or check alignment if the nuc before is best deleted too

**Comment by Silverfoxcome** [comment]
Thanks! I'll look it up right now!
Thank you for your help!!!

**Comment by Silverfoxcome** [comment]
Sorry for all these questions :)

In the two options of the chloroplast genome assembly I got, there are letters like K, R, M and Y between the A, T, G and C's. 

What does this mean?

Thank you in advance :)

**Comment by ndierckx** [comment]
http://www.bioinformatics.org/sms2/iupac.html

**Comment by Silverfoxcome** [comment]
> http://www.bioinformatics.org/sms2/iupac.html

Thank you!!!! 
I'll now use NOVOPlasty to assembly my mithocondria genome! 
Thank you so much for all your help :D
